### ISSUE TITLE
OAI without S1 interface and S1 interface cannot run on band 3,4, 39, 13, ... I test these band. But it only runs on bad 7. Howto modify to run on other frequency band ?  

### ISSUE THREAD

**Issue by latuan1710** [EttusResearch/uhd#112]

**Comment by mbr0wn** [comment]
This doesn't look like a UHD bug. @ttsou ?

**Comment by ttsou** [comment]
@latuan1710 wrote:
> OAI without S1 interface and S1 interface cannot run on band 3,4, 39, 13, ...

OAI EARFCN and frequency band are configured through eNodeB configuration files, which are independent from UHD. Please see OAI documentation for eNodeB usage instructions.

https://gitlab.eurecom.fr/oai/openairinterface5g/wikis/HowToConnectCOTSUEwithOAIeNBNew
