### ISSUE TITLE
uhd_usrp_make cannot report error messages

### ISSUE THREAD

**Issue by creinke-sandia** [EttusResearch/uhd#114]
It would be helpful to have a function in the C API that performs the same operation as `uhd_usrp_make` but, in addition to returning the error code, also copies an error message into a buffer.  `uhd_usrp_last_error` can't be used if `uhd_usrp_make` fails, and the error codes are too broad for the user to understand what problem caused the failure.

**Comment by mbr0wn** [comment]
When `uhd_usrp_make()` fails, you can use `uhd_get_last_error()` to figure out what went wrong. I'll close this for now -- but please reopen if this wasn't actually what you were looking for.

**Comment by creinke-sandia** [comment]
Ah, yeah, I missed that function.  Thanks!
