### ISSUE TITLE
uhd_usrp_set_tx_dc_offset_enabled and uhd_usrp_set_tx_iq_balance_enabled

### ISSUE THREAD

**Issue by creinke-sandia** [EttusResearch/uhd#115]
[`uhd_usrp_set_tx_dc_offset_enabled(uhd_usrp_handle h, bool enb, size_t chan)`](https://github.com/EttusResearch/uhd/blob/8f9f4184d4917380e2d0a9c35d88fc76ea599b4e/host/lib/usrp/usrp_c.cpp#L1407) and [`uhd_usrp_set_tx_iq_balance_enabled(uhd_usrp_handle h, bool enb, size_t chan)`](https://github.com/EttusResearch/uhd/blob/8f9f4184d4917380e2d0a9c35d88fc76ea599b4e/host/lib/usrp/usrp_c.cpp#L1417) in the C API have no equivalent in the C++ API.

I assume that [`set_tx_dc_offset(const std::complex<double> &offset, size_t chan)`](https://github.com/EttusResearch/uhd/blob/8f9f4184d4917380e2d0a9c35d88fc76ea599b4e/host/include/uhd/usrp/multi_usrp.hpp#L1018) and [`set_tx_iq_balance(const std::complex<double> &correction, size_t chan)`](https://github.com/EttusResearch/uhd/blob/8f9f4184d4917380e2d0a9c35d88fc76ea599b4e/host/include/uhd/usrp/multi_usrp.hpp#L1027) are being called by the respective C functions with the `bool` being coerced to a `std::complex<double>`.

Probably these functions should be removed from the C API (unless adding them to the C++ API make sense.)

Furthermore, the C API is missing functions to actually set the DC offset and IQ balance values for both RX and TX.

**Comment by mbr0wn** [comment]
You're right, they should be removed. I'm moving this to our internal tracker (and thus, closing).
