### ISSUE TITLE
get_c_global_error_string is not thread-safe

### ISSUE THREAD

**Issue by creinke-sandia** [EttusResearch/uhd#116]
[`get_c_global_error_string()`](https://github.com/EttusResearch/uhd/blob/8f9f4184d4917380e2d0a9c35d88fc76ea599b4e/host/lib/error_c.cpp#L52) should not return its string by reference.

`_c_global_error_string` is supposed to be protected by `_error_c_mutex`, but by returning it by reference, the global is accessible after the mutex is unlocked, such that `uhd_get_last_error` could be reading its value while `set_c_global_error_string` is writing it.

**Comment by mbr0wn** [comment]
Thanks, good catch. Ironically, we don't even use that method (although we should). Just FYI, this method isn't supposed to be called by the user. We might move it outside `UHD_API`.

Thanks for all the great comments on the C API!
