### ISSUE TITLE
Documentation Trails on last question

### ISSUE THREAD

**Issue by oogieoogieful** [EttusResearch/uhd#120]
https://kb.ettus.com/UHD_Python_API

<img width="1008" alt="trailing_off" src="https://user-images.githubusercontent.com/7937014/29328329-03255d36-81a7-11e7-9224-be156d752742.png">

I suspect the last sentence has something to do with the limits of one's equipment and code.

**Comment by michael-west** [comment]
Thank you for letting us know about this.  It has been forwarded to Ettus Support for correction.  Going forward, please report any Knowlege Base issues directly to support@ettus.com

**Comment by mbr0wn** [comment]
The sentence was fixed. Thanks @oogieoogieful!
