### ISSUE TITLE
Overflow Error with UHD Python - API

### ISSUE THREAD

**Issue by oogieoogieful** [EttusResearch/uhd#121]
Hello,
I have a USRP n200 with an SBX daughterboard connected via ethernet to a Linux OS (Debian Stretch). The USRP should be acting strictly as a reciever. My python version is Python 2.7.13.  I am modulating a signal in the ISM band.

I am running a modified version example included with the python-api branch, basically I am comparing usrp.MultiUSRP.recv_num_sampls() with our in-house version.

There are probably a couple things wrong, but I am getting an overflow error (out of sequence) error:

```
$ python pyuhd_rx_to_file.py -a usrp2 -o file -f 897e6 -r 10e3 -d 0.25 -c 0 -g 0
[INFO] [UHDlinux; GNU C++ version 6.3.0 20170516; Boost_106200; UHD_3.11.0.python-api-242-g73e6726a] 
[INFO] [USRP2] Opening a USRP2/N-Series device...
[INFO] [USRP2] Current recv frame size: 1472 bytes
[INFO] [USRP2] Current send frame size: 1472 bytes
[WARNING] [MULTI_USRP] The hardware does not support the requested RX sample rate:
Target sample rate: 0.010000 MSps
Actual sample rate: 0.195312 MSps

[INFO] [CAL] Calibration data loaded: /home/erin/.uhd/cal/rx_iq_cal_v0.2_310B331.csv
ERROR_CODE_OVERFLOW (Out of sequence error)D
Traceback (most recent call last):
  File "pyuhd_rx_to_file.py", line 55, in <module>
    main()
  File "pyuhd_rx_to_file.py", line 51, in main
    with open(args.output_file+str(n)+".bin", 'wb') as f:
NameError: global name 'n' is not defined
[ERROR] [UHD] Exception caught in safe-call.
  in virtual dboard_manager_impl::~dboard_manager_impl()
  at /home/erin/Desktop/UHD/MASTER/uhd/host/lib/usrp/dboard_manager.cpp:449
set_nice_dboard_if(); -> RuntimeError: fifo ctrl timed out looking for acks
[ERROR] [UHD] Exception caught in safe-call.
  in virtual usrp2_codec_ctrl_impl::~usrp2_codec_ctrl_impl()
  at /home/erin/Desktop/UHD/MASTER/uhd/host/lib/usrp/usrp2/codec_ctrl.cpp:128
_ad9777_regs.power_down_mode = 1; this->send_ad9777_reg(0); switch(_iface->get_rev()){ case usrp2_iface::USRP2_REV3: case usrp2_iface::USRP2_REV4: _iface->poke32((0x7000 + (4 * (2))), 0x00); break; case usrp2_iface::USRP_N200: case usrp2_iface::USRP_N210: case usrp2_iface::USRP_N200_R4: case usrp2_iface::USRP_N210_R4: _ads62p44_regs.power_down = ads62p44_regs_t::POWER_DOWN_GLOBAL_PD; this->send_ads62p44_reg(0x14); break; case usrp2_iface::USRP_NXXX: break; } -> RuntimeError: fifo ctrl timed out looking for acks
[ERROR] [UHD] Exception caught in safe-call.
  in virtual rx_dsp_core_200_impl::~rx_dsp_core_200_impl()
  at /home/erin/Desktop/UHD/MASTER/uhd/host/lib/usrp/cores/rx_dsp_core_200.cpp:94
this->clear(); -> RuntimeError: fifo ctrl timed out looking for acks
[ERROR] [UHD] Exception caught in safe-call.
  in virtual rx_dsp_core_200_impl::~rx_dsp_core_200_impl()
  at /home/erin/Desktop/UHD/MASTER/uhd/host/lib/usrp/cores/rx_dsp_core_200.cpp:94
this->clear(); -> RuntimeError: fifo ctrl timed out looking for acks
[ERROR] [UHD] Exception caught in safe-call.
  in virtual usrp2_clock_ctrl_impl::~usrp2_clock_ctrl_impl()
  at /home/erin/Desktop/UHD/MASTER/uhd/host/lib/usrp/usrp2/clock_ctrl.cpp:95
this->enable_external_ref(false); this->enable_rx_dboard_clock(false); this->enable_tx_dboard_clock(false); this->enable_dac_clock(false); this->enable_adc_clock(false); this->enable_mimo_clock_out(false); this->enable_test_clock(false); -> RuntimeError: fifo ctrl timed out looking for acks
[ERROR] [UHD] Exception caught in safe-call.
  in virtual usrp2_fifo_ctrl_impl::~usrp2_fifo_ctrl_impl()
  at /home/erin/Desktop/UHD/MASTER/uhd/host/lib/usrp/usrp2/usrp2_fifo_ctrl.cpp:64
this->peek32(0); -> RuntimeError: fifo ctrl timed out looking for acks
[ERROR] [UHD] Exception caught in safe-call.
  in virtual usrp2_clock_ctrl_impl::~usrp2_clock_ctrl_impl()
  at /home/erin/Desktop/UHD/MASTER/uhd/host/lib/usrp/usrp2/clock_ctrl.cpp:95
this->enable_external_ref(false); this->enable_rx_dboard_clock(false); this->enable_tx_dboard_clock(false); this->enable_dac_clock(false); this->enable_adc_clock(false); this->enable_mimo_clock_out(false); this->enable_test_clock(false); -> RuntimeError: fifo ctrl timed out looking for acks
[ERROR] [UHD] Exception caught in safe-call.
  in virtual usrp2_fifo_ctrl_impl::~usrp2_fifo_ctrl_impl()
  at /home/erin/Desktop/UHD/MASTER/uhd/host/lib/usrp/usrp2/usrp2_fifo_ctrl.cpp:64
this->peek32(0); -> RuntimeError: fifo ctrl timed out looking for acks
```

I've plotted the results here:
![uhd_python_api_10e6](https://user-images.githubusercontent.com/7937014/29390382-db51b2f6-82a4-11e7-8f89-4d93db9b0ac8.png)

If I change the sample rate to 50e6, I get hardly anything:

![uhd_python_api_50e6](https://user-images.githubusercontent.com/7937014/29390497-94433532-82a5-11e7-9316-0cafe0812e0a.png)

Normally, I sample at 50e6 samples/sec.  Here is a zoom-in of the modulated signal that I expect to see:
![usrp_ctypes](https://user-images.githubusercontent.com/7937014/29390228-cacc4e6a-82a3-11e7-85a5-366ed09405a6.png)

**Comment by oogieoogieful** [comment]
dang, I hit enter before I was ready.

**Comment by michael-west** [comment]
@oogieoogieful The error is indicating a dropped packet (hence, the 'D' printed in the output).  This is usually indicative of a network issue and not generally due to a bug in the UHD code.  The other errors reported in the output (i.e. fifo ctrl timed out looking for acks) also indicate packet loss on the network.  I recommend testing UDP performance on your network.  For further support, please consider posting on the [usrp-users mailing list ](http://lists.ettus.com/mailman/listinfo/usrp-users_lists.ettus.com)or contacting [Ettus Support](mailto:support@ettus.com).

**Comment by oogieoogieful** [comment]
When I use the uhd c/c++ utilities to capture data (or the in-house capture method), I have no problem with dropped packets. 

I can run the benchmark tests okay for 25e6/50e6 samples/sec capture. 

On the same network using the python api capture I get dropped packets. Therefore, there seems to be a problem the python api.  I originally tested this python api when it was first released.

**Comment by michael-west** [comment]
@oogieoogieful Thanks for the feedback.  We will look into the streaming performance of the Python API.

**Comment by LOVEANDNINENINE** [comment]
Try to check if you are using more than one program to call your USRP device?
