### ISSUE TITLE
Segmentation fault in USRP source in MacOS

### ISSUE THREAD

**Issue by vamsi765** [EttusResearch/uhd#123]
I get the following error [I see boost::task_io_service error as final debug]:

> Segmentation fault: 11

When I create the instance of the usurp_source
`
        self.sdr_source = uhd.usrp_source(
        	",".join(('', args)),
        	uhd.stream_args(
        		cpu_format="fc32",
        		channels=range(1),
        	),
        )
`

This code is autogenerated when I create a USRP source.

The error started after I updated to latest UHD using MacPorts (it did work previously).

Here is the log generated by MacOS:
[usrp_source_error.txt](https://github.com/EttusResearch/uhd/files/1254672/usrp_source_error.txt)

**Comment by michaelld** [comment]
Does this error occur every time you init the USRP, or just sometimes?

What does "port installed and active" return?

Have you tried the "uhd-devel" port? Sometimes fixes are in there that aren't yet in the release. It is, plus or minus, a drop-in replacement of "uhd".

**Comment by vamsi765** [comment]
It does occur all the time.
After updating to und-devel port resolved the issue.

Thanks!

**Comment by michaelld** [comment]
You're welcome! I'm glad moving to the devel port did the trick.
