### ISSUE TITLE
can't simultaneously transmit and receive from the same channel on x310 without underflows

### ISSUE THREAD

**Issue by jwzheng94** [EttusResearch/uhd#128]
[uhd_bug.txt](https://github.com/EttusResearch/uhd/files/1307787/uhd_bug.txt)

Example program attached above. See thread:
http://lists.ettus.com/pipermail/usrp-users_lists.ettus.com/2017-August/026128.html

**Comment by michael-west** [comment]
There is a known issue in UHD 3.10.0.0 and later where buffer sizes that are not aligned with the maximum number of samples per transfer can result in underruns.  We are working to fix it, but there is a simple workaround.  Size your TX buffer to some multiple of the value returned by tx_streamer::get_max_num_samps() and the underruns should go away.

**Comment by michael-west** [comment]
We are tracking this internally and working on a fix.  Closing it here to avoid tracking in multiple places.  Please use the workaround for now and check future release notes for a fix.

**Comment by glouw** [comment]
Any luck on this?
