### ISSUE TITLE
accessing 32 bit user register by name

### ISSUE THREAD

**Issue by mdmikh** [EttusResearch/uhd#146]
There is a typo in body of block_ctrl_base::user_reg_read32 (host/lib/rfnoc/block_ctrl_base.cpp) method when the register is accessed by name. Instead of readback register nonexistent setting register is accessed what causes 'LookupError: Path not found in tree' error. The fix is trivial:

diff --git a/host/lib/rfnoc/block_ctrl_base.cpp b/host/lib/rfnoc/block_ctrl_base.cpp
index 9564d1d..ba2d9a8 100644
--- a/host/lib/rfnoc/block_ctrl_base.cpp
+++ b/host/lib/rfnoc/block_ctrl_base.cpp
@@ -330,7 +330,7 @@ uint32_t block_ctrl_base::user_reg_read32(const std::string &reg, const size_t p
         ));
     }
     return user_reg_read32(uint32_t(
\-        _tree->access<size_t>(_root_path / "registers" / "sr" / reg).get()
\+        _tree->access<size_t>(_root_path / "registers" / "rb" / reg).get()
     ), port);
 }

**Comment by mbr0wn** [comment]
Thanks for finding this and pointing to the correct solution! This will be published soon on the master branch, and then be merged into rfnoc within a few weeks.
