### ISSUE TITLE
Build broken with boost 1.66.0

### ISSUE THREAD

**Issue by fxcoudert** [EttusResearch/uhd#147]
```
/tmp/uhd-20171219-86213-y0p3fu/uhd-release_003_010_002_000/host/lib/transport/udp_zero_copy.cpp:193:29: error: no member named 'native' in 'boost::asio::basic_datagram_socket<boost::asio::ip::udp>'
        _sock_fd = _socket->native();
                   ~~~~~~~  ^
```

`basic_datagram_socket::native` has been [deprecated](http://www.boost.org/doc/libs/1_47_0/doc/html/boost_asio/reference/basic_datagram_socket/native.html) since Boost 1.47.0, released July 11th, 2011. It should be [`native_handle`](http://www.boost.org/doc/libs/1_66_0/doc/html/boost_asio/reference/basic_datagram_socket/native_handle.html) instead.

**Comment by michaelld** [comment]
See also this thread on USRP users: http://lists.ettus.com/pipermail/usrp-users_lists.ettus.com/2017-December/027268.html

**Comment by ilovezfs** [comment]
See https://github.com/EttusResearch/uhd/pull/148

**Comment by mbr0wn** [comment]
@fxcoudert @ilovezfs Thanks for the detailed description and the suggested fix. Goes onto master immediately, and maint and LTS will follow.

**Comment by michaelld** [comment]
@mbr0wn also need to remove boost versions 1.46 and 1.46.0 from the top-level CMakeLists.txt file, as "native_handle" was introduced in 1.47.0 (as mentioned above).

**Comment by mbr0wn** [comment]
Ah, I didn't realize the implications. We can't do that, of course, we have a "contract" that we don't remove Boost versions mid-release. That means we can't actually fix this the same way as we did on master. We'll need to `#ifdef` around those calls.

Bringing to attention of @michael-west.

**Comment by mbr0wn** [comment]
```
#if BOOST_VERSION < 104700                                                                                                                                      
    // use native()
#else
    // use native_handle()
#endif

We've had to resolve to this in the past (https://github.com/EttusResearch/uhddev/blob/8138e3947f4ba935f52329644c44b58da34c45fe/host/lib/transport/nirio/rpc/rpc_client.cpp#L59-L73).

**Comment by mbr0wn** [comment]
Requires
```cpp
#include <boost/version.hpp>
```

**Comment by mbr0wn** [comment]
maint is actually on 1.53 minimum Boost, so we can just cherry-pick. LTS allows for Boost 1.46.

**Comment by michael-west** [comment]
On maint.  LTS required additional code and will be merged soon.
