### ISSUE TITLE
How to add new device to uhd 

### ISSUE THREAD

**Issue by KcMeterCEC** [EttusResearch/uhd#149]
Hi guys,
I have made my new SDR board which is controlled by embedded linux.
> 1. The board is communicate with PC through USB3.0(FTDI), the USB3.0 driver is very simple.

I found the uhd library is an **open source and free** library, so i want to add my SDR board driver to the library.
I have read **UHD Development Manual** which didn't indicate how to port a new device to library.
And I have read the source code, I found the code about  device is located at **uhd/host/lib/usrp**.

But it still make me confused about the **CHDR protocol** and device API.

How can i get a cleaner and simple step to add my device?

**Comment by mbr0wn** [comment]
Either maintain your own branch of UHD, or use the plugin API. Please understand that we don't have resources to support other people's hardware.

**Comment by FFY00** [comment]
You can write your software for SoapySDR which has a UHD plugin making it compatible with the UHD driver.
