### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by robellebor** [EttusResearch/uhd#153]
when i try to execute the command cmake ../ i get an error

     CMake Error at cmake/Modules/UHDComponent.cmake:51 (MESSAGE):
     Dependencies for required component LibUHD not met.
     Call Stack (most recent call first):
     CMakeLists.txt:351 (LIBUHD_REGISTER_COMPONENT)

      -- Configuring incomplete, errors occurred!
      See also "/home/robel/workarea-uhd/uhd/host/build/CMakeFiles/CMakeOutput.log".
      See also "/home/robel/workarea-uhd/uhd/host/build/CMakeFiles/CMakeError.log".

what should i do i tried many things but ....

**Comment by robellebor** [comment]
robel@robel-OptiPlex-760:~/workarea-uhd/uhd/host/build$  cmake -DPYTHON_LIBRARIES=/Library/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib .
-- 
-- Configuring the python interpreter...
-- Python interpreter: /usr/bin/python3
-- Override with: -DPYTHON_EXECUTABLE=<path-to-python>
-- Working off of feature or development branch. Updating version number.
-- Using UHD Images Directory: OFF
-- Build type not specified: defaulting to release.
-- 
-- Configuring Boost C++ Libraries...
-- Could NOT find Boost
-- Boost include directories: /usr/include
-- Boost library directories: /usr/lib/x86_64-linux-gnu
-- Boost libraries: 
-- 
-- Python checking for Python version 2.7 or greater
-- Python checking for Python version 2.7 or greater - found
-- 
-- Python checking for Mako templates 0.4.2 or greater
-- Python checking for Mako templates 0.4.2 or greater - found
-- 
-- Python checking for requests 2.0 or greater
-- Python checking for requests 2.0 or greater - found
-- 
-- Configuring LibUHD support...
--   Dependency Boost_FOUND = 0
--   Dependency HAVE_PYTHON_PLAT_MIN_VERSION = TRUE
--   Dependency HAVE_PYTHON_MODULE_MAKO = TRUE
CMake Error at cmake/Modules/UHDComponent.cmake:51 (MESSAGE):
  Dependencies for required component LibUHD not met.
Call Stack (most recent call first):
  CMakeLists.txt:351 (LIBUHD_REGISTER_COMPONENT)


-- Configuring incomplete, errors occurred!
See also "/home/robel/workarea-uhd/uhd/host/build/CMakeFiles/CMakeOutput.log".
See also "/home/robel/workarea-uhd/uhd/host/build/CMakeFiles/CMakeError.log".



i use ubuntu 17.1

**Comment by robellebor** [comment]
thanks i fixed by changing 

  "Boost_FOUND;HAVE_PYTHON_PLAT_MIN_VERSION;HAVE_PYTHON_MODULE_MAKO" OFF ON)
to this 

  "Boost_FOUND;HAVE_PYTHON_PLAT_MIN_VERSION;HAVE_PYTHON_MODULE_MAKO" ON ON)

**Comment by dkozel** [comment]
@robellebor That looks like you do not have all the dependencies installed. Here is a guide which contains all the dependencies listed. The Ubuntu 17.04 list will almost certainly work for 17.10.

https://kb.ettus.com/Building_and_Installing_the_USRP_Open-Source_Toolchain_(UHD_and_GNU_Radio)_on_Linux#Update_and_Install_dependencies

I hope this works for you. If you have any other questions the mailing list is a great resource and has a good community.

**Comment by audiohacked** [comment]
@robellebor @dkozel The problem is Ubuntu has a different naming scheme for the libboost_python library so CMake is unable to find the proper libraries. Normal naming scheme is "libboost_python2.7" and "libboost_python3.5" but Ubuntu names the libaries "libboost_python-py27" and "libboost_python-py35"

**Comment by noc0lour** [comment]
@audiohacked If that is the case this is most likely a `cmake` bug in Ubuntu since the functionality in the distribution shipped `FindBoost` `cmake` is used. If Ubuntu changes naming for Boost libraries it should account for it in the `cmake` Module.

**Comment by mbr0wn** [comment]
Hm yeah, this is hard to fix from our end.

**Comment by audiohacked** [comment]
@mbr0wn One way to "fix" it is to include a patched FindBoost.cmake module in uhd.

**Comment by rjzak** [comment]
I had this same error, and had to edit the cmake file to ON ON in the Win32 If/Else block. It seems stupid that the else block disables the Python API, despite the required libraries being found.

**Comment by mbr0wn** [comment]
Boost.Python was removed from UHD (and replaced with PyBind11).

**Comment by rjzak** [comment]
In which version? I'm pretty sure that's not documented. I was going over the compilation instructions.

**Comment by mbr0wn** [comment]
You're right, it's on master. Anyhow, I'm not sure what your exact problem is (given the history of this issue), can you please open a new one?

**Comment by awilliamson** [comment]
This definitely needs to be fixed in documentation, or more easily accessible. This has bitten me twice now, from two separate installations.

**Comment by joeldelosangeles** [comment]
> thanks i fixed by changing
> 
> "Boost_FOUND;HAVE_PYTHON_PLAT_MIN_VERSION;HAVE_PYTHON_MODULE_MAKO" OFF ON)
> to this
> 
> "Boost_FOUND;HAVE_PYTHON_PLAT_MIN_VERSION;HAVE_PYTHON_MODULE_MAKO" ON ON)

Which file should be edited?  Thanks

**Comment by joeldelosangeles** [comment]
> > "Boost_FOUND;HAVE_PYTHON_PLAT_MIN_VERSION;HAVE_PYTHON_MODULE_MAKO" OFF ON
> 
> Can please tell me how and where did you change it?

 vim /usr/local/src/uhd/host/CMakeLists.txt

**Comment by hanghoo** [comment]
> thanks i fixed by changing
> 
> "Boost_FOUND;HAVE_PYTHON_PLAT_MIN_VERSION;HAVE_PYTHON_MODULE_MAKO" OFF ON) to this
> 
> "Boost_FOUND;HAVE_PYTHON_PLAT_MIN_VERSION;HAVE_PYTHON_MODULE_MAKO" ON ON)

Thank you very much for sharing the solutions. Could you explain further why we have to change the OFF to ON?

**Comment by kraj** [comment]
I think you are missing a dependency `python-mako` once its installed on the system this error should go away

**Comment by mbr0wn** [comment]
Yeah you really don't have to modify CMakeLists.txt files if you're on a standard Ubuntu or similar

**Comment by K0zero** [comment]
> kraj

this is worked to me  thanks a lot

**Comment by RRoHES** [comment]
I did pip install mako to resolve this issue which download the missing mako module
