### ISSUE TITLE
CMake ignores user requests

### ISSUE THREAD

**Issue by ZeroChaos-** [EttusResearch/uhd#160]
when attempting -DENABLE_MANUAL=YES with doxygen not installed, cmake simply disables the component and moves on without it.  the desired behavior (for all user requests) should be to abort when a user requests something which isn't possible

**Comment by mbr0wn** [comment]
Yes Sir,

this is a bug. I've kicked a patch through our CI system and it will go live soon. Closing this.

**Comment by mbr0wn** [comment]
Fixing this unmasked a bug in our CI system. We're on it, though.
