### ISSUE TITLE
eob flag lost at receive

### ISSUE THREAD

**Issue by mdmikh** [EttusResearch/uhd#168]
In cases when supplied user buffer is larger than one packet receive handler uses metadata from the first packet only. Consider some custom RFNoC block sending end of burst flag in packet headers. The flag will be lost if user application gets multiple packets during single invocation of recv streamer method. Although usage of eob flag in metadata during receive may be not expected, it is useful way to send one bit of additional information, for example to mark symbol boundaries.

One liner fix is below:

```
--- a/host/lib/transport/super_recv_packet_handler.hpp
+++ b/host/lib/transport/super_recv_packet_handler.hpp
@@ -288,6 +288,7 @@ public:

             //return immediately if end of burst
             if (_queue_metadata.end_of_burst) {
+                metadata.end_of_burst = true;
                 break;
             }
         }
```

**Comment by mbr0wn** [comment]
@mdmikh We could replicate, but we couldn't use your fix verbatim (the eob assignment needs to happen elsewhere). Thanks for bringing this up! Our fix will go live within a few days.
