### ISSUE TITLE
demuxer unexpected sid error

### ISSUE THREAD

**Issue by nitha2000** [EttusResearch/uhd#173]
I'm running srsLte in the same setup as #171 and, often, I'm getting "recv packet demuxer unexpected sid 0x80ffc0..." errors. The throughput goes really low as a result of this error.

**Comment by michael-west** [comment]
@nitha2000 Try adding "recv_frame_size=1024" to the device arguments.  A few others have encountered the issue and that has worked for them.  We have an open issue for it on our internal issue tracker, but have not yet tracked down the root cause.  We hope to soon.
