### ISSUE TITLE
E310 update prohibits input stream arg from specifying "fpga=<newimage>"

### ISSUE THREAD

**Issue by ejk43** [EttusResearch/uhd#179]
When updating E310 rfnoc-devel recently, I found I could not change my fpga image using command line args. 

For example, the following command still loads the default image:

`uhd_usrp_probe --args "fpga=myimage.bit"`

I believe this is due to the update in this commit, which creates device_addr_cp but does not copy the existing device_addr passed to e300_impl: https://github.com/EttusResearch/uhd/commit/51ecda41e3c57883ee4787cec0a8aede6020d092#diff-9cdf6bee7578727d7268dd7e7481fd82

**Comment by mbr0wn** [comment]
Many thanks for the report and the fix.
