### ISSUE TITLE
n3xx support in uhd_image_builder.py 

### ISSUE THREAD

**Issue by MichaelFay** [EttusResearch/uhd#185]
It appears that the n3xx is not yet implemented in the uhd_image_builder.py, it would be nice to utilize this tool for n3xx.

**Comment by mbr0wn** [comment]
@MichaelFay you are absolutely right, and we'll get it in by the next UHD release.

**Comment by mbr0wn** [comment]
...and by the 'next release', I don't mean 3.12.0.0 (sorry), we're too far in the RC for that.

**Comment by mbr0wn** [comment]
This has been fixed.
