### ISSUE TITLE
No such a file or directory

### ISSUE THREAD

**Issue by FarhadMir** [EttusResearch/uhd#188]
I just reinstalled uhd and now when I try to run any of the .cpp file inside examples directory on ubuntu terminal, it keeps saying no such a file or directory as below:

~/workarea/uhd/host/examples$ ./rx_ascii_art_dft --args “addr=192.168.10.2” --freq 98e6 --rate 5e6 --gain 20 --bw 5e6 --ref-lvl -50
bash: ./rx_ascii_art_dft: No such file or directory
any idea what the issue might be?
 
![image](https://user-images.githubusercontent.com/36164448/41357942-48c72522-6ef5-11e8-9a49-c2a32adbca3a.png)

**Comment by dkozel** [comment]
Hello @FarhadMir It looks like you are trying to run the examples in the source code directory, not in your install or build directory. Look in your installation location in the `lib/uhd/examples` directory.

If that does not work could you please send an email to the USRP users email list? We can help better there.
http://lists.ettus.com/mailman/listinfo/usrp-users_lists.ettus.com
