### ISSUE TITLE
invalid new-expression of abstract class type error when running pybombs e3xx-rfnoc recipe

### ISSUE THREAD

**Issue by wfdanowitz** [EttusResearch/uhd#196]
Issue with latest version of pybombs, with latest github recipe lists when building UHD. Replicated with both ubuntu 18.04 and ubuntu 16.04. Console output (with username redacted) below:

[  2%] Built target uhd_rpclib
[  2%] Building CXX object lib/CMakeFiles/uhd.dir/usrp/e300/e300_remote_codec_ctrl.cpp.o

~/e310/src/uhd/host/lib/usrp/e300/e300_remote_codec_ctrl.cpp: In static member function 'static uhd::usrp::ad9361_ctrl::sptr uhd::usrp::e300::e300_remote_codec_ctrl::make(uhd::transport::zero_copy_if::sptr)':
~/e310/src/uhd/host/lib/usrp/e300/e300_remote_codec_ctrl.cpp:277:54: error: invalid new-expression of abstract class type 'uhd::usrp::e300::e300_remote_codec_ctrl_impl'
     return sptr(new e300_remote_codec_ctrl_impl(xport));
                                                      ^
~/e310/src/uhd/host/lib/usrp/e300/e300_remote_codec_ctrl.cpp:18:7: note:   because the following virtual functions are pure within 'uhd::usrp::e300::e300_remote_codec_ctrl_impl':
 class e300_remote_codec_ctrl_impl : public e300_remote_codec_ctrl
       ^
In file included from ~/e310/src/uhd/host/lib/usrp/e300/e300_remote_codec_ctrl.hpp:12:0,
                 from ~/e310/src/uhd/host/lib/usrp/e300/e300_remote_codec_ctrl.cpp:8:
~/e310/src/uhd/host/lib/include/uhdlib/usrp/common/ad9361_ctrl.hpp:109:18: note: 	virtual void uhd::usrp::ad9361_ctrl::set_timing_mode(const string&)
     virtual void set_timing_mode(const std::string &timing_mode) = 0;
                  ^
~/e310/src/uhd/host/lib/usrp/e300/e300_remote_codec_ctrl.cpp:278:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
lib/CMakeFiles/uhd.dir/build.make:4411: recipe for target 'lib/CMakeFiles/uhd.dir/usrp/e300/e300_remote_codec_ctrl.cpp.o' failed
make[2]: *** [lib/CMakeFiles/uhd.dir/usrp/e300/e300_remote_codec_ctrl.cpp.o] Error 1
CMakeFiles/Makefile2:108: recipe for target 'lib/CMakeFiles/uhd.dir/all' failed
make[1]: *** [lib/CMakeFiles/uhd.dir/all] Error 2
Makefile:143: recipe for target 'all' failed
make: *** [all] Error 2
PyBOMBS.Packager.source - ERROR - Build failed. See output above for error messages.
PyBOMBS.Packager.source - ERROR - Problem occurred while building package uhd:
Build failed.
PyBOMBS.install_manager - ERROR - Error installing package uhd. Aborting.

**Comment by trungnob** [comment]
Thanks for reporting this. 
The latest fix is at https://github.com/EttusResearch/uhd/commit/eec24d7b0442616fdbe9adf6b426959677e67f92
