### ISSUE TITLE
Calling uhd::usrp::multi_usrp::make and then exit blocks on USRP B100

### ISSUE THREAD

**Issue by ashley-b** [EttusResearch/uhd#200]
Simple test case never exits.
Software used: v3.13.0.0 f114cfa0ddf70228d10462758c2b8e878c993f5d
Hardware used: USRP B100 and WBX v3 board

```
int main()
{
	auto usrp = uhd::usrp::multi_usrp::make(std::string());
}
```

I found the problem to be a helper thread
https://github.com/EttusResearch/uhd/blob/f114cfa0ddf70228d10462758c2b8e878c993f5d/host/lib/usrp/common/fifo_ctrl_excelsior.cpp#L75
It still uses old boost::this_thread::interruption_requested when this thread is launched from std::thread.

**Comment by mbr0wn** [comment]
Thanks for the report! Also, thanks a lot for pointing out the offending line.
I pushed a quick fix to https://github.com/EttusResearch/uhd/tree/b100/thread_block, but I haven't tested it yet (I actually need to find a B100 first) and it needs to run through our CI system. If you like, you can give it a shot while you wait.

**Comment by ashley-b** [comment]
Thanks for the quick fix. I will test it out later today.

**Comment by ashley-b** [comment]
Just checkout that branch and tested it. Fixed the blocking issue.
Thanks.

**Comment by mbr0wn** [comment]
@ashley-b I'll close this, the fix needs to go through internal review before we can merge but will go onto master branch soon.
