### ISSUE TITLE
UHD FPGA rfnoc-devel uses noc_shell v. 4, but UHD rfnoc-devel only supports noc_shell v. 2

### ISSUE THREAD

**Issue by wfdanowitz** [EttusResearch/uhd#205]
## Issue Description ##
noc_shell version used by latest uhd-fpga rfnoc-devel build (version 4) is incompatible with latest uhd rfnoc-devel branch (only supports up to version 2). Results in following error: RuntimeError: RuntimeError: FPGA component `noc_shell' is revision 4 and UHD supports revision 2. Please either upgrade UHD  (recommended) or downgrade the FPGA image.

## Setup Details ##
Image generated using pybombs rfnoc recipe. Run on e310 cross-compiled image using pybombs e3xx-rfnoc recipe. Both UHD and the fpga-src submodule are on rfnoc-devel branch.

## Expected Behavior ##
Flow graph will run without error

## Actual Behaviour ##
RuntimeError: RuntimeError: FPGA component `noc_shell' is revision 4 and UHD supports revision 2. Please either upgrade UHD  (recommended) or downgrade the FPGA image.

## Steps to reproduce the problem ##
pybombs update 
Use uhd_image_builder to build a custom fpga image.
Attempt to run a grc flow-chart using the custom image

## Additional Information ##
The "master" UHD branch supports noc_shell version 4, but the other branches do not.

**Comment by mbr0wn** [comment]
@wfdanowitz Thanks for reporting. If you switch to master branch on FPGA as well as UHD, then you will have compatible code. I'm not sure why the rfnoc-devel branches are out of sync, but we have deprecated them a few weeks ago. Now, all the development is done on `master` (and you need to specify `-DENABLE_RFNOC=ON` when running CMake on UHD).

I will update the PyBOMBS recipes ASAP. Again, thanks for reporting.
