### ISSUE TITLE
Problem with leading 0s in auto-generated noc-ids from rfnocmodtool

### ISSUE THREAD

**Issue by wfdanowitz** [EttusResearch/uhd#209]
## Issue Description ##
I used rfnocmodtool from UHD3.13 to generate a new noc block. The id it assigned the block had a leading 0. Unfortunately, the tool appears to have dropped the leading 0 in the auto-generated xml file, which led to grc and uhd_usrp_probe not being able to find the controller and name for the block.

## Setup Details ##
UHD3.13 built with rfnoc flags on

## Expected Behavior ##
I expect the full ID to be put into the block xml

## Actual Behaviour ##
The leading zero gets dropped, and the tool can't associate the fpga block ID with the XML block ID

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue
e.g. command lines, GNU Radio flow graph screenshot and .grc etc]

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by mbr0wn** [comment]
Couldn't reproduce, this might have been fixed. Thanks for raising!
