### ISSUE TITLE
Start of Burst (tx_timed_samples.cpp)

### ISSUE THREAD

**Issue by glouw** [EttusResearch/uhd#210]
https://github.com/EttusResearch/uhd/blob/4e084337e685204a0142d1dff9e41b4e03d0b582/host/examples/tx_timed_samples.cpp#L77

Should be start_of_burst = true for first packet?

**Comment by michael-west** [comment]
@glouw  It should, but it doesn't really matter.  The start_of_burst flag is essentially ignored.  The TX control in the FPGA infers the start of the burst by the presence of the data and does not pay any attention to the flag.

**Comment by glouw** [comment]
That sounds a little dangerous for an open source code base, don't you think? You do after all have forks which rely on this functionality.

**Comment by michael-west** [comment]
There is nothing in the UHD or FPGA code that relies on start_of_burst for TX.  Any past code that may have relied on it will be prevented from running due to a compat number mismatch between the UHD and FPGA.

**Comment by glouw** [comment]
Yes, but your UHD has forks with their own multi_usrp entry points and custom FPGA images that use these tests _and_ rely on start of burst flags. It would be nice to have it do what it advertises.
