### ISSUE TITLE
uhd-3.13.1.0-rc1 N3XX and E32x manually disabled by -DENABLE_N300[E320]=OFF but devices have been added to test target

### ISSUE THREAD

**Issue by amore-amore** [EttusResearch/uhd#225]
--
-- Adding B2XX device test target
-- Adding N3XX device test target
-- Adding E32x device test target
--

**Comment by brentstapleton** [comment]
Hey @amore-amore, thanks for the report. N3xx and E32x devtest targets can be disabled by removing MPMd from your build. That is, add the CMake flag `-DENABLE_MPMD=OFF`.

I've opened an internal Issue to track this.
