### ISSUE TITLE
X310 RFNoC environment setup problem（Can not download RFNoc FPGA image）

### ISSUE THREAD

**Issue by EiffelYin5** [EttusResearch/uhd#232]
## Issue Description ##
Hi,
I'm following the guide https://kb.ettus.com/Getting_Started_with_RFNoC_Development to setup this environment.
The first issue I found is that if I use the pybombs by this manual.
Each time i use this command " $ source ./setup_env.sh"
It will not come up with the version of UHD 4.0.0.rfnoc-devel-xxxxxxxx
but the UHD 3.14.xxxxxxx 
So I changed the file named receipts to select the branch of rfnoc-devel instead of the master and I can get the right version of UHD by pybombs.
Then I found when I use the command of uhd_images_downloader
It will not download the default FPGA image about RFNoC, just the basic image.
And I found this video on youtube that you present https://www.youtube.com/watch?v=j-EfyPVpaJ8
It seems the problem is with the version of UHD 4.0.0.rfnocxxxxxxx
In the video the version is UHD_4.0.0.rfnoc-devel-348-g2c2e1a99
But mine is UHD_4.0.0.rfnoc-devel-702-geec24d7b
And i read the uhd_images_downloader.py so maybe the problem is my version cannot find the FPGA image about the right version, it will find the cache folder to other version.

So my question is :
1. How can i download the right rfnoc FPGA image for this UHD version?
2. What the difference between this two version, can i just manually download from here  http://files.ettus.com/binaries/images/uhd-images_4.0.0.rfnoc-devel-238-g39a41476.zip
But will there some problems using under this UHD version ?  

![image](https://user-images.githubusercontent.com/41133366/49138221-9a231800-f329-11e8-8590-456298e77f61.png)
This the version in the youtube video
![image](https://user-images.githubusercontent.com/41133366/49138260-b2933280-f329-11e8-943d-6bc807a79ecb.png)
This is my version when I setup this software

**Comment by paul1408** [comment]
I am building from binaries the latest uhd rfnoc-devel branch but the uhd_images_downloader has the same behaviour, is there a tag of previous version that I can checkout to make sure I get a working fpga image?

**Comment by mbr0wn** [comment]
Can you switch to master branch, or are you locked to rfnoc-devel?

**Comment by EiffelYin5** [comment]
I asked the Ettus support department and I got the point so far.
It goes like:
The KB is out dated in some part. Please checkout the mster branch of UHD, gnuradio and gr-ettus and follow "Create the development environment manually part" in the RFNOC Application Note to install.

By default RFNoC is not enabled and RFNoC image is not downloaded. You should add "-DENABLE_RFNOC=ON" option when using cmake in UHD to add RFNoC support. And follow the steps in Application Note to generate RFNOC image.

Hope it help

**Comment by paul1408** [comment]
I switched to the master branch and build v3.13.1 with "-DENABLE_RFNOC=ON", but when i use uhd_images_downloader for X310 I was expecting to get the FFT RFNoC block in the image, instead the image only has DDC and DUC. What USRP are you using EiffelYin5 and do uou have all the RFNoC blocks available?

With the old rfnoc-devel branch I had the image for X310 containing RFNoC FFT, fosphor etc.

**Comment by EiffelYin5** [comment]
> I switched to the master branch and build v3.13.1 with "-DENABLE_RFNOC=ON", but when i use uhd_images_downloader for X310 I was expecting to get the FFT RFNoC block in the image, instead the image only has DDC and DUC. What USRP are you using EiffelYin5 and do uou have all the RFNoC blocks available?
> 
> With the old rfnoc-devel branch I had the image for X310 containing RFNoC FFT, fosphor etc.
