### ISSUE TITLE
TwinRX,If I use 'set_command_time', then I cannot receive anything.

### ISSUE THREAD

**Issue by zlinwei** [EttusResearch/uhd#239]
My codes:
```cpp
uhd::tune_result_t tune_resp = usrp->set_rx_freq(uhd::tune_request_t(freq, lo_off), 0);
uhd::tune_request_t tune_req;
tune_req.rf_freq = freq;
tune_req.dsp_freq = tune_resp.actual_dsp_freq;
tune_req.rf_freq_policy = uhd::tune_request_t::POLICY_MANUAL;
tune_req.dsp_freq_policy = uhd::tune_request_t::POLICY_MANUAL;

for (size_t j = 1; j < this->_channel_nums.size(); ++j) {
        usrp->set_rx_freq(tune_req, j);
        std::cout << boost::format("Actual RX Freq: %f MHz...") % (_usrp->get_rx_freq(j) / 1e6) << std::endl;
}

/// tune synchronous.
auto now = usrp->get_time_now();
usrp->set_command_time(now + uhd::time_spec_t(0.1));
usrp->set_rx_freq(tune_req, 0);
usrp->set_rx_freq(tune_req, 1);
usrp->set_rx_freq(tune_req, 2);
usrp->set_rx_freq(tune_req, 3);

usrp->clear_command_time();
```

Is there any problems in my codes? 
It works correctly without 'tune synchronous'.
Thank you.

**Comment by michael-west** [comment]
@zlinwei Please follow the template when reporting issues.  The information is necessary to reproduce/troubleshoot the issue.

Your code example is incomplete, so it cannot be used to reproduce the problem.  There is nothing obviously wrong with the posted code, but there may be issues elsewhere.  For example, does your code call usrp->set_time_unknown_pps() to synchronize the times across the channels?

**Comment by zlinwei** [comment]
Thanks for your response.
I have used usrp->set_time_next_pps before I receive data, But It didn't work too. Is there any example of "TwinRx" with LO sharing?

**Comment by zlinwei** [comment]
I changed 
tune_req.rf_freq = freq;
to 
tune_req.rf_freq = tune_resp.actual_rf_freq  .. then it works.
Thanks so much.
