### ISSUE TITLE
Out-of-bounds array access in uhd/host/examples/ascii_art_dft.hpp

### ISSUE THREAD

**Issue by starsway** [EttusResearch/uhd#242]
Hi,

I am using the latest version

> [INFO] [UHD] linux; GNU C++ version 6.3.0 20170516; Boost_106200; UHD_3.14.0.0-20-gf63c089a

of the program [uhd/host/examples/rx_ascii_art_dft.cpp](https://github.com/EttusResearch/uhd/blob/master/host/examples/rx_ascii_art_dft.cpp) with a USRP N210 like this:

`$ ./examples/rx_ascii_art_dft --args "addr=192.168.10.2" --rate 2e6 --freq 13545e3 --gain 0 --ant RX1 --subdev A:A --bw 1e6 --ref-lvl -70 --frame-rate 10`

and have observed several occurrences where the program stops (this may takes a few seconds or up to a few (< 5) minutes) with the following error message:

> Error: basic_string::at: __n (which is 4) >= this->size() (which is 4)

After a little bit of instrumentation, I pinpointed the issue in the following piece of code in file [uhd/host/examples/ascii_art_dft.hpp](https://github.com/EttusResearch/uhd/blob/master/host/examples/ascii_art_dft.hpp) (lines 234-235):

```
                if      (scaled-z > 1) frame.get_plot(b, z) = syms.at(syms.size()-1);
                else if (scaled-z > 0) frame.get_plot(b, z) = syms.at(size_t((scaled-z)*syms.size()));
```

If the following equality holds:

scaled - z == 1

then the second clause is executed leading to an attempt to access the variable 'syms' at index syms.size() (which happens to be 4, but that's not relevant in itself).

I think an obvious fix would be to replace the first, strict condition by a one which is not strict, like this:
```
                if      (scaled-z >= 1) frame.get_plot(b, z) = syms.at(syms.size()-1);
```

I can try and provide a pull request if necessary.

Thanks and regards.

**Comment by mbr0wn** [comment]
@starsway Thanks so much. Your suggestion is sensible. I've submitted a fix like you suggested to our internal CI pipeline, and it looks good. It will be coming out soon.
