### ISSUE TITLE
error C2039: 'noncopyable': is not a member of 'boost'

### ISSUE THREAD

**Issue by bd5rv** [EttusResearch/uhd#245]
## Issue Description ##
I try to build UHD with VS2017 on Windows 10. It failed due to

uhd/host/lib/include/uhdlib/usrp/cores/gpio_atr_3000.hpp error C2039: 'noncopyable': is not a member of 'boost'. 

## Setup Details ##
UHD:v3.14.0.0-a1-20181220-85-g33233e5c7
Boost: 1.69.0
Compiler: Visual Studio 2017 Community Edition
OS: Windows 10 x64

## Additional Information ##
Add #include <boost/noncopyable.hpp> to gpio_atr_3000.hpp, then the build succeeded.

**Comment by pswiatki** [comment]
Just hit the  same:

uhd_config_info --print-all
UHD 3.14.0.0-0-gabf0db4e
Build date: Sat, 02 Feb 2019 17:35:31
C compiler: GNU 8.2.1
C++ compiler: GNU 8.2.1
C flags: -DHAVE_CONFIG_H -DUHD_LOG_MIN_LEVEL=1 -DUHD_LOG_CONSOLE_LEVEL=2 -DUHD_LOG_FILE_LEVEL=2 -DUHD_LOG_CONSOLE_COLOR
C++ flags: -DHAVE_CONFIG_H -DUHD_LOG_MIN_LEVEL=1 -DUHD_LOG_CONSOLE_LEVEL=2 -DUHD_LOG_FILE_LEVEL=2 -DUHD_LOG_CONSOLE_COLOR -fvisibility=hidden -fvisibility-inlines-hidden
Enabled components: LibUHD, LibUHD - C API, LibUHD - Python API, Examples, Utils, Tests, USB, B100, B200, USRP1, USRP2, X300, N230, MPMD, N300, N320, E320, OctoClock
Install prefix: /usr/local
Boost version: 1.69
Libusb version: 1.0.24
Package path: /usr/local
Images directory: 
ABI version string: 3.14.0

So, it is not pushed to master yet?

**Comment by pswiatki** [comment]
Well... Sorry, I might have been a bit too fast here: The problem manifested itself differently:
uhd/host/lib/include/uhdlib/usrp/cores/gpio_atr_3000.hpp:20:42: error: expected class-name before '{' token
 class gpio_atr_3000 : boost::noncopyable {
                                          ^
Adding #include <boost/noncopyable.hpp> to gpio_atr_3000.hpp fixed the build for me.
Should it be put as another issue?

**Comment by michaelld** [comment]
No let's just leave this as is. We're working internally to decide how much to fix here. We have a "minimal" version just for these tweaks, and a "maximal" version that tweaks all boost::noncopyable to go through an internal header. One way or the other a fix will get in place for the next UHD RC. Sorry it didn't for RC1!

**Comment by pswiatki** [comment]
Alright! No problem. Fortunately, it wasn't too difficult to figure out and build UHD properly. By the way - and this is the question for UHD and more generally GR as well - is the **master** branch the active development branch so it is quite normal the code doesn't build for one reason or another or such situation is rather abnormal and code should build nicely under normal circumstances?
I use a continuous integration approach at work (Jenkins et consortes) and any build breaks are promptly signalled to those who ought to know :) Not that I would advocate its use here, but it certainly taught me some discipline.

**Comment by michaelld** [comment]
Yes the master branch is where active development happens; that branch usually works, though it is not guaranteed to as sometimes a commit breaks something. We do our best to test both personally as well as with CI, but CI doesn't always work correctly and our personal testing can only go so far; that & there are some things that are quite difficult to really test for across all systems! We do our best to keep master buildable and useable. CI is a good thing when it is well configured and working properly!

**Comment by rmx-it** [comment]
Hi,
I also get the same errors on FreeBSD12 uhd 3.14.0.0-rc1 and boost 1.69

**Comment by michaelld** [comment]
@rmx-it what compiler?

BTW> The fixes we have didn't make it into RC1  ... we'll make sure they are in RC2 though.

**Comment by rmx-it** [comment]
Zitat von Michael Dickens <notifications@github.com>:

> @rmx-it what compiler?
>

$ c++ -v
FreeBSD clang version 6.0.1 (tags/RELEASE_601/final 335540) (based on  
LLVM 6.0.1)
Target: x86_64-unknown-freebsd12.0
Thread model: posix
InstalledDir: /usr/bin


> BTW> The fixes we have didn't make it into RC1  ... we'll make sure  
> they are in RC2 though.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/EttusResearch/uhd/issues/245#issuecomment-461554681



Gruß
---
Michael Reifenberger

**Comment by michaelld** [comment]
@rmx-it OK thanks. Makes sense. Apparently GCC doesn't have this issue; it's a clang thing, somehow. Easy to fix at least!

**Comment by pswiatki** [comment]
I tried with GCC 8.2.1 and hit the issue.

**Comment by michaelld** [comment]
FYI the patch I posted here will be in the next RC ... it fixes the boost::noncopyable issues with minimum changes, at least in our testing. Once the next RC is released, there will be opportunities for feedback as to whether we succeeded here :)

**Comment by mbr0wn** [comment]
93ca7c4d3c46a88feccc3faa8d923b1d0f10e281

**Comment by rmx-it** [comment]
It compiles now.
BTW: Where to get the proper firmware images for 3.14.0.0rc1?

Thanke!
---
Michael

**Comment by michaelld** [comment]
Great! Thanks for reporting back your success!

To get the correct images for your UHD install, use the images downloader provided by the UHD install itself: should be $PREFIX/share/uhd/utils/uhd_images_downloader.py or $PREFIX/lib/uhd/utils/uhd_images_downloader.py .
