### ISSUE TITLE
Scoped Lock used incorrectly.

### ISSUE THREAD

**Issue by taliver** [EttusResearch/uhd#246]
Before filing an issue, search for solutions here:
- USRP users mailing list (http://lists.ettus.com/mailman/listinfo/usrp-users_lists.ettus.com)
- https://kb.ettus.com/Knowledge_Base
- https://files.ettus.com/manual/

## Issue Description ##
In 
src/host/lib/usrp/e300/e300_eeprom_manager.cpp

A mutex lock is declared as:
boost::mutex::scoped_lock(_mutex);

Which should actually be:
boost::mutex::scoped_lock  _some_lock_name(_mutex);

This is on the 3.13 branch (at least).

**Comment by taliver** [comment]
It's also in : e300_sensor_manager.cpp

Thanks.

**Comment by michael-west** [comment]
@taliver  Thanks again.  The issue has been raised to R&D.

**Comment by mbr0wn** [comment]
All gone on master.
