### ISSUE TITLE
Who can give me a sample that access registers of b200 ? 

### ISSUE THREAD

**Issue by z00254829** [EttusResearch/uhd#277]
## Issue Description ##

I try to access registers of b200 device with  multi_usrp_impl::write_register/read_register,but it throw "register IO not supported for this device".Then I call multi_usrp_impl::enumerate_registers, it return  an empty vector. 
Who can give me an sample of access registers of b200 device.Thank you!

**Comment by mbr0wn** [comment]
I think this manual page should answer your Q: http://files.ettus.com/manual/page_usrp_b200.html#b200_customfpga
