### ISSUE TITLE
links to knowledge base in README return 404

### ISSUE THREAD

**Issue by julidau** [EttusResearch/uhd#285]
## Issue Description ##
The knowledge base linked to in the README.md under **Documentation** seems to be dead. 
http://www.ettus.com/kb/detail/frequently-asked-questions just shows a 404, as does http://www.ettus.com/kb in general.

## Additional Information ##
I would personally rate this as low priority, but since there seems to be no issue mentioning this already i thought create one…

**Comment by mbr0wn** [comment]
Thanks for pointing this out! We'll have a fix out ASAP.
