### ISSUE TITLE
choppy tx signal

### ISSUE THREAD

**Issue by Meown12** [EttusResearch/uhd#286]
## Issue Description ##
Playing around with gps-sdr-sim and a realtime adaption using UHD I ran into a problem regarding sampling. I basically copied the tx_samples_c.c setup and expected my signal to be a normal gps c/a signal.

## Setup Details ##
Ubuntu 18.04.2 64 bit 
Ettus B200 via USB3
GNU C++ version 7.3.0; Boost_106501; UHD_003.010.003.000-0-unknown from packet sources
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

## Expected Behavior ##
broad signal at 1.57542 GHz.

## Actual Behaviour ##
The signal fluctuates strongly leaving blanks in between. 

## Steps to reproduce the problem ##
when unpacking the attached archive you can build it with make or cmake and the run `./bladegps -e ephemeris.txt -c master_clock_rate=50e6`

What would cause such an issue?
Maybe someone had a similar problem?

Thanks,

Max

![signalfull](https://user-images.githubusercontent.com/13763047/59590622-c8611d00-90ec-11e9-8955-589a16385fd8.png)
![signal](https://user-images.githubusercontent.com/13763047/59590623-c8611d00-90ec-11e9-8ba0-3203676e6d44.png)
[uhdGPS.zip](https://github.com/EttusResearch/uhd/files/3295951/uhdGPS.zip)

**Comment by natetemple** [comment]
@meown12 It's unclear if this is a UHD bug, so I'm going to close this github issue. Please email support@ettus.com directly and we can help further debug the issue there.
