### ISSUE TITLE
Building on Odroid XU4/Similar ARM Based Systems

### ISSUE THREAD

**Issue by bleckers** [EttusResearch/uhd#287]
## Issue Description ##
Build fails at 11% build with "error: inlining failed in call to always_inline .... target specific option mismatch .... float32x4_t"

## Setup Details ##
Odroid XU4 with Ubuntu 18.04.

## Steps to reproduce the problem ##
Building with any current release branch using kb instructions on XU4 - https://kb.ettus.com/Building_and_Installing_the_USRP_Open-Source_Toolchain_(UHD_and_GNU_Radio)_on_Linux

## Fix ##
Include the following in the CMakeLists.txt at the top to allow it to compile:

set(NEON_FLAGS "-DENABLE_NEON -mfloat-abi=hard -mfpu=neon-vfpv4 -mcpu=cortex-a15 -Ofast")
set(CMAKE_CXX_FLAGS "-std=c++0x ${CMAKE_CXX_FLAGS} -Wno-format-security ${NEON_FLAGS}")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${NEON_FLAGS}")

## Additional Information ##

Might want to add if((CMAKE_SYSTEM_PROCESSOR MATCHES "^arm")) to CMakeLists file (would require further testing).

**Comment by natetemple** [comment]
@bleckers Thanks for the feedback. I'm closing this issue and moving to our internal tracker where we will review. We may add this to UHD or document it on the KB.
