### ISSUE TITLE
Vivado License Documentation

### ISSUE THREAD

**Issue by jsaylor525** [EttusResearch/uhd#291]
## Issue Description ##

Documentation for Xilinx Licenses

## Setup Details ##

N/A

## Expected Behavior ##

One of the documents should indicate the required licenses to build the FPGA. 
I'm mainly concerned with the E-3XX series but this is required for all so that projects
can properly budget.

**Comment by natetemple** [comment]
@jsaylor525 Thanks for the feedback. I'm closing this issue and moving to our internal tracker and we will have an update to the manual in an upcoming UHD release.

Just for reference though below are the current requirements:

The E310, E312, and E313 can use the free WebPACK version of Vivado.

The E320, X3xx, N3xx all require a paid System or Design edition of Vivado.

The N2xx and B2xx require a paid Vivado ISE version.
