### ISSUE TITLE
noc_block_split_stream.v bug

### ISSUE THREAD

**Issue by garengllc** [EttusResearch/uhd#299]
There is a problem with the module that does not allow it to respond to uhd_usrp_probe correctly (or any flowgraph) even though it builds fine.

The problem is that since the block has two outputs, the rb_stb of noc_shell is expecting two bits, but the code has:`    .rb_stb(1'b1), .rb_data(64'd0), .rb_addr(),
`

It should be changed to:`    .rb_stb(2'b11), .rb_data(64'd0), .rb_addr(),
`

The FPGA build will complete as-is, but when you try to do a probe, you get the dreaded command timeout error.  The above change seems to get past that.

**Comment by natetemple** [comment]
@garengllc this has been fixed with this commit: https://github.com/EttusResearch/fpga/commit/1102779f49d44c9e8b88ce7251d203eb62ae26c9 which will be on the next UHD release.
