### ISSUE TITLE
man page compression should be optional

### ISSUE THREAD

**Issue by ZeroChaos-** [EttusResearch/uhd#300]
most linux distribution packaging software handles selectable man page compression which is broken by force compressing the man pages with gzip.  This default behavior is fine (although I'd prefer xz), but there needs to be a way to disable it so the package manager can handle it.

**Comment by michaelld** [comment]
Can you test this patch? It works in my testing for both compressed (default) and uncompressed.

[patch-uhd_man_pages_optional_compress.diff.txt](https://github.com/EttusResearch/uhd/files/3677336/patch-uhd_man_pages_optional_compress.diff.txt)

**Comment by ZeroChaos-** [comment]
glorious, tested with and without the flag and this appears to work and keep the original default.  Please accept this patch.

**Comment by michaelld** [comment]
@ZeroChaos- Thx for your feedback. Hoping it's not too difficult to get merged.

**Comment by ZeroChaos-** [comment]
@mbr0wn I checked a few branches, felt like at random, and didn't see this committed.  If you can tell me which branch I should be testing I'm happy to test this and https://github.com/EttusResearch/uhd/issues/301 to make sure it's all good.

**Comment by michaelld** [comment]
@ZeroChaos- it's currently in a private dev repo. It'll be pushed to the public UHD repo soon-ish. It works very nicely... I think you'll be pleased!

**Comment by ZeroChaos-** [comment]
I'm sure it will be fine, I just like to close the loop and test the dev code :-) you know how to find me pre-release if you want extra verification
