### ISSUE TITLE
Device3 Getting all blocks?

### ISSUE THREAD

**Issue by mcarosino** [EttusResearch/uhd#306]
**Problem**
Have an application where I'd like to get all the block_ids (and eventually block controllers) that were found by UHD in the fpga image. Device3 has two related functions however they don't allow blindly finding all blocks without knowing what you're looking for:

1) find_blocks - Provide a hint to find matching blocks. Unfortunately you can't do something like find_blocks("") as a wildcard, because it uses block_id::match under the hood which has a check to prevent returning a match when all 3 of the match fields are empty.

2) has_block - Provide the block_id you're looking for - requires an exact match.

**Solutions**

Unless I've missed something, seems like a simple change to UHD should resolve this. Two options I see:

1) a new device3 function like list_blocks() that simply dumps out all the block_ids

OR 

2) modifying the existing find_blocks to allow wildcard matches e.g. find_blocks("*")

**Comment by mbr0wn** [comment]
`find_blocks("")` does the trick now.

**Comment by mcarosino** [comment]
@mbr0wn was there an associated git commit with this? Can't seem to find it

**Comment by mcarosino** [comment]
Scratch that - I see it's on the 3.15LTS branch. Thanks!
