### ISSUE TITLE
UHD_IMAGE_BUILDER_GUI crashes when selecting E310 RfNoC or E310 RfNoC SG3

### ISSUE THREAD

**Issue by lunar-mosiur** [EttusResearch/uhd#308]
## Issue Description ##

After cloning the repo from https://github.com/EttusResearch/fpga.git I tried to run the UHD Image Builder gui from fpga/usrp3/tools/scripts with the command: python uhd_image_builder_gui.py. When I click the options from the left column either E310 RfNoC or E310 RfNoC SG3 it crashes with the following message:

Traceback (most recent call last):
  File "uhd_image_builder_gui.py", line 422, in ootlist
    help_string = re.findall(pattern, fil.read(), re.MULTILINE)[0].replace("##","")
IndexError: list index out of range

## Setup Details ##

UHD Version: UHD_3.14.0.0-0-gf6cacec8
OS: Ubuntu 16.04 LTS x64
Target Hardware: USRP E312

## Expected Behavior ##

It will let me select RfNoC blocks for E310.

## Actual Behaviour ##

It crashes with an error message.

## Steps to reproduce the problem ##

Open terminal and run the following commands:
$git clone https://github.com/EttusResearch/fpga.git
$cd fpga/usrp3/tools/scripts/
$mv ../../top/e31x/ ../../top/e300
$python uhd_image_builder_gui.py

**Comment by mbr0wn** [comment]
Thanks for reporting. This was fixed on UHD-3.15.LTS.
