### ISSUE TITLE
x300 fw communication failure #1 EnvironmentError: IOError: x300 fw poke32 - reply timed out

### ISSUE THREAD

**Issue by mwk088** [EttusResearch/uhd#312]
## Issue Description ##
I cannot collect with my flowgraph for more than 5 minutes until I see the x300 fw poke32 error

## Setup Details ##
[INFO] UHD_3.12.0.HEAD-0-gec786351
|   |       Mboard: X310
|   |   revision: 4
|   |   product: 30410
|   |   FW Version: 6.0
|   |   FPGA Version: 35.0
|   |   FPGA git hash: 0cf76fc
|   |   RFNoC capable: Yes
  
Also seen with UHD_3.12.0.1-1-g0ffff6a2

This is only see using an X310 using a TWINRX or UBX

## Expected Behavior ##
My flowgraph to continuously run, collecting and writing data

## Actual Behaviour ##
x300 fw communication failure #1 EnvironmentError: IOError: x300 fw poke32 - reply timed out

After about 5minutes

**Comment by natetemple** [comment]
Hi @mwk088,

Please email support@ettus.com and we can debug the issue through that channel.
