### ISSUE TITLE
uboot neon_read_ethaddr() fails because of bad i2ctun sequence number

### ISSUE THREAD

**Issue by aholtzma** [EttusResearch/uhd#316]
When the changes for rev2 were made, neon_read_ethaddr() didn't have the sequence number of the i2c tunnel updated. neon_probe_mboard() *was* updated and works fine. This is only a problem if you want to use ethernet in u-boot.
```
--- a/meta-neon/recipes-bsp/u-boot/files/0001-ni-zynq-Add-support-for-NI-Project-Neon-Rev2-SDR.patch
+++ b/meta-neon/recipes-bsp/u-boot/files/0001-ni-zynq-Add-support-for-NI-Project-Neon-Rev2-SDR.patch
@@ -634,7 +634,7 @@ index 0000000000..42ed383d24
 +      int err, i;
 +      u32 crc;
 +
-+      err = uclass_get_device_by_seq(UCLASS_I2C, 20, &i2c_tun);
++      err = uclass_get_device_by_seq(UCLASS_I2C, 2, &i2c_tun);
 +      if (err < 0)
 +              return err;
 +
```

**Comment by steviez** [comment]
@aholtzma - Apologies for not following up sooner, but the fix has been applied
https://github.com/EttusResearch/meta-ettus/commits/uhd-3.15/thud
and should be reflected in our UHD v3.15.0.0 filesystems:
https://files.ettus.com/binaries/cache/e3xx/meta-ettus-v3.15.0.0/

Thanks for bringing this to our attention / providing the fix!
