### ISSUE TITLE
pybombs recipe tracks UHD-3.14, which is not python3-ready?

### ISSUE THREAD

**Issue by jkbecker** [EttusResearch/uhd#317]
## Issue Description ##
I noticed that the recipe for uhd that is published to PyBOMBS tracks the UHD-3.14 branch, which does not seem to be fully ready for a fully Python3-compatible installation.

## Setup Details ##
- Ubuntu 18.04-based clean system, python3 installed, pip3 installed
- `pip3 install --upgrade git+https://github.com/gnuradio/pybombs.git`
- basic pybombs config set up
- i.e., a fully python3-based installation (intended to be used with gnuradio 3.8)

## Expected Behavior ##
`pybombs install uhd` should install UHD using the python3 interpreter.

## Actual Behaviour ##
The UHD-3.14 branch seems to only work with python2.
I attempted to hotfix it with `-DPYTHON_EXECUTABLE=/usr/bin/python3` etc. but it would still complain about missing python2(!) modules (mako, etc) instead of using the equivalent python3 modules (which are present on the system).

## Steps to reproduce the problem ##
1. install pybombs on a Python3-based system
1. `pybombs install uhd` will fail
1. adding this to the config.yml will switch the python interpreter supposedl:
    ```
    - packages:
      uhd:
        vars:
          config_opt: " -DPYTHON_EXECUTABLE=/usr/bin/python3 -DRUNTIME_PYTHON_EXECUTABLE=/usr/bin/python3 "
    ```
4. but the install process will still fail, complaining about missing python (2) packages.

## Suggestion
Switch uhd recipe to a more current branch -- `master` worked for me but I didn't look into which is the most current stable branch with python3 support. UHD-3.14 is 260 commits behind master it seems, which feels like a lot (especially given these commits must contain a lot of python3 readiness changes?)

**Comment by mbr0wn** [comment]
@jkbecker Thanks for the report. I've set the default branch to UHD-3.15.LTS, which is almost release-ready and mostly contains bugfixes over 3.14.

FYI you need to also specify ENABLE_PYTHON3 on the 3.14 branch, which is a bit annoying and we cleaned that up on master and 3.15.

Since this is what you suggested, I will close this issue, but please re-open if you think it doesn't, or I misunderstood you.
