### ISSUE TITLE
missing boost include in max287x.hpp

### ISSUE THREAD

**Issue by guruofquality** [EttusResearch/uhd#33]
Just missing explicit #include \<boost/math/special_functions/round.hpp\> in host/lib/usrp/common/max287x.hpp It killed my CI build against master branch, log is here: https://travis-ci.org/pothosware/SoapyUHD/jobs/58334988

**Comment by bhilburn** [comment]
This work was actually done separately, and is included in the UHD-3.8.3 tag.
