### ISSUE TITLE
DPDK 19.11 is not supported.

### ISSUE THREAD

**Issue by doronbehar** [EttusResearch/uhd#333]
## Issue Description ##

DPDK 19.11 and/or 20.02 are not supported.

## Setup Details ##

At NixOS, we would like to enable dpdk support for our uhd host build and our version of dpdk is 19.11. They also have version 20.02 released but it's not considered LTS so we don't use it. See http://core.dpdk.org/download/ .

## Expected Behavior ##

DPDK 19.11 and/or 20.02 would be supported, 

## Actual Behaviour ##

I got the error message:

```
-- Could NOT find DPDK: Found unsuitable version ".", but required is exact version "17.11" (found /nix/store/khg3206h5l09k3jg22yk76s2y3xvk7hm-dpdk-19.11/include)
```

## Steps to reproduce the problem ##

Run `cmake` with `-DENABLE_DPDK=ON` and dpdk 19.11 installed.

## Additional Information ##

TBH, I'm not sure what's the purpose of these feature, I'm just a packager. I was only thinking it would be proper to open an issue here. Feel free to close it if you won't intend to support newer versions of dpdk.

**Comment by mbr0wn** [comment]
@doronbehar The different versions of DPDK are not supported, that is correct. DPDK can change drastically from version to version, so we typically lock down one supported version of DPDK per version of UHD. For master branch, that is 18.11, and for 3.15, it is 17.11.

This is very similar to how we depend on Vivado, where also only support one version per version of UHD.

Our intention is to support future versions of DPDK (eventually), but as long as the DPDK API is in such flux, we will probably not support multiple versions at once.

Many people who require DPDK often compile UHD from source, with their custom flags. I would recommend disabling DPDK (ENABLE_DPDK=OFF) for your default builds.

Thanks for flagging this, and thanks for packaging UHD. Sorry that we can't do more for you right now.
