### ISSUE TITLE
Error building PACKAGE 

### ISSUE THREAD

**Issue by MarkHHansen** [EttusResearch/uhd#342]
## Issue Description ##
I have an issue, when building the PACKAGE project in visual studio on windows. The problem seems to be in cmake_install.cmake. It says an absolute path destination is forbidden. 

## Setup Details ##
Windows 10
Visual Studio 17 v.15.9.22
UHD version: 4.0.0.0-583-g3b59529e
Libusb-1.0.23 (Path C:/Users/myuser/)
Boost_1_68:0 14.1 (Path C:/local)
Python 3.8
CMake 3.17.1

The entries for building the project in CMake are set according to the ettus guide for building windows. 
BOOST_ALL_DYN_LINK: Checked

## Expected Behavior ##
The build works as inteded. 

## Actual Behaviour ##

**When the PACKAGE project is building, the following error occurs:**
3>CPack: -   Install component: pythonapi
3>CMake Error at C:/Users/mhhn/uhd-master/uhd/host/build/python/cmake_install.cmake:42 (message):
3>  ABSOLUTE path INSTALL DESTINATION forbidden (by caller):
3>  C:/local/uhd_install/Lib/site-packages/uhd
3>Call Stack (most recent call first):
3>  C:/Users/mhhn/uhd-master/uhd/host/build/cmake_install.cmake:76 (include)
3>
3>
3>EXEC : CPack error : Error when generating package: UHD
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: The command "setlocal
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: cd C:\Users\mhhn\uhd-master\uhd\host\build
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: C:
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: "C:\Program Files\CMake\bin\cpack.exe" -C Release --config ./CPackConfig.cmake
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :cmEnd
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :cmErrorLevel
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: exit /b %1
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :cmDone
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :VCEnd" exited with code 1.
3>Done building project "PACKAGE.vcxproj" -- FAILED.

## Steps to reproduce the problem ##
The steps to reproduce this error, is just to have the same setup as shown above, and follow this guide:
https://files.ettus.com/manual/page_build_guide.html

There are two warnings when configuring in CMake, and 1 error when build the PACKAGE project. 

## Additional Information ##
CMake output:

Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18363.

Configuring the Python interpreter...
Manually determining build Python version...
Python interpreter: C:/Users/mhhn/AppData/Local/Programs/Python/Python38/python.exe Version: 3.8.2
Override with: -DPYTHON_EXECUTABLE=<path-to-python>
Manually determining runtime Python version...
Python runtime interpreter: C:/Users/mhhn/AppData/Local/Programs/Python/Python38/python.exe Version: 3.8.2
Override with: -DRUNTIME_PYTHON_EXECUTABLE=<path-to-python>
Finding Python Libraries...
Python Libraries: C:/Users/mhhn/AppData/Local/Programs/Python/Python38/libs/python38.lib
Python include directories: C:/Users/mhhn/AppData/Local/Programs/Python/Python38/include
Operating on master branch.
Using UHD Images Directory: C:\local\uhd_install\share\uhd\images

Configuring Boost C++ Libraries...

Checking for Boost version 1.58 or greater
  Looking for required Boost components...
CMake Warning at C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:1164 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:1286 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:1887 (_Boost_MISSING_DEPENDENCIES)
  cmake/Modules/UHDBoost.cmake:176 (find_package)
  CMakeLists.txt:298 (include)

CMake Warning at C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:1164 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:1286 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:1887 (_Boost_MISSING_DEPENDENCIES)
  cmake/Modules/UHDBoost.cmake:176 (find_package)
  CMakeLists.txt:298 (include)

CMake Warning at C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:1164 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:1286 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:1887 (_Boost_MISSING_DEPENDENCIES)
  cmake/Modules/UHDBoost.cmake:176 (find_package)
  CMakeLists.txt:298 (include)

CMake Warning at C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:1164 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:1286 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:1887 (_Boost_MISSING_DEPENDENCIES)
  cmake/Modules/UHDBoost.cmake:176 (find_package)
  CMakeLists.txt:298 (include)

CMake Warning at C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:1164 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:1286 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:1887 (_Boost_MISSING_DEPENDENCIES)
  cmake/Modules/UHDBoost.cmake:176 (find_package)
  CMakeLists.txt:298 (include)

CMake Warning at C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:1164 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:1286 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:1887 (_Boost_MISSING_DEPENDENCIES)
  cmake/Modules/UHDBoost.cmake:176 (find_package)
  CMakeLists.txt:298 (include)

CMake Warning at C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:1164 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:1286 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:1887 (_Boost_MISSING_DEPENDENCIES)
  cmake/Modules/UHDBoost.cmake:176 (find_package)
  CMakeLists.txt:298 (include)

CMake Warning at C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:1164 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:1286 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:1887 (_Boost_MISSING_DEPENDENCIES)
  cmake/Modules/UHDBoost.cmake:176 (find_package)
  CMakeLists.txt:298 (include)

CMake Warning at C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:1164 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:1286 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:1887 (_Boost_MISSING_DEPENDENCIES)
  cmake/Modules/UHDBoost.cmake:176 (find_package)
  CMakeLists.txt:298 (include)

  Enabling Boost Error Code Header Only
    Disabling boost::asio use of std::string_view
  Boost version: 1.73.0
  Boost include directories: C:/local/boost_1_73_0
  Boost library directories: C:/local/boost_1_73_0/lib64-msvc-14.1
  Boost libraries: optimized;C:/local/boost_1_73_0/lib64-msvc-14.1/boost_chrono-vc141-mt-x64-1_73.lib;debug;C:/local/boost_1_73_0/lib64-msvc-14.1/boost_chrono-vc141-mt-gd-x64-1_73.lib;optimized;C:/local/boost_1_73_0/lib64-msvc-14.1/boost_date_time-vc141-mt-x64-1_73.lib;debug;C:/local/boost_1_73_0/lib64-msvc-14.1/boost_date_time-vc141-mt-gd-x64-1_73.lib;optimized;C:/local/boost_1_73_0/lib64-msvc-14.1/boost_filesystem-vc141-mt-x64-1_73.lib;debug;C:/local/boost_1_73_0/lib64-msvc-14.1/boost_filesystem-vc141-mt-gd-x64-1_73.lib;optimized;C:/local/boost_1_73_0/lib64-msvc-14.1/boost_program_options-vc141-mt-x64-1_73.lib;debug;C:/local/boost_1_73_0/lib64-msvc-14.1/boost_program_options-vc141-mt-gd-x64-1_73.lib;optimized;C:/local/boost_1_73_0/lib64-msvc-14.1/boost_unit_test_framework-vc141-mt-x64-1_73.lib;debug;C:/local/boost_1_73_0/lib64-msvc-14.1/boost_unit_test_framework-vc141-mt-gd-x64-1_73.lib;optimized;C:/local/boost_1_73_0/lib64-msvc-14.1/boost_serialization-vc141-mt-x64-1_73.lib;debug;C:/local/boost_1_73_0/lib64-msvc-14.1/boost_serialization-vc141-mt-gd-x64-1_73.lib;optimized;C:/local/boost_1_73_0/lib64-msvc-14.1/boost_thread-vc141-mt-x64-1_73.lib;debug;C:/local/boost_1_73_0/lib64-msvc-14.1/boost_thread-vc141-mt-gd-x64-1_73.lib;optimized;C:/local/boost_1_73_0/lib64-msvc-14.1/boost_system-vc141-mt-x64-1_73.lib;debug;C:/local/boost_1_73_0/lib64-msvc-14.1/boost_system-vc141-mt-gd-x64-1_73.lib;optimized;C:/local/boost_1_73_0/lib64-msvc-14.1/boost_atomic-vc141-mt-x64-1_73.lib;debug;C:/local/boost_1_73_0/lib64-msvc-14.1/boost_atomic-vc141-mt-gd-x64-1_73.lib
Looking for Boost version 1.58 or greater - found

Python checking for Python version 3.5 or greater
Python checking for Python version 3.5 or greater - found

Python checking for Mako templates 0.4.2 or greater
Python checking for Mako templates 0.4.2 or greater - found

Python checking for requests 2.0 or greater
Python checking for requests 2.0 or greater - found

Python checking for numpy 1.11 or greater
Python checking for numpy 1.11 or greater - found

Python checking for ruamel.yaml 0.15 or greater
Python checking for ruamel.yaml 0.15 or greater - "import ruamel.yaml" failed

Configuring LibUHD support...
  Dependency Boost_FOUND = TRUE
  Dependency HAVE_PYTHON_MODULE_MAKO = TRUE
  Enabling LibUHD support.
  Override with -DENABLE_LIBUHD=ON/OFF

Configuring LibUHD - C API support...
  Dependency ENABLE_LIBUHD = ON
  Disabling LibUHD - C API support.
  Override with -DENABLE_C_API=ON/OFF

Configuring LibUHD - Python API support...
  Dependency ENABLE_LIBUHD = ON
  Dependency HAVE_PYTHON_MODULE_NUMPY = TRUE
  Dependency HAVE_PYTHON_LIBS = TRUE
  Enabling LibUHD - Python API support.
  Override with -DENABLE_PYTHON_API=ON/OFF

Configuring Examples support...
  Dependency ENABLE_LIBUHD = ON
  Enabling Examples support.
  Override with -DENABLE_EXAMPLES=ON/OFF

Configuring Utils support...
  Dependency ENABLE_LIBUHD = ON
  Enabling Utils support.
  Override with -DENABLE_UTILS=ON/OFF

Configuring Tests support...
  Dependency ENABLE_LIBUHD = ON
  Enabling Tests support.
  Override with -DENABLE_TESTS=ON/OFF

CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (PkgConfig)
  does not match the name of the calling package (USB1).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindPkgConfig.cmake:45 (find_package_handle_standard_args)
  cmake/Modules/FindUSB1.cmake:6 (include)
  lib/CMakeLists.txt:62 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (LIBUSB)
  does not match the name of the calling package (USB1).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/Modules/FindUSB1.cmake:61 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  lib/CMakeLists.txt:62 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
Could NOT find LIBERIO (missing: LIBERIO_LIBRARY LIBERIO_INCLUDE_DIR) 
Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
Could NOT find DPDK (missing: DPDK_INCLUDE_DIRS DPDK_LIBRARIES) (Required is exact version "18.11")

Configuring LIBERIO support...
  Dependency ENABLE_LIBUHD = ON
  Dependency LIBERIO_FOUND = FALSE
  Disabling LIBERIO support.
  Override with -DENABLE_LIBERIO=ON/OFF

Configuring USB support...
  Dependency ENABLE_LIBUHD = ON
  Dependency LIBUSB_FOUND = TRUE
  Enabling USB support.
  Override with -DENABLE_USB=ON/OFF

Configuring B100 support...
  Dependency ENABLE_LIBUHD = ON
  Dependency ENABLE_USB = ON
  Enabling B100 support.
  Override with -DENABLE_B100=ON/OFF

Configuring B200 support...
  Dependency ENABLE_LIBUHD = ON
  Dependency ENABLE_USB = ON
  Enabling B200 support.
  Override with -DENABLE_B200=ON/OFF

Configuring USRP1 support...
  Dependency ENABLE_LIBUHD = ON
  Dependency ENABLE_USB = ON
  Enabling USRP1 support.
  Override with -DENABLE_USRP1=ON/OFF

Configuring USRP2 support...
  Dependency ENABLE_LIBUHD = ON
  Enabling USRP2 support.
  Override with -DENABLE_USRP2=ON/OFF

Configuring X300 support...
  Dependency ENABLE_LIBUHD = ON
  Enabling X300 support.
  Override with -DENABLE_X300=ON/OFF

Configuring MPMD support...
  Dependency ENABLE_LIBUHD = ON
  Enabling MPMD support.
  Override with -DENABLE_MPMD=ON/OFF

Configuring N300 support...
  Dependency ENABLE_LIBUHD = ON
  Dependency ENABLE_MPMD = ON
  Enabling N300 support.
  Override with -DENABLE_N300=ON/OFF

Configuring N320 support...
  Dependency ENABLE_LIBUHD = ON
  Dependency ENABLE_MPMD = ON
  Enabling N320 support.
  Override with -DENABLE_N320=ON/OFF

Configuring E320 support...
  Dependency ENABLE_LIBUHD = ON
  Dependency ENABLE_MPMD = ON
  Enabling E320 support.
  Override with -DENABLE_E320=ON/OFF

Configuring E300 support...
  Dependency ENABLE_LIBUHD = ON
  Dependency ENABLE_MPMD = ON
  Enabling E300 support.
  Override with -DENABLE_E300=ON/OFF

Configuring OctoClock support...
  Dependency ENABLE_LIBUHD = ON
  Enabling OctoClock support.
  Override with -DENABLE_OCTOCLOCK=ON/OFF

Configuring DPDK support...
  Dependency ENABLE_MPMD = ON
  Dependency DPDK_FOUND = FALSE
  Disabling DPDK support.
  Override with -DENABLE_DPDK=ON/OFF

Configuring priority scheduling...
  Priority scheduling supported through windows SetThreadPriority.
  Setting thread names is not supported.
  Setting thread affinity is supported through windows SetThreadAffinityMask.

Configuring module loading...
  Module loading supported through LoadLibrary.

Processing NI-RIO FPGA LVBITX Bitstreams...
  Using x300.lvbitx_base for codegen
  Using x310.lvbitx_base for codegen

USB support enabled via libusb.

Configuring interface address discovery...
  Interface address discovery supported through SIO_GET_INTERFACE_LIST.

Loading build info.
Could NOT find Curses (missing: CURSES_LIBRARY CURSES_INCLUDE_PATH) 

Adding B2XX device test target
Adding X3x0 device test target
Adding E3XX device test target
Adding N3XX device test target
Adding E32x device test target

Could NOT find Curses (missing: CURSES_LIBRARY CURSES_INCLUDE_PATH) 
Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 

Configuring Manual support...
  Dependency DOXYGEN_FOUND = NO
  Disabling Manual support.
  Override with -DENABLE_MANUAL=ON/OFF

Configuring API/Doxygen support...
  Dependency DOXYGEN_FOUND = NO
  Disabling API/Doxygen support.
  Override with -DENABLE_DOXYGEN=ON/OFF

Compressed Man Pages disabled
  Override with -DENABLE_MAN_PAGE_COMPRESSION=ON/OFF

Configuring Man Pages support...
  Dependency NOT_WIN32 = 
  Disabling Man Pages support.
  Override with -DENABLE_MAN_PAGES=ON/OFF

Python checking for virtualenv
Python checking for virtualenv - "assert hasattr(sys, 'real_prefix')" failed
Utilizing the python install directory: C:/local/uhd_install/Lib/site-packages

######################################################
# UHD enabled components                              
######################################################
  * LibUHD
  * LibUHD - Python API
  * Examples
  * Utils
  * Tests
  * USB
  * B100
  * B200
  * USRP1
  * USRP2
  * X300
  * MPMD
  * N300
  * N320
  * E320
  * E300
  * OctoClock

######################################################
# UHD disabled components                             
######################################################
  * LibUHD - C API
  * LIBERIO
  * DPDK
  * Manual
  * API/Doxygen
  * Man Pages

******************************************************
* You are building the UHD development master branch.
* For production code, we recommend our stable,
* releases or using the release branch (maint).
******************************************************
Building version: 4.0.0.0-583-g3b59529e
Using install prefix: C:/local/uhd_install
Configuring done
Generating done

**Comment by atrnati** [comment]
Hi, thanks for reporting this issue. I believe this has been addressed since your report by commit c68977cf. If you're in a position to give it a try, please let us know if that solves your issue. Thanks again!

**Comment by michael-west** [comment]
@MarkHHansen We are closing this as resolved.  Please re-open if it is still an issue for you.
