### ISSUE TITLE
uhd_images_downloader.py not work with http proxy (solution found)

### ISSUE THREAD

**Issue by warmonkey** [EttusResearch/uhd#343]
## Issue Description ##
uhd_images_downloader.py not work with http proxy. when env variable HTTP_PROXY specified, or arguments --http-proxy specified, it keeps downloading without proxy (we don't have direct access to files.ettus.com here, so download always failed). just like no proxy is provided.

## Setup Details ##
sudo /usr/lib/uhd/utils/uhd_images_downloader.py --http-proxy http://localhost:8080

## Expected Behavior ##
the script download files over http proxy specified by user. should be fast.

## Actual Behaviour ##
files.ettus.com returned HTTP code 301, indicate that user should change to https.
After that, the script tries to download files with *DIRECT* https connection, not over proxy. 
no difference with simple `sudo /usr/lib/uhd/utils/uhd_images_downloader.py `

## Steps to reproduce the problem ##
add a line below setting _PROXIES (line 161)
before:
`line 161        _PROXIES['http'] = args.http_proxy`
after
`        _PROXIES['http'] = args.http_proxy`
`        _PROXIES['https'] = args.http_proxy`

## Additional Information ##
most http proxy supports general TCP connection (so work with https definitely). Just tell python.requests that for https we use same proxy as http.

**Comment by mbr0wn** [comment]
Thanks for the great report and suggestion. We'll fix this on master soon.
