### ISSUE TITLE
rebuild latest packages against recent libboost

### ISSUE THREAD

**Issue by zabbal** [EttusResearch/uhd#36]
The latest .deb release packages in http://files.ettus.com/binaries/uhd/latest_release/ is built against boost 1.54 although all the releases after latest LTS uses version 1.55

It would make working with latest uhd releases on ubuntu much easier if the appropriate version of boost would be used. People sticking to LTS version are more likely to choose http://files.ettus.com/binaries/uhd/latest_stable/ so this change would not affect them. This would also makes transition to next LTS release faster and easier because corresponding changes would be already tested during intermediate releases.

Even better, of course, would be to see ppa with packages for currently available ubuntu versions. This would solve the problem once and for all - and it would make installation instructions over http://code.ettus.com/redmine/ettus/projects/uhd/wiki/UHD_Linux 10 times shorter: one command to add ppa, another to install uhd. That's it.

**Comment by mbr0wn** [comment]
Hey @zabbal, latest_stable and latest_release are identical; we only keep both for historical reasons. Also, we only build installers for the two latest LTS versions.
