### ISSUE TITLE
OS X Build Instructions Tip

### ISSUE THREAD

**Issue by niftylettuce** [EttusResearch/uhd#37]
Hello,

I had installed some things with `brew` and some with `pip`, therefore I had to modify my install on OS X as follows:

```bash
CC=/usr/bin/llvm-gcc CXX=/usr/bin/llvm-g++ cmake -DPYTHON_EXECUTABLE=/usr/local/opt/python/bin/python2.7 -DPYTHON_INCLUDE_DIR=/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/Headers -DPYTHON_LIBRARY=/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/Python ../host
```

Please make a note in the Redmine Wiki somewhere that tells the user explicitly that they need to ensure their paths are correct for these environment variables (especially if they installed a dependency with `brew`).

This would have saved me some time having this reminder to myself in there &ndash; I'm sure it'll save others' time too.

Thank you,

**Comment by mbr0wn** [comment]
Hey @niftylettuce, thanks for the feedback. I'll converse with our Mac OS X guy, and as we're moving this infos to the manual, I'll update it there.

**Comment by niftylettuce** [comment]
thanks
