### ISSUE TITLE
set_rx_rate()  takes 300ms-500ms. 

### ISSUE THREAD

**Issue by commthu** [EttusResearch/uhd#371]
My application require switch sample rate very often,  However set_rx_rate() takes 300ms-500ms time.
How can i reduce this overhead.

**Comment by michaelld** [comment]
which USRP are you using here?

**Comment by commthu** [comment]
B210 mini

**Comment by michaelld** [comment]
That's useful information. Some other useful information would include your host computer make/model, and the USB connection (for example "lsusb" if you're on Linux).

This is not an issue with UHD, per se, so I'm going to close this out.

I encourage you to sign up and use the USRP-users email discussion list < https://lists.ettus.com/mailman/listinfo/usrp-users_lists.ettus.com >. You can try sending an email to "support@ettus.com", but they are overwhelmed & so you're much more likely to get a reply from USRP-users.
