### ISSUE TITLE
[ERROR] [B200] Got a ctrl packet with unknown SID

### ISSUE THREAD

**Issue by chandersVT** [EttusResearch/uhd#373]
I saw this error reported on a previous version of UHD, but it appears to still persist in 3.15.0.

OS: Ubuntu 18.04.4 LTS
Kernel: 5.3.0-62-generic  (happens on lowlatency kernel as well)
UHD: 3.15.0.HEAD-0-gaea0e2de
SRS LTE 20.04.1 (EPC + eNB on one host)

## Issue Description ##

Error:
eNB producing "[ERROR] [B200] Got a ctrl packet with unknown SID x" with mostly the same SID's.  This causes the eNB to crash and I have to power cycle the USRP.

## Setup Details ##
As specified above.  This happens with both the Generic and Lowlatency kernel.  I'm using a Core i5 Intel NUC min-pc.  It is resource-intensive, but appears to run with plenty of memory and processor time to spare.

According to https://github.com/EttusResearch/uhd/issues/222  this was an issue in a buffer somewhere and was theoretically corrected in UHD 3.15.  But I still seem to be seeing it.

## Additional Information ##
I'm just running the baseline LTE configuration supplied as default with SRS LTE.  10 MHz bandwidth, single TX/RX.  Of note, it also happens with the 5 MHz bandwidth.  I can run the various UHD test/benchmark routines at the sample rate used by SRSLTE (23.04 MHz) with no issues.

**Comment by atrnati** [comment]
Would you be in a position to try reproducing this issue with UHD 4.0.0?

**Comment by chandersVT** [comment]
Aaron,

Yes, I believe so.

Also, I played around with the device arguments and found that using  
"send_frame_size=256" seems to stabilize it.  Or at least it hasn't 
crashed during the limited testing I've done so far (I've let it run for 
up to an hour or so).

I'll try building UHD 4.0 later this week and see what happens.

Chris

**Comment by michael-west** [comment]
@chandersVT The fact that a smaller send_frame_size succeeds seems to suggest that bulk transfers may not be working properly.  Using a maximum frame size of 512 for USB2 or 1024 for USB3 will avoid using bulk transfers.

We did update the FX3 firmware in UHD 4.0, which may or may not help.  There are a lot of moving parts including UHD, libusb, the USB controller, FX3 firmware, and FPGA image so it is difficult to say where the issue may reside.

**Comment by michael-west** [comment]
Redirecting this to Support for reproduction and validation.

**Comment by mbr0wn** [comment]
This looks like a 3.15 issue which we can't reproduce.
