### ISSUE TITLE
uhd version 4.0 make fails 

### ISSUE THREAD

**Issue by ilayni** [EttusResearch/uhd#377]
## Issue Description ##
g dependencies of target uhd
[  3%] Building CXX object lib/CMakeFiles/uhd.dir/cal/database.cpp.o
/home/gig/uhd/host/lib/cal/database.cpp:200:2: error: converting to ‘std::tuple<uhd::usrp::cal::source, bool (*)(const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&), std::vector<unsigned char, std::allocator<unsigned char> > (*)(const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)>’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {uhd::usrp::cal::source, bool (*)(const std::__cxx11::basic_string<char, std::char_traits<char>, std::alloc

## Setup Details ##

GNU C++ version 5.4.0 20160609; Boost_105800; ubuntu 16.04

## Expected Behavior ##
successful build
## Steps to reproduce the problem ##

make with this setup

**Comment by michael-west** [comment]
Fixed with 72c7084e4bf7001aa29cd78dfa6a90c5629155fc
