### ISSUE TITLE
UHD_RX_STREAM

### ISSUE THREAD

**Issue by dshukla19** [EttusResearch/uhd#384]
I am running my code on B210 and N210. On B210 i am able to read more than 30000 samples in single recv call from uhd. 
But on N210 it's not the same. So i just wanted to know how much data i can read in single recv call from UHD. in B210 and N210.
Thanks.

**Comment by michaelld** [comment]
Hi @dshukla19  - your question is a very good one for the [USRP users list](https://lists.ettus.com/mailman/listinfo/usrp-users_lists.ettus.com). These GitHub issues are meant to be related to UHD bugs to be fixed. This venue is not meant to be for customer support for queries on how to use UHD.

That said, here's a snippet of code that you might find useful:
```
    auto maxRxSamps = rxStream->get_max_num_samps();
```
with info found [here](https://files.ettus.com/manual/classuhd_1_1rx__streamer.html). Good luck with your UHD / USRP work!
