### ISSUE TITLE
N310:  ERROR_CODE_BAD_PACKET seen when using DMAFIFO in UHD4.0.0.0

### ISSUE THREAD

**Issue by dmitryshidlovsky** [EttusResearch/uhd#389]
## Issue Description ##
I'd like to capture 1 250 000 samples in 125 MHz sample rate, and I'm using DMAFIFO for that. I have my own fpga part, but the issue can be reproduced with default bit file with DMAFIFO (using usrp_n310_fpga_AA.bit) and with my uhd program (rx_multi_samples.cpp with some modification to use DMAFIFO). 
 

## Setup Details ##
UHD\FPGA master (4.0.0.0), N310

## Expected Behavior ##
capturing of 1 250 000 samples at sample rate 125 MHz through DMAFIFO

## Actual Behaviour ##
[ERROR] [STREAMER] The receive transport caught a value exception.
ValueError: Bad CHDR header or invalid packet length.
Error: Receiver error: ERROR_CODE_BAD_PACKET

## Steps to reproduce the problem ##
with default 4.0.0.0 sdi  (command: uhd_images_downloader -t n3xx_common_sdimg_default)
load bit file with DMAFIFO: 
uhd_image_loader --args type=n3xx --fpga-path /usr/share/uhd/images/usrp_n310_fpga_AA.bit
run capture program, I use modified version of rfnoc_rx_to_file (see Additional Information)
./rfnoc_rx_to_file --rate=125000000 --nsamps=1250000

## Additional Information ##

//
// Copyright 2011 Ettus Research LLC
// Copyright 2018 Ettus Research, a National Instruments Company
//
// SPDX-License-Identifier: GPL-3.0-or-later
//

#include <uhd/usrp/multi_usrp.hpp>
#include <uhd/utils/safe_main.hpp>
#include <uhd/utils/thread.hpp>
#include <boost/algorithm/string.hpp>
#include <boost/format.hpp>
#include <boost/program_options.hpp>
#include <chrono>
#include <complex>
#include <iostream>
#include <thread>
#include <fstream>
#include <uhd/rfnoc/ddc_block_control.hpp>
//#include <uhd/rfnoc/radarxcorr_control.hpp>
#include <uhd/rfnoc/dmafifo_block_control.hpp>
#include <uhd/rfnoc/defaults.hpp>
#include <uhd/rfnoc/mb_controller.hpp>
#include <uhd/rfnoc/radio_control.hpp>
#include <uhd/rfnoc_graph.hpp>

namespace po = boost::program_options;

int UHD_SAFE_MAIN(int argc, char* argv[])
{
    // variables to be set by po
    std::string args, sync, subdev, channel_list;
    double seconds_in_future;
    size_t total_num_samps, shift;
    double rate, freq, gain, s;

    // setup the program options
    po::options_description desc("Allowed options");
    // clang-format off
    desc.add_options()
        ("help", "help message")
        ("args", po::value<std::string>(&args)->default_value(""), "single uhd device address args")
        ("secs", po::value<double>(&seconds_in_future)->default_value(1.5), "number of seconds in the future to receive")
        ("nsamps", po::value<size_t>(&total_num_samps)->default_value(10000), "total number of samples to receive")
        ("rate", po::value<double>(&rate)->default_value(100e6/16), "rate of incoming samples")
        ("freq", po::value<double>(&freq)->default_value(0.0), "RF center frequency in Hz")
        ("gain", po::value<double>(&gain), "gain for the RF chain")        
        ("sync", po::value<std::string>(&sync)->default_value("now"), "synchronization method: now, pps, mimo")
        ("subdev", po::value<std::string>(&subdev), "subdev spec (homogeneous across motherboards)")
        ("shift", po::value<size_t>(&shift)->default_value(0), "shift")        
        ("dilv", "specify to disable inner-loop verbose")
        ("channels", po::value<std::string>(&channel_list)->default_value("0"), "which channel(s) to use (specify \"0\", \"1\", \"0,1\", etc)")
        ("s", po::value<double>(&s)->default_value(0), "silence mode")
    ;
    // clang-format on
    po::variables_map vm;
    po::store(po::parse_command_line(argc, argv, desc), vm);
    po::notify(vm);

    // print the help message
    if (vm.count("help")) {
        std::cout << boost::format("UHD RX Multi Samples %s") % desc << std::endl;
        std::cout
            << "    This is a demonstration of how to receive aligned data from multiple "
               "channels.\n"
               "    This example can receive from multiple DSPs, multiple motherboards, "
               "or both.\n"
               "    The MIMO cable or PPS can be used to synchronize the configuration. "
               "See --sync\n"
               "\n"
               "    Specify --subdev to select multiple channels per motherboard.\n"
               "      Ex: --subdev=\"0:A 0:B\" to get 2 channels on a Basic RX.\n"
               "\n"
               "    Specify --args to select multiple motherboards in a configuration.\n"
               "      Ex: --args=\"addr0=192.168.10.2, addr1=192.168.10.3\"\n"
            << std::endl;
        return ~0;
    }

    bool verbose = vm.count("dilv") == 0;

    std::cout << std::endl;
    std::cout << boost::format("Creating the RFNoC graph with args: %s...") % args
              << std::endl;
    uhd::rfnoc::rfnoc_graph::sptr graph = uhd::rfnoc::rfnoc_graph::make(args);

    // Create handle for radio object
    uhd::rfnoc::block_id_t radio_ctrl_id1(0, "Radio", 0);
    // This next line will fail if the radio is not actually available
    uhd::rfnoc::radio_control::sptr radio_ctrl1 =
        graph->get_block<uhd::rfnoc::radio_control>(radio_ctrl_id1);
    std::cout << "Using radio " << 0 << ", channel " << 0 << std::endl;
    
    // Create handle for radio object
    uhd::rfnoc::block_id_t radio_ctrl_id2(0, "Radio", 1);
    // This next line will fail if the radio is not actually available
    uhd::rfnoc::radio_control::sptr radio_ctrl2 =
        graph->get_block<uhd::rfnoc::radio_control>(radio_ctrl_id2);
    std::cout << "Using radio " << 1 << ", channel " << 0 << std::endl;    
    
    /*uhd::rfnoc::block_id_t xcorr_ctrl_id(0, "RADARXCORR", 0);
    uhd::rfnoc::radarxcorr_control::sptr radarxcorr_ctrl =
        graph->get_block<uhd::rfnoc::radarxcorr_control>(xcorr_ctrl_id); */

    uhd::rfnoc::block_id_t dmafifo_ctrl_id(0, "DmaFIFO", 0);
    uhd::rfnoc::dmafifo_block_control::sptr dmafifo_ctrl =
        graph->get_block<uhd::rfnoc::dmafifo_block_control>(dmafifo_ctrl_id); 
        
    //std::cout << dmafifo_ctrl->get_packet_count(0) << std::endl;
    //uhd::rfnoc::dmafifo_block_control::_fifo_cores.back();
    
    size_t spp = 2044; //360
    
    /*std::cout << "Setting samples per packet to: " << spp << std::endl;
    radio_ctrl2->set_property<int>("spp", spp, 0);
    radio_ctrl1->set_property<int>("spp", spp, 0);
    radio_ctrl2->set_property<int>("spp", spp, 1);
    radio_ctrl1->set_property<int>("spp", spp, 1);  
    

    std::cout << "Actual samples per packet = " << radio_ctrl1->get_property<int>("spp", 0) << std::endl;
    std::cout << "Actual samples per packet = " << radio_ctrl1->get_property<int>("spp", 1) << std::endl;
    std::cout << "Actual samples per packet = " << radio_ctrl2->get_property<int>("spp", 0) << std::endl;
    std::cout << "Actual samples per packet = " << radio_ctrl2->get_property<int>("spp", 1) << std::endl;*/

    /************************************************************************
     * Set up radio
     ***********************************************************************/

    // set the sample rate
    if (rate <= 0.0) {
        std::cerr << "Please specify a valid sample rate" << std::endl;
        return EXIT_FAILURE;
    }
    std::cout << boost::format("Setting RX Rate: %f Msps...") % (rate / 1e6) << std::endl;
    double radio_rate = radio_ctrl1->get_rate();

    rate = radio_ctrl1->set_rate(rate);

    std::cout << boost::format("Actual RX Rate: %f Msps...") % (rate / 1e6) << std::endl
              << std::endl;
              
              
    std::cout << boost::format("Setting RX Rate: %f Msps...") % (rate / 1e6) << std::endl;
    radio_rate = radio_ctrl2->get_rate();

    rate = radio_ctrl2->set_rate(rate);
    
    std::cout << boost::format("Actual RX Rate: %f Msps...") % (rate / 1e6) << std::endl
              << std::endl;              

    // set the center frequency

        std::cout << boost::format("Setting RX Freq: %f MHz...") % (freq / 1e6)
                  << std::endl;
        uhd::tune_request_t tune_request(freq);

        radio_ctrl1->set_rx_frequency(freq,0);
        radio_ctrl1->set_rx_frequency(freq,1);
        std::cout << boost::format("Actual RX Freq: %f MHz...")
                         % (radio_ctrl1->get_rx_frequency(0) / 1e6)
                  << std::endl
                  << std::endl;

    // set the rf gain

        std::cout << boost::format("Setting RX Gain: %f dB...") % gain << std::endl;
        radio_ctrl1->set_rx_gain(gain,0);
        radio_ctrl1->set_rx_gain(gain,1);
        std::cout << boost::format("Actual RX Gain: %f dB...")
                         % radio_ctrl1->get_rx_gain(0)
                  << std::endl
                  << std::endl;

    
     // set the center frequency

        std::cout << boost::format("Setting RX Freq: %f MHz...") % (freq / 1e6)
                  << std::endl;

        radio_ctrl2->set_rx_frequency(freq,0);
        radio_ctrl2->set_rx_frequency(freq,1);
        std::cout << boost::format("Actual RX Freq: %f MHz...")
                         % (radio_ctrl2->get_rx_frequency(0) / 1e6)
                  << std::endl
                  << std::endl;

    // set the rf gain

        std::cout << boost::format("Setting RX Gain: %f dB...") % gain << std::endl;
        radio_ctrl2->set_rx_gain(gain,0);
        radio_ctrl2->set_rx_gain(gain,1);
        std::cout << boost::format("Actual RX Gain: %f dB...")
                         % radio_ctrl2->get_rx_gain(0)
                  << std::endl
                  << std::endl;
 
    

    /************************************************************************
     * Set up streaming
     ***********************************************************************/
     
    // detect which channels to use
    std::vector<std::string> channel_strings;
    std::vector<size_t> channel_nums;
    boost::split(channel_strings, channel_list, boost::is_any_of("\"',"));
    for (size_t ch = 0; ch < channel_strings.size(); ch++) {
        size_t chan = std::stoi(channel_strings[ch]);
            channel_nums.push_back(std::stoi(channel_strings[ch]));
    }
     
    // create a receive streamer

    uhd::device_addr_t streamer_args("");

    // create a receive streamer

    uhd::stream_args_t stream_args("sc16", "sc16"); // We should read the wire format from the blocks
    stream_args.channels             = channel_nums;
    //stream_args.args = streamer_args;
    stream_args.args = streamer_args;
    // TODO?
    stream_args.args["spp"] = boost::lexical_cast<std::string>(spp);
    /*stream_args.channels = {0, 1, 2, 3};
    stream_args.args["block_id0"] = "0/Radio_0";
    stream_args.args["block_id1"] = "0/Radio_0";
    stream_args.args["block_id2"] = "0/Radio_1";
    stream_args.args["block_id3"] = "0/Radio_1"; 
    stream_args.args["block_port0"] = "0";
    stream_args.args["block_port1"] = "1";
    stream_args.args["block_port2"] = "0";
    stream_args.args["block_port3"] = "1";*/
    
    std::cout << "Using streamer args: " << stream_args.args.to_string() << std::endl;
    uhd::rx_streamer::sptr rx_stream = graph->create_rx_streamer(1, stream_args);
    
    std::cout << "Num channels: " << rx_stream->get_num_channels() << std::endl;

    /*graph->connect(radio_ctrl1->get_block_id(),0,radarxcorr_ctrl->get_block_id(),0);
    graph->connect(radarxcorr_ctrl->get_block_id(),0,dmafifo_ctrl->get_block_id(),0);
    graph->connect(dmafifo_ctrl->get_block_id(),0,rx_stream, 0);
    
    graph->connect(radio_ctrl1->get_block_id(),1,radarxcorr_ctrl->get_block_id(),1);
    graph->connect(radarxcorr_ctrl->get_block_id(),1,dmafifo_ctrl->get_block_id(),1);
    graph->connect(dmafifo_ctrl->get_block_id(),1,rx_stream, 1);   
    
    graph->connect(radio_ctrl2->get_block_id(),0,radarxcorr_ctrl->get_block_id(),2);
    graph->connect(radarxcorr_ctrl->get_block_id(),2,dmafifo_ctrl->get_block_id(),2);
    graph->connect(dmafifo_ctrl->get_block_id(),2,rx_stream, 2);
    
    graph->connect(radio_ctrl2->get_block_id(),1,radarxcorr_ctrl->get_block_id(),3);
    graph->connect(radarxcorr_ctrl->get_block_id(),3,dmafifo_ctrl->get_block_id(),3);
    graph->connect(dmafifo_ctrl->get_block_id(),3,rx_stream, 3);   */     
    
    graph->connect(radio_ctrl1->get_block_id(),0,dmafifo_ctrl->get_block_id(),0);
    graph->connect(dmafifo_ctrl->get_block_id(),0,rx_stream, 0);  
    
    /*graph->connect(radio_ctrl1->get_block_id(),1,dmafifo_ctrl->get_block_id(),1);
    graph->connect(dmafifo_ctrl->get_block_id(),1,rx_stream, 1);    */

    // Connect blocks and commit the graph
    /*for (auto& edge : chain1) {
    	std::cout << edge.src_blockid << std::endl;

        if (uhd::rfnoc::block_id_t(edge.dst_blockid).match(uhd::rfnoc::NODE_ID_SEP)) {
            graph->connect(edge.src_blockid, edge.src_port, rx_stream, 0);
            //std::cout << edge.src_blockid << std::endl;
        } else {
            graph->connect(
                edge.src_blockid, edge.src_port, edge.dst_blockid, edge.dst_port);
        }
    }
    for (auto& edge : chain2) {
    	std::cout << edge.src_blockid << std::endl;

        if (uhd::rfnoc::block_id_t(edge.dst_blockid).match(uhd::rfnoc::NODE_ID_SEP)) {
            graph->connect(edge.src_blockid, edge.src_port, rx_stream, 1);
            //std::cout << edge.src_blockid << std::endl;
        } else {
            graph->connect(
                edge.src_blockid, edge.src_port, edge.dst_blockid, edge.dst_port);
        }
    }
    for (auto& edge : chain3) {
    	std::cout << edge.src_blockid << std::endl;

        if (uhd::rfnoc::block_id_t(edge.dst_blockid).match(uhd::rfnoc::NODE_ID_SEP)) {
            graph->connect(edge.src_blockid, edge.src_port, rx_stream, 2); //2
            //std::cout << edge.src_blockid << std::endl;
        } else {
            graph->connect(
                edge.src_blockid, edge.src_port, edge.dst_blockid, edge.dst_port);
        }
    }
    for (auto& edge : chain4) {
    	std::cout << edge.src_blockid << std::endl;

        if (uhd::rfnoc::block_id_t(edge.dst_blockid).match(uhd::rfnoc::NODE_ID_SEP)) {
            graph->connect(edge.src_blockid, edge.src_port, rx_stream, 3);
            //std::cout << edge.src_blockid << std::endl;
        } else {
            graph->connect(
                edge.src_blockid, edge.src_port, edge.dst_blockid, edge.dst_port);
        }
    }    */       
    graph->commit();

    std::cout << boost::format("Setting device timestamp to 0...") << std::endl;
    if (sync == "now") {
        // This is not a true time lock, the devices will be off by a few RTT.
        // Rather, this is just to allow for demonstration of the code below.
        //graph->get_mb_controller(0)->get_timekeeper(0)->set_time_now(uhd::time_spec_t(0.0));
	graph->get_mb_controller(0)->get_timekeeper(0)->set_time_next_pps(uhd::time_spec_t(0.0));
	//graph->synchronize_devices(uhd::time_spec_t(0.0),false);
	//graph->get_mb_controller(0)->get_timekeeper()->set_time_next_pps(uhd::time_spec_t(0.0));
	std::this_thread::sleep_for(std::chrono::milliseconds(1000));
    } else if (sync == "pps") {
        /*radio_ctrl->set_time_source("external");
        radio_ctrl->set_time_unknown_pps(uhd::time_spec_t(0.0));
        std::this_thread::sleep_for(std::chrono::seconds(1)); // wait for pps sync pulse*/
    } else if (sync == "mimo") {
        /*UHD_ASSERT_THROW(usrp->get_num_mboards() == 2);

        // make mboard 1 a slave over the MIMO Cable
        usrp->set_clock_source("mimo", 1);
        usrp->set_time_source("mimo", 1);

        // set time on the master (mboard 0)
        usrp->set_time_now(uhd::time_spec_t(0.0), 0);

        // sleep a bit while the slave locks its time to the master
        std::this_thread::sleep_for(std::chrono::milliseconds(100));*/
    }

    // setup streaming
    std::cout << std::endl;
    std::cout << boost::format("Begin streaming %u samples, %f seconds in the future...")
                     % total_num_samps % seconds_in_future
              << std::endl;
    uhd::stream_cmd_t stream_cmd(uhd::stream_cmd_t::STREAM_MODE_NUM_SAMPS_AND_DONE);
    stream_cmd.num_samps  = total_num_samps;
    stream_cmd.stream_now = false;
    stream_cmd.time_spec  = uhd::time_spec_t(seconds_in_future);
    rx_stream->issue_stream_cmd(stream_cmd); // tells all channels to stream
    
    std::ofstream outfile;
    if (!s)
    	outfile.open("usrp_samples.dat", std::ofstream::binary);

    // meta-data will be filled in by recv()
    uhd::rx_metadata_t md;

    // allocate buffers to receive with samples (one buffer per channel)
    size_t samps_per_buff = rx_stream->get_max_num_samps();

    std::vector<std::vector<std::complex<short>>> buffs(
        rx_stream->get_num_channels(), std::vector<std::complex<short>>(samps_per_buff));

    // create a vector of pointers to point to each of the channel buffers
    std::vector<std::complex<short>*> buff_ptrs;
    for (size_t i = 0; i < buffs.size(); i++)
        buff_ptrs.push_back(&buffs[i].front());

    // the first call to recv() will block this many seconds before receiving
    double timeout = seconds_in_future + 1; // timeout (delay before receive + padding)

    size_t num_acc_samps = 0; // number of accumulated samples
    while (num_acc_samps < total_num_samps) {
        // receive a single packet
        size_t num_rx_samps = rx_stream->recv(buff_ptrs, samps_per_buff, md, timeout);

        // use a small timeout for subsequent packets
        timeout = 0.1;

        // handle the error code
       if (md.error_code == uhd::rx_metadata_t::ERROR_CODE_TIMEOUT)
            break;
//        if (md.error_code != uhd::rx_metadata_t::ERROR_CODE_NONE) {
//            throw std::runtime_error(
//                str(boost::format("Receiver error %s") % md.strerror()));
//        }

        if (verbose)
            std::cout << boost::format(
                             "Received packet: %u samples, %u full secs, %f frac secs")
                             % num_rx_samps % md.time_spec.get_full_secs()
                             % md.time_spec.get_frac_secs()
                      << std::endl;

        num_acc_samps += num_rx_samps;
        
        std::cout << "num_rx_samps:" << num_rx_samps << std::endl;
        
        if (!s) {
        
        if (outfile.is_open()) {
        	for (size_t i = 0; i < buffs.size(); i++) {
        	
        			//std::cout << "i:" << i << std::endl;
            			outfile.write((const char*)&buffs[i].front(), num_rx_samps * 2 *sizeof(short));
            		}
        }
        
        }
    }

    if (num_acc_samps < total_num_samps)
        std::cerr << "Receive timeout before all samples received..." << std::endl;

    // finished
    std::cout << std::endl << "Done!" << std::endl << std::endl;

    return EXIT_SUCCESS;
}

**Comment by michael-west** [comment]
@dmitryshidlovsky Thanks for reporting!  Please provide the following additional information:

1.  Is this being run from the local host on the N310 or a remote host?
2.  What spp sizes have you tried?  I see 2044 with 360 commented on the side.  Did the same error occur with the 360 value?

This could be an issue with the transport and not necessarily the DMA FIFO block, so I have changed the title.  The error indicates corrupted or lost data in a packet.  I suspect some type of buffer issue.  If the smaller spp size works, then it is likely the frames created with the larger spp are too large.  If both sizes fail, it is more likely to be an issue with buffering in the transport.  In that case, you could try experimenting with different values for the `recv_buff_size`, `recv_frame_size`, and `num_recv_frames` device arguments.

In UHD 4.0.0.0, the default images (other than the AA image) now contain the Replay block.  I would encourage you to move to using the Replay block as it has proven to be more reliable and versatile than the DMA FIFO.  You could try using the HG image and modifying the code to use the Replay block instead of the DMA FIFO.  All that is needed in the code is to directly replace the DMA FIFO with the Replay block and then just add calls to record() and play() on the Replay block.

**Comment by dmitryshidlovsky** [comment]
@michael-west Thank you for the answer!
Regarding additional information:
1. It run from local host (on N310).
2. With spp=360 and less it works for a little total number of samples (ERROR_CODE_BAD_PACKET isn't seen), but with total number of samples more then 8000 overflow happens, and I lost some samples.

Thank you for directing me to Replay block! I think it will help me.

**Comment by michael-west** [comment]
@dmitryshidlovsky The overflow is likely due to the occasional latency seen during DRAM refreshing.  The way to mitigate that is to make sure the DMA FIFO is on a separate endpoint and use a large ingress buffer on the endpoint.  You will need to do that when using the Replay block as well.

Since reducing the spp to 360 resolves the original issue of the ERROR_CODE_BAD_PACKET, I am closing this issue.  Thank you!
