### ISSUE TITLE
CMake errot :The source directory "/home/...." does not appear to contain CMakeLists.txt.

### ISSUE THREAD

**Issue by Csysongyi** [EttusResearch/uhd#391]
Hello,
when I installing the uhd on my Ubuntu 18.04 system, I met a problem,  I fellow the steps on the web page:

https://kb.ettus.com/Building_and_Installing_the_USRP_Open-Source_Toolchain_(UHD_and_GNU_Radio)_on_Linux

mkdir build
 cd build
 cmake ../

when I use  "cmake ../ ", an error happened:

CMake errot :The source directory "/home/...." does not appear to contain CMakeLists.txt.

And I found that there doesn't have the CMakeLists.txt file in my uhd folder
how can I  solve this problem 
thanks in advanced.

**Comment by michaelld** [comment]
Here are the instructions:
```
Next, create a build folder within the repository, invoke CMake and build UHD.

   cd host
   mkdir build
   cd build
   cmake ../
```

Did you do `cd host` part before the `mkdir build` part? That's critical to successfully building UHD from source!

**Comment by michaelld** [comment]
FYI this issue is better off served by either [the USRP email](https://lists.ettus.com/mailman/listinfo/usrp-users_lists.ettus.com) list or [support@ettus.com](mailto:support@ettus.com). UHD builds fine from source, so this is not an 'issue' per se -- which is really what these GitHub issues are about. Hence I'm closing this.

**Comment by Csysongyi** [comment]
Thank you very much, I worked it out under your help, and I will join the mailing list of UHD, thanks for your recommendation.







best wishes!

Songyi.Cao





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EttusResearch/uhd"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月19日(星期一) 晚上8:56
收件人:&nbsp;"EttusResearch/uhd"<uhd@noreply.github.com&gt;;
抄送:&nbsp;"Songyi Cao"<2053234590@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [EttusResearch/uhd] CMake errot :The source directory "/home/...." does not appear to contain CMakeLists.txt. (#391)





 
Here are the instructions:
 Next, create a build folder within the repository, invoke CMake and build UHD.    cd host    mkdir build    cd build    cmake ../  
Did you do cd host part before the mkdir build part? That's critical to successfully building UHD from source!
