### ISSUE TITLE
Install UHD on BeagleBone (Debian 10)

### ISSUE THREAD

**Issue by Hepan02** [EttusResearch/uhd#393]
# Issue Description ##
I have problem with installing UHD on BeagleBone, with Debian 10. I am following instruction due to:
https://files.ettus.com/manual/page_build_guide.html

First problem was with NEON, the problem is described here:
https://stackoverflow.com/questions/64765975/error-during-installation-uhd-on-beaglebone-debian-10
But I solved the problem with edit file CMakeCache.txt located in uhd/host/build/.
//Use NEON SIMD instuctions, if applicable
NEON_SIMD_ENABLE:BOOL=**OFF**

Now the problem is after using **make** command.

## Setup Details ##
**cat /proc/cpuinfo**

processor       : 0
model name      : ARMv7 Processor rev 2 (v7l)
BogoMIPS        : 995.32
Features        : half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpd32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x3
CPU part        : 0xc08
CPU revision    : 2

Hardware        : Generic AM33XX (Flattened Device Tree)
Revision        : 0000
Serial          : 4219BBBK05E9

**lsb_release -a**
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

## Expected Behavior ##
I expect to finish installation process.
 
## Actual Behaviour ##
root@beaglebone:~/uhd/host/build# make
[  2%] Built target uhd_rpclib
[  2%] Built target uhd-resources
[  3%] Building CXX object lib/CMakeFiles/uhd.dir/rfnoc/graph.cpp.o
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [lib/CMakeFiles/uhd.dir/build.make:736: lib/CMakeFiles/uhd.dir/rfnoc/graph.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:129: lib/CMakeFiles/uhd.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

## Steps to reproduce the problem ##
git clone https://github.com/EttusResearch/uhd.git
cd <uhd-repo-path>/host
mkdir build
cd build
(CHANGE CMakeCache.txt as described below)
cmake ../
make

## Additional Information ##
I don't know why:
root@beaglebone:~/uhd/host/build# pybombs install uhd
PyBOMBS.ConfigManager - INFO - Prefix Python version is: 3.7.3
PyBOMBS - INFO - PyBOMBS Version 2.3.3
PyBOMBS.install_manager - INFO - Phase 1: Creating install tree and installing binary packages:
PyBOMBS.install_manager - INFO - No packages to install.

Second problem is with compiling init_usrp:
root@beaglebone:~/uhd/host/examples/init_usrp/build# cmake ..
-- The CXX compiler identification is GNU 8.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:26 (find_package):
  Could not find a configuration file for package "UHD" that is compatible
  with requested version "4.0.0".

  The following configuration files were considered but not accepted:

    /usr/lib/arm-linux-gnueabihf/cmake/uhd/UHDConfig.cmake, version: 3.13.1.0-3

-- Configuring incomplete, errors occurred!

**Comment by mbr0wn** [comment]
@Hepan02 The first issue is here:

```
root@beaglebone:~/uhd/host/build# make
[ 2%] Built target uhd_rpclib
[ 2%] Built target uhd-resources
[ 3%] Building CXX object lib/CMakeFiles/uhd.dir/rfnoc/graph.cpp.o
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [lib/CMakeFiles/uhd.dir/build.make:736: lib/CMakeFiles/uhd.dir/rfnoc/graph.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:129: lib/CMakeFiles/uhd.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

The build of UHD is not succeeding. It is not recommended to build UHD natively on the device, please find a way to cross-compile UHD for the BeagleBone.

Next, there's this:
``` 
root@beaglebone:~/uhd/host/build# pybombs install uhd
PyBOMBS.ConfigManager - INFO - Prefix Python version is: 3.7.3
PyBOMBS - INFO - PyBOMBS Version 2.3.3
PyBOMBS.install_manager - INFO - Phase 1: Creating install tree and installing binary packages:
PyBOMBS.install_manager - INFO - No packages to install.
```

Thanks for trying PyBOMBS! From the log output, it seems like you already have a version of UHD installed. Most likely via the package manager, Debian does ship a version of UHD.

Finally, there's this:
```
Second problem is with compiling init_usrp:
root@beaglebone:~/uhd/host/examples/init_usrp/build# cmake ..
-- The CXX compiler identification is GNU 8.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:26 (find_package):
Could not find a configuration file for package "UHD" that is compatible
with requested version "4.0.0".

The following configuration files were considered but not accepted:

/usr/lib/arm-linux-gnueabihf/cmake/uhd/UHDConfig.cmake, version: 3.13.1.0-3

-- Configuring incomplete, errors occurred!
```

This confirms that you have a binary version of UHD already installed (3.13.1.0). The `-3` part tells me it indeed is a version of UHD that you installed via apt-get. There's nothing wrong with that -- but you are trying to compile `init_usrp` from the UHD 4.0 branch, which doesn't like the 3.13 version of UHD.

You have some options:
- Keep the 3.13 version, if that is sufficient for your applications, and compile against that.
- Remove the 3.13 version and install your desired version from source.
  - You should cross-compile it off-device, and then copy over.
