### ISSUE TITLE
uhd_image_loader displays incorrect FPGA type when fpga-path is manually specified

### ISSUE THREAD

**Issue by dkozel** [EttusResearch/uhd#395]
## Issue Description ##
The `uhd_image_loader` utility sometimes prints the wrong FPGA type when used with the X3xx.

## Setup Details ##
UHD_4.0.0.0-25-g1a34ba8a  
USRP X310

## Expected Behavior ##
The image loader utility should display the correct FPGA build (XG/HG/etc) or *not* display the type if it cannot derive it.

## Actual Behaviour ##
The image loader displays the `fpga_type` read from the currently running FPGA on the USRP.

## Steps to reproduce the problem ##

> 
> [dkozel (gr39) x300] (UHD-4.0) uhd_image_loader --args type=x300 --fpga-path=/home/dkozel/prefixes/gr39/share/uhd/images/usrp_x310_fpga_XG.bit
> [INFO] [UHD] linux; Clang version 10.0.1 ; Boost_107100; UHD_4.0.0.0-25-g1a34ba8a
> Unit: USRP X310 (F4717A, 192.168.40.2)
> FPGA Image: /home/dkozel/prefixes/gr39/share/uhd/images/usrp_x310_fpga_**XG**.bit
> -- Initializing FPGA loading...successful.
> -- Loading **HG** FPGA image: 100% (121/121 sectors)
> -- Finalizing image load...successful.
> Power-cycle the USRP X310 to use the new image.
> 

The error message is printed at:

https://github.com/EttusResearch/uhd/blob/1a34ba8a953ff4edeb4c196e087ab15e7b9e48fe/host/lib/usrp/x300/x300_image_loader.cpp#L327-L330

The value is read at:

https://github.com/EttusResearch/uhd/blob/1a34ba8a953ff4edeb4c196e087ab15e7b9e48fe/host/lib/usrp/x300/x300_image_loader.cpp#L226

A fix would be to set the `fpga_type` in the else case:

https://github.com/EttusResearch/uhd/blob/1a34ba8a953ff4edeb4c196e087ab15e7b9e48fe/host/lib/usrp/x300/x300_image_loader.cpp#L239-L240

**Comment by mbr0wn** [comment]
We have a fix in the pipeline.
