### ISSUE TITLE
Incorrect tx incrementors in benchmark_tx_rate_async_helper

### ISSUE THREAD

**Issue by emoges** [EttusResearch/uhd#402]
https://github.com/EttusResearch/uhd/blob/master/host/examples/python/benchmark_rate.py

shouldn't the benchmark_tx_rate_async_helper function read 
...     
            elif ((async_metadata.event_code == uhd.types.TXMetadataEventCode.underflow) or
                  (async_metadata.event_code == uhd.types.TXMetadataEventCode.underflow_in_packet)):
                **num_tx_underrun += 1**
            elif ((async_metadata.event_code == uhd.types.TXMetadataEventCode.seq_error) or
                  (async_metadata.event_code == uhd.types.TXMetadataEventCode.seq_error_in_packet)):
                **num_tx_seqerr += 1**
...
instead of 
...     
            elif ((async_metadata.event_code == uhd.types.TXMetadataEventCode.underflow) or
                  (async_metadata.event_code == uhd.types.TXMetadataEventCode.underflow_in_packet)):
                **num_tx_seqerr += 1**
            elif ((async_metadata.event_code == uhd.types.TXMetadataEventCode.seq_error) or
                  (async_metadata.event_code == uhd.types.TXMetadataEventCode.seq_error_in_packet)):
                **num_tx_underrun += 1**
...

**Comment by mbr0wn** [comment]
Yes, you are correct. Thanks for the report!
