### ISSUE TITLE
Being able to call get_max_num_samps() before get_rx_stream()

### ISSUE THREAD

**Issue by hazevt04** [EttusResearch/uhd#404]
## Issue Description ##
This is, I think, a minor usability improvement. I think it would be nice if I did not have to have an rx_streamer in order to call get_max_num_samps().

## Setup Details ##
I am using the UHD C++ API (no GNU Radio, no Python). For example, if I wanted to use two channels for receiving complex float samples, one rx_streamer per channel and later use the rx_streamers in separate threads, I would do:
```C++
std::vector<size_t> channel_nums;
std::vector<uhd::rx_streamer::sptr> rx_streams;
std::vector<std::vector<std::complex>> buffs;
std::vector<void*> buff_ptrs;

// channel_nums is a std::vector where each channel number is from the command line

size_t num_rx_channels = channel_nums.size();
size_t max_samples_per_packet = 0;

buffs.resize(num_rx_channels);

// cpu_format = fc32, over-the-wire format = sc16
uhd::stream_args_t stream_args("fc32", "sc16");

for ( size_t channel_index = 0; channel_index != num_rx_channels; ++channel_index ) {
         // Each RX streamer has one channel
         stream_args.channels  = {channel_nums.at(channel_index)};

         rx_streams.push_back( usrp->get_rx_stream(stream_args) );
         
         // Except for the channels, the stream args are the same for all rx_streamers.
         // I only need to do this once. The only way to get max number of samples is via an rx_streamer
         if ( channel_index == 0 ) {
                  max_samples_per_packet = rx_streams[0]->get_max_num_samps();
         }

         buffs[channel_index].resize(max_samples_per_packet);
         buff_ptrs.push_back(&(buffs[channel_index].front())); 
}
```

## Expected Behavior ##
It would be nice to have a function that could use the ```C++ uhd::usrp::multi_usrp::sptr usrp``` pointer and it would probably need the 'cpu_format' string( "fc32", for example) :
```C++
// The result probably depends on the MTU between the host and the USRP SDR and the 'cpu_format' for the samples
// Example: MTU = 8000 bytes, cpu_format = 'fc32', 8 bytes per sample. 
// The result might be 996 packets max (instead of 1000) due to packet overhead
size_t max_samples_per_packet = usrp->get_rx_max_num_samps("fc32");
```

## Actual Behaviour ##
I have to have an rx_streamer to call get_max_num_samps().

**Comment by mbr0wn** [comment]
@hazevt04 I agree this is a minor improvement, but there is a lot of logic that goes into figuring out the max packet size. It is very much tied to the streamers. For most applications, streamers are required anyway, so it's (most of the times) not a burden.

Implementing this would be a lot of work, and we would rather spend that elsewhere.

Thanks for the suggestion! We are always glad to see how people use UHD.
