### ISSUE TITLE
PPA is missing an entry for Ubuntu Groovy 20.10

### ISSUE THREAD

**Issue by nllz** [EttusResearch/uhd#407]
## Issue Description ##
The Ettus Research PPA [0] is missing an entry for Ubuntu Groovy 20.10

[0] https://launchpad.net/~ettusresearch/+ppa-packages

## Expected Behavior ##
Add PPA via add-apt-repostiory

## Actual Behaviour ##
E: The repository 'http://ppa.launchpad.net/ettusresearch/uhd/ubuntu groovy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

## Steps to reproduce the problem ##
$ sudo add-apt-repository ppa:ettusresearch/uhd     on a Ubuntu 20.10 system

**Comment by mbr0wn** [comment]
Yeah this has gotten a bit old...
