### ISSUE TITLE
It doesn't look like `_ctx` is ever used in `libusb_zero_copy`

### ISSUE THREAD

**Issue by johnwstanford** [EttusResearch/uhd#408]
I was looking at `libusb_zero_copy` and noticed that `_ctx` is never used.  I think these libusb calls use the default context, which is why it works, but if this is the case, maybe this member should be removed from the class?

https://github.com/EttusResearch/uhd/blob/3b9ced8f07c068faf1f494ce170cb44edaa47075/host/lib/transport/libusb1_zero_copy.cpp#L197

**Comment by mbr0wn** [comment]
It looks like you're right.
