### ISSUE TITLE
Python checking for virtualenv - "assert hasattr(sys, 'real_prefix')" failed

### ISSUE THREAD

**Issue by jingxianwang** [EttusResearch/uhd#412]
## Issue Description ##
Compiling UHD from Source on OSX

## Setup Details ##
I run cmake ../host

Output:
- Python checking for virtualenv
-- Python checking for virtualenv - "assert hasattr(sys, 'real_prefix')" failed
-- 
-- Python checking for gevent 1.4.0 or greater
-- Python checking for gevent 1.4.0 or greater - found
-- 
-- Python checking for mprpc
-- Python checking for mprpc - "import mprpc" failed
-- 
-- Python checking for pyudev 0.21.0 or greater
-- Python checking for pyudev 0.21.0 or greater - found
-- 
-- Python checking for pyroute2
-- Python checking for pyroute2 - "import pyroute2" failed
-- MPM unit test Python package prerequisites not met; skipping

######### cmake error.log
Performing C++ SOURCE FILE Test HAVE_WIN_SETTHREADPRIORITY failed with the following output:
Change Dir: /Users/jx/Documents/uhd/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_e2fcb/fast"
/Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/cmTC_e2fcb.dir/build.make CMakeFiles/cmTC_e2fcb.dir/build
Building CXX object CMakeFiles/cmTC_e2fcb.dir/src.cxx.o
/Library/Developer/CommandLineTools/usr/bin/clang++   -I/opt/local/include/libusb-1.0  -fvisibility=hidden -fvisibility-inlines-hidden -DHAVE_WIN_SETTHREADPRIORITY -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk   -std=gnu++14 -o CMakeFiles/cmTC_e2fcb.dir/src.cxx.o -c /Users/jx/Documents/uhd/build/CMakeFiles/CMakeTmp/src.cxx
/Users/jx/Documents/uhd/build/CMakeFiles/CMakeTmp/src.cxx:2:14: fatal error: 'windows.h' file not found
    #include <windows.h>
             ^~~~~~~~~~~
1 error generated.
make[1]: *** [CMakeFiles/cmTC_e2fcb.dir/src.cxx.o] Error 1
make: *** [cmTC_e2fcb/fast] Error 2

Source file was:

    #include <windows.h>
    int main(){
        SetThreadPriority(GetCurrentThread(), 0);
        SetPriorityClass(GetCurrentProcess(), 0);
        return 0;
    }
    
Performing C++ SOURCE FILE Test HAVE_PTHREAD_SETNAME failed with the following output:
Change Dir: /Users/jx/Documents/uhd/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_6a34c/fast"
/Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/cmTC_6a34c.dir/build.make CMakeFiles/cmTC_6a34c.dir/build
Building CXX object CMakeFiles/cmTC_6a34c.dir/src.cxx.o
/Library/Developer/CommandLineTools/usr/bin/clang++   -I/opt/local/include/libusb-1.0  -fvisibility=hidden -fvisibility-inlines-hidden -DHAVE_PTHREAD_SETNAME -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk   -std=gnu++14 -o CMakeFiles/cmTC_6a34c.dir/src.cxx.o -c /Users/jx/Documents/uhd/build/CMakeFiles/CMakeTmp/src.cxx
/Users/jx/Documents/uhd/build/CMakeFiles/CMakeTmp/src.cxx:6:9: error: no matching function for call to 'pthread_setname_np'
        pthread_setname_np(pt, pt_name);
        ^~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/pthread.h:513:5: note: candidate function not viable: requires 1 argument, but 2 were provided
int     pthread_setname_np(const char*);
        ^
1 error generated.
make[1]: *** [CMakeFiles/cmTC_6a34c.dir/src.cxx.o] Error 1
make: *** [cmTC_6a34c/fast] Error 2

Source file was:

    #include <pthread.h>
    int main(){
        pthread_t pt;
        const char* pt_name = "test";
        pthread_setname_np(pt, pt_name);
        return 0;
    }
    
Performing C++ SOURCE FILE Test HAVE_PTHREAD_SETAFFINITY_NP failed with the following output:
Change Dir: /Users/jx/Documents/uhd/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_850da/fast"
/Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/cmTC_850da.dir/build.make CMakeFiles/cmTC_850da.dir/build
Building CXX object CMakeFiles/cmTC_850da.dir/src.cxx.o
/Library/Developer/CommandLineTools/usr/bin/clang++   -I/opt/local/include/libusb-1.0  -fvisibility=hidden -fvisibility-inlines-hidden -DHAVE_PTHREAD_SETAFFINITY_NP -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk   -std=gnu++14 -o CMakeFiles/cmTC_850da.dir/src.cxx.o -c /Users/jx/Documents/uhd/build/CMakeFiles/CMakeTmp/src.cxx
/Users/jx/Documents/uhd/build/CMakeFiles/CMakeTmp/src.cxx:5:9: error: unknown type name 'cpu_set_t'
        cpu_set_t cs;
        ^
/Users/jx/Documents/uhd/build/CMakeFiles/CMakeTmp/src.cxx:6:43: error: use of undeclared identifier 'cpu_set_t'
        pthread_setaffinity_np(pt, sizeof(cpu_set_t), &cs);
                                          ^
2 errors generated.
make[1]: *** [CMakeFiles/cmTC_850da.dir/src.cxx.o] Error 1
make: *** [cmTC_850da/fast] Error 2

Source file was:

    #include <pthread.h>
    int main(){
        pthread_t pt;
        cpu_set_t cs;
        pthread_setaffinity_np(pt, sizeof(cpu_set_t), &cs);
        return 0;
    }
    
Performing C++ SOURCE FILE Test HAVE_WIN_SETTHREADAFFINITYMASK failed with the following output:
Change Dir: /Users/jx/Documents/uhd/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_fb4dd/fast"
/Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/cmTC_fb4dd.dir/build.make CMakeFiles/cmTC_fb4dd.dir/build
Building CXX object CMakeFiles/cmTC_fb4dd.dir/src.cxx.o
/Library/Developer/CommandLineTools/usr/bin/clang++   -I/opt/local/include/libusb-1.0  -fvisibility=hidden -fvisibility-inlines-hidden -DHAVE_WIN_SETTHREADAFFINITYMASK -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk   -std=gnu++14 -o CMakeFiles/cmTC_fb4dd.dir/src.cxx.o -c /Users/jx/Documents/uhd/build/CMakeFiles/CMakeTmp/src.cxx
/Users/jx/Documents/uhd/build/CMakeFiles/CMakeTmp/src.cxx:2:14: fatal error: 'windows.h' file not found
    #include <windows.h>
             ^~~~~~~~~~~
1 error generated.
make[1]: *** [CMakeFiles/cmTC_fb4dd.dir/src.cxx.o] Error 1
make: *** [cmTC_fb4dd/fast] Error 2

Source file was:

    #include <windows.h>
    int main(){
        SetThreadAffinityMask(GetCurrentThread(), 0);
        return 0;
    }
    
Performing C++ SOURCE FILE Test HAVE_LOAD_LIBRARY failed with the following output:
Change Dir: /Users/jx/Documents/uhd/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_fc8d7/fast"
/Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/cmTC_fc8d7.dir/build.make CMakeFiles/cmTC_fc8d7.dir/build
Building CXX object CMakeFiles/cmTC_fc8d7.dir/src.cxx.o
/Library/Developer/CommandLineTools/usr/bin/clang++   -I/opt/local/include/libusb-1.0  -fvisibility=hidden -fvisibility-inlines-hidden -DHAVE_LOAD_LIBRARY -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk   -std=gnu++14 -o CMakeFiles/cmTC_fc8d7.dir/src.cxx.o -c /Users/jx/Documents/uhd/build/CMakeFiles/CMakeTmp/src.cxx
/Users/jx/Documents/uhd/build/CMakeFiles/CMakeTmp/src.cxx:3:14: fatal error: 'windows.h' file not found
    #include <windows.h>
             ^~~~~~~~~~~
1 error generated.
make[1]: *** [CMakeFiles/cmTC_fc8d7.dir/src.cxx.o] Error 1
make: *** [cmTC_fc8d7/fast] Error 2

Source file was:

    #define WIN32_LEAN_AND_MEAN
    #include <windows.h>
    int main(){
        LoadLibrary(0);
        return 0;
    }
    
Determining if the include file winsock2.h exists failed with the following output:
Change Dir: /Users/jx/Documents/uhd/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_06747/fast"
/Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/cmTC_06747.dir/build.make CMakeFiles/cmTC_06747.dir/build
Building CXX object CMakeFiles/cmTC_06747.dir/CheckIncludeFile.cxx.o
/Library/Developer/CommandLineTools/usr/bin/clang++   -I/opt/local/include/libusb-1.0  -fvisibility=hidden -fvisibility-inlines-hidden  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk   -std=gnu++14 -o CMakeFiles/cmTC_06747.dir/CheckIncludeFile.cxx.o -c /Users/jx/Documents/uhd/build/CMakeFiles/CMakeTmp/CheckIncludeFile.cxx
/Users/jx/Documents/uhd/build/CMakeFiles/CMakeTmp/CheckIncludeFile.cxx:1:10: fatal error: 'winsock2.h' file not found
#include <winsock2.h>
         ^~~~~~~~~~~~
1 error generated.
make[1]: *** [CMakeFiles/cmTC_06747.dir/CheckIncludeFile.cxx.o] Error 1
make: *** [cmTC_06747/fast] Error 2

Determining if the include file atlbase.h exists failed with the following output:
Change Dir: /Users/jx/Documents/uhd/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_a27df/fast"
/Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/cmTC_a27df.dir/build.make CMakeFiles/cmTC_a27df.dir/build
Building CXX object CMakeFiles/cmTC_a27df.dir/CheckIncludeFile.cxx.o
/Library/Developer/CommandLineTools/usr/bin/clang++   -I/opt/local/include/libusb-1.0  -fvisibility=hidden -fvisibility-inlines-hidden  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk   -std=gnu++14 -o CMakeFiles/cmTC_a27df.dir/CheckIncludeFile.cxx.o -c /Users/jx/Documents/uhd/build/CMakeFiles/CMakeTmp/CheckIncludeFile.cxx
/Users/jx/Documents/uhd/build/CMakeFiles/CMakeTmp/CheckIncludeFile.cxx:1:10: fatal error: 'atlbase.h' file not found
#include <atlbase.h>
         ^~~~~~~~~~~
1 error generated.
make[1]: *** [CMakeFiles/cmTC_a27df.dir/CheckIncludeFile.cxx.o] Error 1
make: *** [cmTC_a27df/fast] Error 2

**Comment by michaelld** [comment]
UHD _can_ configure on OSX from 10.4/5 (PPC 32/64 && Intel 32/64) to current (Intel64 / ARM64), with the correct dependencies installed. Hence I'm closing this issue.

Please send an email to support@ettus.com with your issue & status. Please include some more information, so that I can help you better:

* Version of MacOS & Xcode ... for example run this script `echo "macOS $(sw_vers -productVersion) $(sw_vers -buildVersion)"; echo "Xcode $(xcodebuild -version)"`

* Version of UHD you're trying to build and how: from source? inside MacPorts? current GIT master or some specific branch or tag?

* The full configure / CMake info output / debug log.

NOTE: It is normal on OSX for `virtualenv` to fail. Here's what I see from within MacPorts
```
:info:configure -- Python checking for virtualenv
:info:configure -- Python checking for virtualenv - "assert hasattr(sys, 'real_prefix')" failed
```
This failure does not impact whether UHD can build or not; it just changes how UHD does some internal CMake things.

**Comment by michaelld** [comment]
Related: Here's what the [DPDK folks note on their main webpage
](https://www.dpdk.org/)
```
Designed to run on x86, POWER and ARM processors, it runs mostly in Linux userland, with a FreeBSD port available for a subset of DPDK features.
```
To the best of my knowledge, DPDK doesn't build or work on MacOS / OSX of any version. In theory it _might_ be portable since they have a FreeBSD port, and Darwin / OSX is a variant on *BSD ... I really don't know! My strong advice is to not even try DPDK on macOS at this time _unless this is the end-goal of your work_ ; for casual UHD users just trying to get UHD running, just use MacPorts unless you can't for some reason.

**Comment by jingxianwang** [comment]
Thank you so much Michael, that's helpful. I have a followup question: I was able to use UHD properly via MacPorts Installation. I have a dumb question, how to compile and build my own cpp application? I was able to do that on linux by adding it in cmakelist.txt and make. I am not sure how to do it on Mac when I use MacPorts Installation.

**Comment by michaelld** [comment]
@jingxianwang Look in the source code directory `host/examples` and look at those individual examples for the `CMakeLists.txt` that can be used for out-of-tree builds ... roughly. Should be roughly the same as on any other OS, since CMake is so cross-platform portable.

**Comment by jingxianwang** [comment]
The problem is it's not clear where the CMakeLists.txt is after the MacPorts installation. I can only find Unix executable files in the folder of /usr/local/lib/uhd/examples.
