### ISSUE TITLE
Installation of UHD doesnt copy all headers

### ISSUE THREAD

**Issue by Rokta** [EttusResearch/uhd#419]
## Issue Description ##

After building UHD from source and installing it not all headers are copied to include folder. My installation missed this header: "uhd/host/include/uhd/rfnoc/replay_block_control.hpp". I didnt check for any other headers.

## Setup Details ##

linux; GNU C++ version 8.3.1 20191121 (Red Hat 8.3.1-5); Boost_106600; UHD_4.0.0.HEAD-0-g90ce6062

## Expected Behavior ##

I expected that all headers are copied to include folder. 

## Actual Behaviour ##

Some headers are missing from include folder.

## Steps to reproduce the problem ##

Building UHD from source and installing it.

**Comment by mbr0wn** [comment]
Fixed by aa9e950dcf4f83c106f17512fc58158f746f0777
