### ISSUE TITLE
Receiving a signal at the USRP B200mini

### ISSUE THREAD

**Issue by evzubkov** [EttusResearch/uhd#427]
## Issue Description ##

I am trying to make a B200mini based receiver. For this I use the usrp.recv_num_samps function. I use a signal generator for testing. After recording the radio signal, I receive not a complete signal, but only a part of it (less than 200 samples).

![Снимок экрана от 2021-04-07 17-29-02](https://user-images.githubusercontent.com/24616049/113852810-25006100-97c7-11eb-86a6-93f83e2f4a8b.png)

Code:
<pre>
def get_signal(usrp, num_smpl, freq_carrier, freq_smpl):
    """RX samples and write to file"""
    samps = usrp.recv_num_samps(
        num_smpl, # Number of samples
        freq_carrier, # Frequency in Hz
        freq_smpl, # Sampling rate
        [0], # Receive on channel 0
        0 # dB of RX gain
    )
    return samps

usrp = uhd.usrp.MultiUSRP("type=b200")
num_smpl = 2**10
freq_carrier = 1000e6
freq_smpl = 56e6
signal = get_signal(usrp, num_smpl, freq_carrier, freq_smpl)
</pre>

## Setup Details ##

GNU C++ version 9.3.0; Boost_107100; UHD_4.0.0.HEAD-0-g4c8ba577

**Comment by michaelld** [comment]
I strongly doubt that what you're experiencing is an actual UHD bug or issue. Please send an email to "support@ettus.com" with your query; or, even better, to the [USRP users email list](https://lists.ettus.com/list/usrp-users.lists.ettus.com).
