### ISSUE TITLE
n3xx: `XQ` FPGA image is not allowed when setting `time_source=sfp0`

### ISSUE THREAD

**Issue by faku99** [EttusResearch/uhd#434]
## Issue Description ##

For n3xx devices, the `XQ` FPGA image is not included as a candidate for WhiteRabbit protocol on the SFP+ 0 interface, although it should be.

## Setup Details ##

* **UHD Version**: 4.0.0.0 90ce6062b6b5df2eddeee723777be85108e4e7c7

## Expected Behavior ##

As stated from [this table](https://files.ettus.com/manual/page_usrp_n3xx.html#n3xx_rh_sfp_protocols), the WhiteRabbit protocol on the SFP+ 0 interface is available for the `WX` and `XQ` FPGA images.

## Actual Behaviour ##

When `time_source=sfp0`, the n3xx periph manager throws the error: `sfp0 time source requires FPGA types ('WX',)`.

## Steps to reproduce the problem ##

Program any n3xx device with the `XQ` version of the FPGA image, call `rx_to_file_multi_calib` with `args="time_source=sfp0"`.

## Additional information ##

This issue was already reported and acknowledged in December 2019 by one of your engineer: http://ettus.80997.x6.nabble.com/USRP-users-N320-XQ-image-issue-using-sfp0-as-time-source-td13973.html but no fix has been implemented.

**Comment by mbr0wn** [comment]
Fix incoming.
