### ISSUE TITLE
Missing std::abs for argument to std::min(freq, 2)

### ISSUE THREAD

**Issue by StefanBruens** [EttusResearch/uhd#438]
https://github.com/EttusResearch/uhd/blob/0813efb9a116d73300f6690b223295cf10a2f723/host/lib/usrp/usrp2/usrp2_impl.cpp#L920-L921

Obviously, new_freq can be either positive or negative, and `zone` can be an arbitrary negative value when `new_freq` is negative.

**Comment by ZeroChaos-** [comment]
bump

**Comment by mbr0wn** [comment]
Fix is public.
