### ISSUE TITLE
Able to import uhd, but unable to run any methods

### ISSUE THREAD

**Issue by Danistheman26** [EttusResearch/uhd#452]
## Issue Description ##
I am able to import the python uhd module, however the module has no contents.

## Setup Details ##
OS: Windows 10
installer: uhd_4.0.0.0-release_Winx64_VS2019
I have VS2019 and 2017 installed on this computer as well.
I just followed the steps from https://files.ettus.com/manual/page_install.html for the windows install.
I also have my PYTHONPATH pointing to C:\Program Files\UHD\lib

## Expected Behavior ##
open cmd window as admin and run "python3"
> > > import uhd
> > > usrp = uhd.usrp.MultiUSRP("type=b200")
'no error messages'

## Actual Behaviour ##
> > > import uhd
> > > help(uhd)
Help on package uhd:

NAME
    uhd

PACKAGE CONTENTS

FILE
    (built-in)

> > > usrp = uhd.usrp.MultiUSRP("type=b200")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'uhd' has no attribute 'usrp'

## Steps to reproduce the problem ##
install following steps from: https://files.ettus.com/manual/page_install.html for the windows install.
install: uhd_4.0.0.0-release_Winx64_VS2019
Then set PYTHONPATH to wherever UHD was installed to.
Then from command line (as admin) run 'python3'
and in the interactive shell run:
> > > import uhd
> > > usrp = uhd.usrp.MultiUSRP("type=b200")

## Additional Information ##
I have python 2.7 on my system as well, but am not sure if this is the issue as I am running from python3's shell.
I find it strange that I am able to import uhd, but the library itself is empty after importing
I am not the most experienced with python in general, and have only installed libraries using pip up until this point so let me know if there is anything else I am missing to run this library!

Thanks!
-Dan

**Comment by manderseck** [comment]
@Danistheman26 Sorry for the delayed response. I agree that it is strange that you are able to import uhd without any error. Apart from this the lack of methods makes sense as the Python API is not included in the UHD installer. Please follow the [manual for compiling UHD on Windows](https://kb.ettus.com/Building_and_Installing_the_USRP_Open_Source_Toolchain_(UHD_and_GNU_Radio)_on_Windows) and pay attention to include the [Python API](http://kb.ettus.com/UHD_Python_API). Afterwards you might still stumble upon the "No module named 'uhd'" issue. To resolve this please check the [Python API instructions](https://files.ettus.com/manual/page_python.html).
I'm closing this issue now. Please feel free to re-open if you feel that any aspects of your issue are not covered.
