### ISSUE TITLE
rfnoc_image_builder fails if Vivado is installed to a custom installation path.

### ISSUE THREAD

**Issue by TSlivede** [EttusResearch/uhd#455]
## Issue Description ##

If Vivado is installed to a non default path, `rfnoc_image_builder` always fails with
```
- Vivado: Version 2019.1 not found in /opt/Xilinx/Vivado (ERROR.. Builds and simulations will not work)
          Use the --vivado-path option to override the search path
```
even if I previously successfully sourced `. setupenv.sh --vivado-path /opt/Xilinx_WebPack/Vivado/`.

## Setup Details ##

UHD version is current UHD-4.0  (b061af4fcf62b2bb640636cea7170003f6a2777d)

## Expected Behavior ##

I would expect, that rfnoc_image_builder respects the environment, that was set previosly via `setupenv.sh`.

## Actual Behaviour ##

 `rfnoc_image_builder` seems to always execute `setupenv.sh` and ignores previously specified vivado-path

## Steps to reproduce the problem ##

Just install Vivado to a directory that is not [`/tools/Xilinx/Vivado_Lab`,`/tools/Xilinx/Vivado`,`/opt/Xilinx/Vivado_Lab` or `/opt/Xilinx/Vivado`](https://github.com/EttusResearch/uhd/blob/master/fpga/usrp3/tools/scripts/setupenv_base.sh#L21---L27) and rfnoc_image_builder from uhd4.0 won't find it.

## Additional Information ##

As a hack/workaround(/solution?) I replaced
```
export VIVADO_PATH=$VIVADO_BASE_PATH/$VIVADO_VER
```
in [fpga/usrp3/tools/scripts/setupenv_base.sh](https://github.com/EttusResearch/uhd/blob/master/fpga/usrp3/tools/scripts/setupenv_base.sh#L170) with
```
if [[ -d "$VIVADO_PATH" ]] && [[ "$(basename "$VIVADO_PATH")" == "$VIVADO_VER" ]]; then
    echo "Reusing previosly set VIVADO_PATH=$VIVADO_PATH"
    VIVADO_BASE_PATH="$(dirname "$VIVADO_PATH")"
    export VIVADO_PATH
else
    export VIVADO_PATH=$VIVADO_BASE_PATH/$VIVADO_VER
fi
```
such that setupenv.sh will respect a previously set vivado-path it the version is correct.

Now I can run `. setupenv.sh --vivado-path /opt/Xilinx_WebPack/Vivado/` and afterwards `rfnoc_image_builder` works.

**Comment by wordimont** [comment]
@TSlivede Thank you for pointing out this problem! I've submitted a pull request adding a --vivado-path argument to rfnoc_image_builder that works the same as the argument on setupenv.sh so that you can specify a non-default Vivado path in cases like this.
