### ISSUE TITLE
xil_bitfile_parser.py is not python3 compatible

### ISSUE THREAD

**Issue by TSlivede** [EttusResearch/uhd#467]
## Issue Description ##

When calling [`probe_bitfile`](https://files.ettus.com/manual/md_usrp3_vivado_env_utils.html) (which internally uses [`xil_bitfile_parser.py`](https://github.com/EttusResearch/uhd/blob/master/fpga/usrp3/tools/scripts/xil_bitfile_parser.py) an error is printed.

## Setup Details ##

`python3 --version` -> `Python 3.8.10`    
`xil_bitfile_parser.py` -> tested UHD-4.0 and verison from current master

## Expected Behavior ##

Calling `probe_bitfile /usr/share/uhd/images/usrp_n310_fpga_HG.bit` or    
`$REPO_BASE_PATH/tools/scripts/xil_bitfile_parser.py --info /usr/share/uhd/images/usrp_n310_fpga_HG.bit`    
should print information.

## Actual Behaviour ##

Calling `probe_bitfile /usr/share/uhd/images/usrp_n310_fpga_HG.bit` or    
`$REPO_BASE_PATH/tools/scripts/xil_bitfile_parser.py --info /usr/share/uhd/images/usrp_n310_fpga_HG.bit`    
results in this error:
```
Traceback (most recent call last):
  File "<path-to-uhd-repo>/fpga/usrp3/tools/scripts/xil_bitfile_parser.py", line 88, in <module>
    main()
  File "<path-to-uhd-repo>/fpga/usrp3/tools/scripts/xil_bitfile_parser.py", line 68, in main
    (header, data) = parse_bitfile(bit_file.read())
  File "<path-to-uhd-repo>/fpga/usrp3/tools/scripts/xil_bitfile_parser.py", line 42, in parse_bitfile
    header[KEYNAMES[key]] = str(val).rstrip('\0')
KeyError: 97
```
## Steps to reproduce the problem ##

```
. <path-to-uhd-repo>/fpga/usrp3/top/n3xx/setupenv.sh
probe_bitfile /usr/share/uhd/images/usrp_n310_fpga_HG.bit
```

## Additional Information ##

Calling `python2 $REPO_BASE_PATH/tools/scripts/xil_bitfile_parser.py --info /usr/share/uhd/images/usrp_n310_fpga_HG.bit` works the way it should.

I changed [line 25](https://github.com/EttusResearch/uhd/blob/master/fpga/usrp3/tools/scripts/xil_bitfile_parser.py#L25) from
```
KEYNAMES = {'a':'design_name', 'b':'part_name', 'c':'date', 'd':'time'}
```
to
```
KEYNAMES = {'a':'design_name', 'b':'part_name', 'c':'date', 'd':'time', ord('a'):'design_name', ord('b'):'part_name', ord('c'):'date', ord('d'):'time'}
```
and now it works for me (with python2 and with python3).

**Comment by mbr0wn** [comment]
Thanks for the feedback. Upon running this, I discovered some more issues. We'll probably just drop Python2 support though.
