### ISSUE TITLE
Best practices for custom_dsp_rx on usrp3

### ISSUE THREAD

**Issue by andreaskuster** [EttusResearch/uhd#476]
The `usrp2` FPGA device family offers a nice interface to glue custom modules into the rx respectively the tx chains (i.e. [Customization Instructions](https://files.ettus.com/manual/md_usrp2_customize_signal_chain.html), [custom_dsp_rx.v](https://github.com/EttusResearch/uhd/blob/master/fpga/usrp2/custom/custom_dsp_rx.v), [dsp_rx_glue.v](https://github.com/EttusResearch/uhd/blob/546ea894a0d5dd23dd046ef3b3c2d61acebefa98/fpga/usrp2/sdr_lib/dsp_rx_glue.v) )

However, such a nice interface seems to be nonexistent for the `usrp3` product family. 

- Is this feature still in your work pipeline? 
   - If yes: What is the time frame? 
   - If no: Is there a specific reason (other than time/resources)?
- Would you encourage/accept a pull request if I adjust the pipeline like the `usrp2` solution?

- What are the best practices (especially in terms of middle to long term maintainability of these out-of-tree modification) to integrate a custom module after the DDC rx chain and/or before the DUC tx chain for usrp3 devices?

**Comment by mbr0wn** [comment]
Hi @andreaskuster,

we have put a lot of work over the years into our RFNoC architecture, which replaces this custom DSP architecture. It is way more flexible, and doesn't require tainting the repository. There's a lot of documentation, maybe you can start here: https://kb.ettus.com/Getting_Started_with_RFNoC_Development

RFNoC works on all Gen-3 devices, and also the X410.
