### ISSUE TITLE
Duplicate Mako Generation in CMakeLists

### ISSUE THREAD

**Issue by johnwstanford** [EttusResearch/uhd#478]
Probably not a problem, but `max2112_regs.hpp` is listed twice in this `CMakeLists.txt`:

https://github.com/EttusResearch/uhd/blob/a7486cbfba959d7f55a9343db66eabee94786b2f/host/lib/ic_reg_maps/CMakeLists.txt#L75

**Comment by michaelld** [comment]
Thanks for the info @johnwstanford  ... I've created a PR to remove the duplicate
