### ISSUE TITLE
make uninstall leaves lib symbolic links installed

### ISSUE THREAD

**Issue by nldudok1** [EttusResearch/uhd#48]
When I uninstall uhd 3.10 it leaves the following links installed
libuhd.so -> libuhd.so.003
libuhd.so.003 -> libuhd.so.003.010

sudo make uninstall
....
-- Uninstalling "[PREFIX]/lib/libuhd.so.003.010"
-- Uninstalling "[PREFIX]/lib/libuhd.so.003"
-- File "[PREFIX]/lib/libuhd.so.003" does not exist.
-- Uninstalling "[PREFIX]/lib/libuhd.so"
-- File "[PREFIX]/lib/libuhd.so" does not exist.
....

ls -liah [PREFIX]/lib/libuhd*
[PREFIX]/libuhd.so -> libuhd.so.003
[PREFIX]/lib/libuhd.so.003 -> libuhd.so.003.010

This is probably a cmake issue.
cmake --version
cmake version 2.8.12.2

I think the problem is.
It first uninstalls libuhd.so.003.010
After that it tries to do uninstall libuhd.so.003 and libuhd.so which are now symbolic link to a now non-existant file. This results in the make error:
File "/opt/mlat/lib/libuhd.so.003" does not exist.
File "/opt/mlat/lib/libuhd.so" does not exist.

I am not sure on how to solve this.

**Comment by mbr0wn** [comment]
4503c7e6287e4204af946c9aa6e669f76c9b8289 should fix this -- please let us know if it doesn't solve your problem entirely.
