### ISSUE TITLE
Possible Typo in MAX_RATE_1GIGE

### ISSUE THREAD

**Issue by johnwstanford** [EttusResearch/uhd#481]
We use `10e9` for `MAX_RATE_10GIGE` and `10e9` again for `MAX_RATE_1GIGE`.  I think it should be `1e9` for `MAX_RATE_1GIGE`.

https://github.com/EttusResearch/uhd/blob/546ea894a0d5dd23dd046ef3b3c2d61acebefa98/host/lib/usrp/x300/x300_eth_mgr.cpp#L64

**Comment by mbr0wn** [comment]
Definitely a typo. In older versions, this number was correct.
