### ISSUE TITLE
Unused variable in `x300_eth_mgr.cpp`

### ISSUE THREAD

**Issue by johnwstanford** [EttusResearch/uhd#482]
It looks like `default_buff_args` is never used.

https://github.com/EttusResearch/uhd/blob/919043f305efdd29fbdf586e9cde95d9507150e8/host/lib/usrp/x300/x300_eth_mgr.cpp#L229

**Comment by mbr0wn** [comment]
Good catch. I'm surprised none of the compilers have complained.

**Comment by mbr0wn** [comment]
Fix will be public soon.
