### ISSUE TITLE
Missing Frequencies in Error Message

### ISSUE THREAD

**Issue by johnwstanford** [EttusResearch/uhd#483]
The error message only lists 10 and 30.72 MHz as valid frequencies, but it looks like 11.52 and 23.04 MHz are also allowed.

https://github.com/EttusResearch/uhd/blob/919043f305efdd29fbdf586e9cde95d9507150e8/host/lib/usrp/x300/x300_clock_ctrl.cpp#L641

**Comment by manderseck** [comment]
@johnwstanford Thanks for reporting this issue. Looking into the history of that file it seems like the error message was forgotten when support for 11.52 MHz and 23.04 MHz references was added. Let me fix this.

**Comment by manderseck** [comment]
The issue is fixed internally but it will take a few days before it goes public.
