### ISSUE TITLE
How to build using cmake's FetchContent

### ISSUE THREAD

**Issue by pfeatherstone** [EttusResearch/uhd#489]
I would like to add uhd as a dependency in my cmake script using FetchContent.
Is there a way to do that?
Thank you very much.

**Comment by mbr0wn** [comment]
This is a very CMake-related question, so I'll close this here. Short answer, we haven't experimented with it yet. Seems like CMake has decent documentation: https://cmake.org/cmake/help/latest/module/FetchContent.html

...but it needs to be used in projects outside of UHD.
