### ISSUE TITLE
X310 FPGA Compatibility Number

### ISSUE THREAD

**Issue by drewvian** [EttusResearch/uhd#50]
The current version of the UHD driver has a bad compatibility number when compared to the X310 FPGA image.

Error: RuntimeError: Expected FPGA compatibility number 18, but got 17:

This error in not corrected by re-downloading the FPGA image and then writing the image to the X310 using the uhd_images_downloader.py and uhd_image_loader utilities. This problem occurs using the X310 connected by PCIE and also 1GigE connection.

**Comment by mbr0wn** [comment]
Yes, we know, we pushed a commit prematurely. We'll have this sorted out ASAP.
