### ISSUE TITLE
X310 USRP Dual TwinRX LEDs not turning on properly

### ISSUE THREAD

**Issue by icyveins7** [EttusResearch/uhd#500]
## Issue Description ##
X310 with two TwinRX daughterboards, opening all 4 channels for receive via a subdev spec of "A:0 A:1 B:0 B:1", and channels "0,1,2,3", results in only the RX2 lights of both daughterboards turning on. Further experimentation shows that the order in which the channels are selected matters i.e. Doing A:RX1, A:RX2, B:RX2, B:RX1 (via GNURadio) results in only the A:RX2 and B:RX1 lights being on.

The recording itself was unaffected i.e. even though the LED was off, it was still recording 4 channels correctly (tested with external signal source plugged into each channel one by one).

Issue did not occur when using UHD 3.15.0 (and subsequently also re-flashing the FPGA for compatibility, so it may be the FPGA image that is the cause). All lights turned on.

## Setup Details ##
UHD 4.0 and 4.1 were tested and were the culprits. FPGA versions were whatever was required i.e. upon uhd_usrp_probe, if asked to re-flash due to compatibility issues for that version, I did so.

OS: Both Windows 10 and Ubuntu had the same issue.
Hardware: Has occurred on both my laptop (i7-8565UC) and my desktop (Ryzen 5 1600x).

## Expected Behavior ##
All 4 LEDs should light up, as per the UHD 3.15.0 test.

## Actual Behaviour ##
Only the 2nd selected antenna for each TwinRX lights up (example in the description at the start).

## Steps to reproduce the problem ##
Easiest way to reproduce is to run 

```
rx_multi_samples --rate 200000 --subdev="A:0 A:1 B:0 B:1" --channels 0,1,2,3
```

and observe the LEDs below the SMA ports. I also used GRC to hook up a UHD Source to 4 outputs, with the same subdev config, and played around with channel antennas. This allowed me to change the ordering to A:RX1, A:RX2, B:RX2, B:RX1, which then showed that only the second antenna LEDs lit up (in this case, A:RX2 and B:RX1).

## Additional Information ##
Nothing for now.

**Comment by mbr0wn** [comment]
We have a fix for this which will become public in the near future.
