### ISSUE TITLE
Why UBX 160 gain not work (for RX and TX)

### ISSUE THREAD

**Issue by stackprogramer** [EttusResearch/uhd#501]
Hi, in my USRP x310 I used a daughterboard  ubx160, but in Gnuradio gain is not effect...
gain 0 and gain 100 show the same signal...for FM station it can not show any signal  How can solve my problem?

Gnuardio 3.8.1
UHD 3.15.1

thanks in advance

**Comment by mbr0wn** [comment]
UBX gain certainly works.
