### ISSUE TITLE
TRYING TO COMPILE FROM SOURCE CODE ON WINDOWS

### ISSUE THREAD

**Issue by 2556235254** [EttusResearch/uhd#505]
## Issue Description ##

Failing to compile and install with visual studio on windows

## Setup Details ##

Based on: https://files.ettus.com/manual/page_build_guide.html
After building and generating the project with cmake with adding ENABLE_USB with no errors,
I am opening Visual studio as a admin, I can build the project ALL_BUILD with no errors, 
But when I try to build INSTALL, I get an error:
"MSB3073: The command "setlocal "C:\Program Files\cmake-3.13.4XXX\bin\cmake.exe" -DBUILD_TYPE=DEBUG cmake_install.cmake ............... "
In Project INSTALL, File Microsoft.CppCommon.targets, line 138.

VERSIONS:
Visual Studio: I get the same error with Visual Studio 2017 and 2019
OPEN SOURCE CODE FROM RELEASE uhd 4.0.0.0
CMAKE 3.13.4
BOOST 1_71_0
LIBUSB 1.0.22
PYTHON 3.7
NSIS 3.04

CMake Generate output:
UHD enabled components:
- LibUHD
- LibUHD - C API
- LibUHD - Python API
- Examples
- Utils
- Tests
- USB
- B100
- B200
- USRP1
- USRP2
- X300
- MPMD
- N300
- N320
- E320
- E300

UHD disabled components:
- DPDK
- Manual
- API / Doxygen
- Man Pages

## Expected Behavior ##

NO ERRORS AND I WANT TO BE ABLE TO USE PYTHON API WITH USRP B200

## Actual Behaviour ##

COMPILATION FAILS

**Comment by manderseck** [comment]
@2556235254 Since I haven't heard anything back from you on this issue anymore I assume it is resolved in the meantime. I'll close the issue but please feel free to re-open if the issue persists and more support is required. Thanks!
