### ISSUE TITLE
Why when change frequency USRP x300, frequency change is not change real time???

### ISSUE THREAD

**Issue by stackprogramer** [EttusResearch/uhd#513]
I record a signal from USRP when I change the frequency USRP from below 80 MHz to 89 MHZ, USRP does not change frequency instantaneously......
USRP frequency change is alike step change and 2 seconds is time to lock completely on 89 MHZ.....
when I ping to address USRP 192.168.10.2 it takes a long .5 ms......But when I changed the frequency of USRP x300 with GUI Gnuradio I see this response. I too test this case in CPP....but...problem yet there is.....

This response screenshot is recorded with another SDR hardware...........

Thanks in advance
![Untitled](https://user-images.githubusercontent.com/11349841/138687718-05c59d62-8167-4b72-a1b7-c47c1d0f4231.png)

**Comment by mbr0wn** [comment]
@stackprogramer When using GNU Radio, you have a lot of buffering, and bad latency, which is part of the issue. If you so desire, you can program UHD to change frequency on the exact sample that you wish (plus the hardware delay, which can be up to a few hundred us, depending on hardware).
