### ISSUE TITLE
Inconsistent documentation of dependencies

### ISSUE THREAD

**Issue by TSlivede** [EttusResearch/uhd#516]
## Issue Description ##

When trying to find out which packages I need to install on Ubuntu 20 to satisfy the dependencies to build and use UHD, the documentation seemed inconsistent.

## Setup Details ##

Current master branch of UHD
Current state of the knowledge base

## Expected Behavior ##

I expected, that the packages listed [here](https://kb.ettus.com/RFNoC_4_Migration_Guide#Dependencies_.28Ubuntu_20.04.29), [here](https://kb.ettus.com/Building_and_Installing_the_USRP_Open-Source_Toolchain_(UHD_and_GNU_Radio)_on_Linux#Update_and_Install_dependencies) and here

https://github.com/EttusResearch/uhd/blob/748162e6a9a018f6cf377be8f9a68a7445060336/host/docs/build.dox.in#L128

are the same.

## Actual Behaviour ##

Each of the lists is missing some packets that are listed in one of the other lists.

## Additional Information ##

I just installed the packages of all three lists and it seems to work, but it would be nice if the documentation were more consistent.

**Comment by TSlivede** [comment]
@manderseck 

Nitpicking:

On https://kb.ettus.com/RFNoC_4_Migration_Guide the last edit description says
>Remove GNU Radio dependencies (not required for UHD only))
and it seems those were indeed removed. However the page still contains instructions to build gnuradio:
https://kb.ettus.com/RFNoC_4_Migration_Guide#GNU_Radio_3.8
Maybe those dependencies should have been moved there instead of completely removing them?

**Comment by manderseck** [comment]
@TSlivede Thanks for nitpicking, this is really appreciated! 
Since this is the migration guide to UHD 4.0 I think it's fair to not treat it like a fresh install, therefore omitting the GNU Radio dependencies there makes sense in my opinion. Nevertheless I have added a link to the official build instructions of GNU Radio where all dependencies are listed anyway.
For libtinfo5 and libncurses5 you are right. It doesn't make sense to remove them if we refer to them only a paragraph later. And they are still required, so I brought them back into the deps.

**Comment by TSlivede** [comment]
If you like nitpicking, here is one more:

If libtinfo5 and libncurses5 are necessary for Xilinx, those should probably also be listed under "Setting up build dependencies on Ubuntu" on https://files.ettus.com/manual/md_usrp3_build_instructions.html.

Currently only get them if you follow the migration guide, the https://kb.ettus.com/Getting_Started_with_RFNoC_in_UHD_4.0 doesn't list any dependencies or build instructions. (Shouldn't that getting started guide also contain a minimal build instructions, similar to the migration guides [Prerequisits](https://kb.ettus.com/RFNoC_4_Migration_Guide#Prerequisites)?)

One could even think about adding libtinfo5 to the dependencies on https://kb.ettus.com/Building_and_Installing_the_USRP_Open-Source_Toolchain_(UHD_and_GNU_Radio)_on_Linux#Update_and_Install_dependencies and on https://files.ettus.com/manual/page_build_guide.html   (ncurses is already in those dependencies)
 Even though these pages don't actually use Xilinx, someone might assume that these packages are all packages one needs for anything UHD related. And libtinfo5 is a relatively small library, so it wouldn't really hurt. But I guess, this is rather opinion based...

**Comment by TSlivede** [comment]
@manderseck

Also shouldn't places like "Additional Resources" on https://www.ettus.com/all-products/usrp-n310/ by now link to the RFNoC 4 getting started guide? Or at least there should be a huge "This is outdated" note on the linked https://kb.ettus.com/Getting_Started_with_RFNoC_Development

**Comment by manderseck** [comment]
@TSlivede Thanks again for your remarks. Since it seems like we'll get from one issue to the next we'll take them into account when reworking the documents completely.
