### ISSUE TITLE
[INFO] [UHD RF] Tx while waiting for EOB, timed out... 20.6379 >= 0. Starting new burst... 

### ISSUE THREAD

**Issue by akhila-rao** [EttusResearch/uhd#518]
## Issue Description ##

I run srsRAN on X310 USRP devices. During operation I see this message a lot. What does it mean ? What could be causing it ? 
Any solutions ?  

## Setup Details ##

I use X310 with UBX daughter boards. 
I use the latest UHD 4.2, but I saw the same errors when I used UHD 3.15  

## Expected Behavior ##

I expect this error to not happen 
## Actual Behaviour ##

I see this error 

## Steps to reproduce the problem ##

I use the srsRAN version 21.04 over UHD 4.2 to set it up as an LTE basestation.  

## Additional Information ##

The sampling rate I use when I setup the LTE basestation is 11.52e6

**Comment by michaelld** [comment]
@akhila-rao a couple thoughts: (1) UHD 4.2 has not been released; it is still in beta. Please use the latest 4.1 release instead and see if that works & if not then update your post here. (2) please provide a run log that includes all of the printouts for UHD and whatever app is using it. What you've provided doesn't provide enough info for us to help.

**Comment by mbr0wn** [comment]
Closing this bug report, as it's partly related to srs, partly using a beta version, and partly because it's inactive.
