### ISSUE TITLE
purpose of control:   sw_iface: nocscript

### ISSUE THREAD

**Issue by TSlivede** [EttusResearch/uhd#519]
## Issue Description ##

Not really a functional problem, but I was wondering what the purpose of
```
control:
  sw_iface: nocscript
```
in many (all?) RFNoC-Block description yaml files is. It does not seem to be documented anywhere (KB, UHD-Manual or RFNoC-Spec). I also couldn't find references in code...

## Setup Details ##

current (2021-11-03) state of documentation

## Expected Behavior ##

I expected to find documentation about the `sw_iface` key, or at least a code location where it is interpreted, ....

## Actual Behaviour ##

... but all I could [find](https://github.com/search?q=org%3AEttusResearch+sw_iface&type=Code) is the snipet in yaml files and within a template. [Google](https://www.google.com/search?q=sw_iface+site%3Aettus.com) also just lists pages where it is used, but not where it is explained...

## Steps to reproduce the problem ##

Try to look for the meaning of `sw_iface` yourself :smiley: 

## Additional Information ##

Is it possible that it is not actually used for anything and could be removed to not confuse people?

**Comment by mbr0wn** [comment]
It's a vestige from an intermediate state of the RFNoC spec. It can be removed. Thanks for pointing out!
