### ISSUE TITLE
ALL_CHANS wildcard not working on Windows

### ISSUE THREAD

**Issue by trocotronic** [EttusResearch/uhd#52]
Currently ALL_CHANS is defined as size_t(~0) in Windows, which produces arbitrary number. However, UHD driver identifies ALL_CHANS as a particular channel. For instance, dev->set_tx_gain(30, ALL_CHANS) throws the following error

Error: LookupError: IndexError: multi_usrp: TX channel 18446744073709551615 out of range for configured TX frontends

It should apply the parameter to all channels instead of throwing this error.

**Comment by mbr0wn** [comment]
Hi @trocotronic, thanks for pointing this out. Yes, `ALL_CHANS` is not recognized by all methods of `multi_usrp`. We'll move it into the queue. Thanks!
