### ISSUE TITLE
Could UHD for Zed+FMCOMMS2 be possible？

### ISSUE THREAD

**Issue by vvverilog** [EttusResearch/uhd#525]
Hi, I want to now is there some guide for porting the uhd into the xilinx zynq board and adi RF frontend?

If this could be done, how to make the boot image for these board？

thanks!

**Comment by christian-hahn** [comment]
Hi Martin,

Do you have a link to the ZCU111 port?

Many thanks,
Christian

**Comment by mbr0wn** [comment]
No, someone on the usrp-users mailing list was talking about it.
