### ISSUE TITLE
Variable Never Used in chdr_ctrl_endpoint

### ISSUE THREAD

**Issue by johnwstanford** [EttusResearch/uhd#529]
It looks like `_num_drops` is never modified in `chdr_ctrl_endpoint`.  It's just initialized to zero and made available through a getter function, which will always return zero.

https://github.com/EttusResearch/uhd/blob/ef94c93a0822beda2f8c691bd4390727f7355322/host/lib/rfnoc/chdr_ctrl_endpoint.cpp#L174

**Comment by mbr0wn** [comment]
Thanks for yet another great scoop. The variable should be incremented in the recv loop, either for unknown EPIDs, or when we receive garbage. A fix is on the way.
