### ISSUE TITLE
Same Key Twice in a Map

### ISSUE THREAD

**Issue by johnwstanford** [EttusResearch/uhd#537]
The key `1` occurs twice in this map.  I think the second one should be `2`.

https://github.com/EttusResearch/uhd/blob/ef94c93a0822beda2f8c691bd4390727f7355322/host/lib/include/uhdlib/usrp/common/max287x.hpp#L301

**Comment by manderseck** [comment]
@johnwstanford Thanks for reporting this. It looks suspicious indeed. A change is on its way.
