### ISSUE TITLE
Comment Doesn't Seem to Match Code

### ISSUE THREAD

**Issue by johnwstanford** [EttusResearch/uhd#542]
`0x0000 for RX` in 

https://github.com/EttusResearch/uhd/blob/f23ab72129041777bcd3357a1f4e37b29e62dd86/host/lib/rfnoc/radio_control_impl.cpp#L1022

`SWREG_RX_ERR      = 0x1000` in 

https://github.com/EttusResearch/uhd/blob/f23ab72129041777bcd3357a1f4e37b29e62dd86/host/lib/include/uhdlib/rfnoc/radio_control_impl.hpp#L284

**Comment by mbr0wn** [comment]
Yup good catch. Thanks.
