### ISSUE TITLE
Copied comment does not match code

### ISSUE THREAD

**Issue by dylan-baros** [EttusResearch/uhd#545]
## Issue Description ##

Comment is copied from its RX counterpart. This is actually converting _to_ the internal buffer. 
https://github.com/EttusResearch/uhd/blob/f23ab72129041777bcd3357a1f4e37b29e62dd86/host/lib/transport/super_send_packet_handler.hpp#L340-L346

**Comment by mbr0wn** [comment]
Fair point. We'll provide an update.
