### ISSUE TITLE
Implementation of get_sync_sources (and set_sync_source?) missing for E3xx radios

### ISSUE THREAD

**Issue by draeman-synoptic** [EttusResearch/uhd#555]
## Issue Description ##
On an E320 and using UHD 4.1.0.1, calling get_sync_sources() on a multi_usrp object throws a timeout exception. Based on code inspection, the implementation of this call for Zynq-based radios is delegated to the Python MPM peripheral manager in /mpm/python/usrp_mpm/periph_manager/.  The call is implemented in n3xx.py and x4xx.py, but is missing in e320py and e31x.py.  Although I did not attempt to call set_sync_source from the multi_usrp object, at a glance that call also appears to be missing.

## Setup Details ##
UHD 4.1.0.1 and E320.  Based on browsing the code, the implementation still appears to be missing as of UHD 4.1.0.5.

## Expected Behavior ##
Constructing a multi_usrp object for an E320 radio and calling get_sync_sources() returns a vector of supported sync sources.

## Actual Behaviour ##
Constructing a multi_usrp object for an E320 radio and calling get_sync_sources() throws a timeout exception.

**Comment by mbr0wn** [comment]
Confirmed, this is an issue.
