### ISSUE TITLE
CentOS 6.5 and 6.6

### ISSUE THREAD

**Issue by sgardner340** [EttusResearch/uhd#56]
Hi All

I am having failures with Centos 6.5 and 6.6 because of the new python 2.7 requirements for uhd. Centos 6.5 and 6.6 need python 2.6 for yum functionality. Is there a work around that will not affect the other dependencies?

18:43:31 Current step: (uhd :: make)
18:43:31 make
18:43:31 bashexec (/home/hudson/workspace/PyBombs_Build_All_Matrix_New_Gitlab/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/src-rpm/src/uhd/host/build):: 
18:43:31     find . -name '*.make' -print0 | xargs -0 sed -i 's/\(^.*\)\(--cyan \"\)\(.*\)\"$/\1\2\x1b[36;1m\3\x1b[0m\"/;s/\(^.*\)\(--green \"\)\(.*\)\"$/\1\2\x1b[32;1m\3\x1b[0m\"/;s/\(^.*\)\(--red --bold \"\)\(.*\)\"$/\1\2\x1b[31;1m\3\x1b[0m\"/;s/\(^.*\)\(--blue --bold \"\)\(.*\)\"$/\1\2\x1b[34;1m\3\x1b[0m\"/'
18:43:31     find . -name 'Makefile' -print0 | xargs -0 sed -i 's/\(^.*\)\(--cyan \"\)\(.*\)\"$/\1\2\x1b[36;1m\3\x1b[0m\"/;s/\(^.*\)\(--green \"\)\(.*\)\"$/\1\2\x1b[32;1m\3\x1b[0m\"/;s/\(^.*\)\(--red --bold \"\)\(.*\)\"$/\1\2\x1b[31;1m\3\x1b[0m\"/;s/\(^.*\)\(--blue --bold \"\)\(.*\)\"$/\1\2\x1b[34;1m\3\x1b[0m\"/'
18:43:31     ln -s /home/hudson/workspace/PyBombs_Build_All_Matrix_New_Gitlab/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/src-rpm/colorgcc.pl /apps/smokey64/bin/cc
18:43:31     ln -s /home/hudson/workspace/PyBombs_Build_All_Matrix_New_Gitlab/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/src-rpm/colorgcc.pl /apps/smokey64/bin/gcc
18:43:31     ln -s /home/hudson/workspace/PyBombs_Build_All_Matrix_New_Gitlab/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/src-rpm/colorgcc.pl /apps/smokey64/bin/c++
18:43:31     ln -s /home/hudson/workspace/PyBombs_Build_All_Matrix_New_Gitlab/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/src-rpm/colorgcc.pl /apps/smokey64/bin/g++
18:43:31     make -j4
18:43:31 
18:43:31 sed: no input files
18:43:31 sed: no input files
18:43:31 make: *** No targets specified and no makefile found.  Stop.
18:43:31 bash return val = 2
18:43:31 Traceback (most recent call last):
18:43:31   File "./pybombs", line 360, in <module>
18:43:31     main()
18:43:31   File "./pybombs", line 357, in main
18:43:31     sys.exit(cli(parser,opts,args))
18:43:31   File "./pybombs", line 171, in cli
18:43:31     pybombs_ops.install(p, not opts.force);
18:43:31   File "/home/hudson/workspace/PyBombs_Build_All_Matrix_New_Gitlab/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/src-rpm/mod_pybombs/pybombs_ops.py", line 151, in install
18:43:31     global_recipes[pkg].install();
18:43:31   File "/home/hudson/workspace/PyBombs_Build_All_Matrix_New_Gitlab/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/src-rpm/mod_pybombs/recipe.py", line 531, in install
18:43:31     st = self.install_src();
18:43:31   File "/home/hudson/workspace/PyBombs_Build_All_Matrix_New_Gitlab/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/src-rpm/mod_pybombs/recipe.py", line 598, in install_src
18:43:31     self.install_order[step][1]();
18:43:31   File "/home/hudson/workspace/PyBombs_Build_All_Matrix_New_Gitlab/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/src-rpm/mod_pybombs/recipe.py", line 658, in make
18:43:31     assert(st == 0);
18:43:31 AssertionError
18:43:31 Build step 'Execute shell' marked build as failure
18:43:31 [WARNINGS] Skipping publisher since build result is FAILURE
18:43:31 Email was triggered for: 1st Failure

**Comment by mbr0wn** [comment]
@sgardner340 on a side note, let me say that we've dropped 2.6 support on master, so only maint will work. Can you confirm you're not building master?

The error message looks like a PyBOMBS1 error. What is the UHD error your're seeing?

Also, remember you can easily install a different Python version into a virtualenv and then use that to build UHD and run PyBOMBS.
