### ISSUE TITLE
How do I set the gain of the USRP B210 via the command line tool?

### ISSUE THREAD

**Issue by shuimoshusheng** [EttusResearch/uhd#563]
Want to change the default gain of USRP B210.

**Comment by mbr0wn** [comment]
@shuimoshusheng This sounds less like a bug, more like a usage question. If you're using our examples, then usually there's a `--gain` argument. The default gain is fixed to 0 (https://github.com/EttusResearch/uhd/blob/master/host/lib/usrp/common/ad936x_manager.cpp#L24), but I'm not sure that's what you want.

I recommend moving this discussion to the mailing list.
