### ISSUE TITLE
please release 4.1.0.6

### ISSUE THREAD

**Issue by ZeroChaos-** [EttusResearch/uhd#569]
Specifically it would be great if I got a release with:
https://github.com/EttusResearch/uhd/commit/da1ee1aa71501665b142cdb64fd4daa02793fbc1.patch
https://github.com/EttusResearch/uhd/pull/560

That first one doesn't apply cleanly to 4.1.0.5 due to surrounding changes and the second one is trivial.

**Comment by mbr0wn** [comment]
Sorry we couldn't respond sooner -- but we're actually releasing 4.2 soon, which includes this fix. RC is already out!
