### ISSUE TITLE
cmd time errors with UHD USRP sink

### ISSUE THREAD

**Issue by zhanght34** [EttusResearch/uhd#585]
I'm playing with gnuradio and an USRP X410 device.
I connect pc with USRP X410 by QFSP.I want to test how fast the QFSP port transfer rate is.
Then in gnuradio grc,i have connected two block:Sig Source and USRP Sink. Details as shown
![image](https://user-images.githubusercontent.com/102239404/164861607-f66c02c4-70c0-43d9-81bb-f9b8681b15d9.png)

When i run this grc,and set samp_ate to 30MHz，gnuradio printfs"cmd time errors".How to slove it?
![image](https://user-images.githubusercontent.com/102239404/164861594-20d95274-335b-450e-84f2-2421e3c87fb1.png)

System Information
i9-11900F @ 2.50GHz
Ubuntu20.04
GNU Radio 3.10.1.1
Python 3.8.10
UHD 4.2.00-rc1

USRP X410 fpga image
X4_200

GNU Radio Version
3.10 (maint-3.10)

Specific Version
3.10.1.1

Error message printfs"
Susrp_sink :error: In the last 28292 ms, 1 cmd time errors occurred.
SSSSSSSSUusrp_sink :error: In the last 28298 ms, 1 underflows occurred.
"
At the same time, the light on the usrp x410 showing the RF transmit go off.

**Comment by raefYoussef** [comment]
I have the same issue. Did you ever get it solved?

**Comment by mbr0wn** [comment]
We have too little data, so I'm closing this. In general, using the USRP Sink works with X410 and other devices.

**Comment by Shirleyue** [comment]
> I have the same issue. Did you ever get it solved?

I have the same issue. Did you ever get it solved? Please contact me if you get it solved.  My email address is shirleyuue@foxmail.com.
