### ISSUE TITLE
RFNOC : GRAPH ERROR x310 + TVRX2

### ISSUE THREAD

**Issue by himanshu10140** [EttusResearch/uhd#587]
USRP X310 with 01 TVRX2 daughterboard
Latest uhd (v4.2.0.0)
X310 + SBX = working without any issue

uhd(v3.14) = TVRX2 gets detected without any issue

![Screenshot from 2022-04-28 13-03-48](https://user-images.githubusercontent.com/5058165/165981862-d99c6f21-0f62-4628-b3ba-2775abe795ad.png)

**Comment by mbr0wn** [comment]
Is only uhd_usrp_probe failing, or also other utilities/examples?

Did you build UHD from source? If so, can you please rebuild with `-DUHD_LOG_MIN_LEVEL=trace`.

In any case, can you please set the log level to max (`export UHD_LOG_LEVEL=trace`, `export UHD_LOG_CONSOLE_LEVEL=trace`) and post the output here?

**Comment by mbr0wn** [comment]
Closing due to lack of feedback.
