### ISSUE TITLE
N320 TDC Measurement Error 

### ISSUE THREAD

**Issue by jpalladino** [EttusResearch/uhd#595]
We've been having an issue with occasional TDC measurement errors on all of our N320s since updating to UHD 4.1.0.5. Here is an example of the output of a uhd_usrp_probe when this occurs.

```
[INFO] [UHD] linux; GNU C++ version 7.5.0; Boost_106501; UHD_4.1.0.HEAD-0-g6bd0be9c

[DEBUG] [MPMD] Discovering MPM devices on port 49600

[DEBUG] [MPMD] Discovering MPM devices on port 49600

[DEBUG] [MPMD] Discovering MPM devices on port 49600

[DEBUG] [MPMD] Discovering MPM devices on port 49600

[INFO] [MPMD] Initializing 1 device(s) in parallel with args: mgmt_addr=192.168.40.2,type=n3xx,product=n320,serial=31EDED4,fpga=XG,claimed=False,addr=192.168.40.2

[DEBUG] [MPMD] Claiming mboard 0

[DEBUG] [MPMD] Device args: `mgmt_addr=192.168.40.2,type=n3xx,product=n320,serial=31EDED4,fpga=XG,claimed=False,addr=192.168.40.2'. RPC address: 192.168.40.2

[DEBUG] [MPMD] MPM reports device info: addr=192.168.30.2,claimed=True,connection=remote,dboard_0_pid=338,dboard_0_serial=31EBB6F,dboard_1_pid=338,dboard_1_serial=31EBB94,description=N300-Series Device,eeprom_version=3,fpga=XG,fpga_version=8.0,fpga_version_hash=6bd0be9.clean,fs_version=20211215135436,mender_artifact=v4.1.0.5_n3xx,mpm_sw_version=4.1.0.5-g6bd0be9c,mpm_version=4.0,name=ni-n3xx-31EDED4,pid=16962,product=n320,rev=10,rpc_connection=remote,second_addr=192.168.40.2,serial=31EDED4,type=n3xx

[DEBUG] [MPMD] Found 8 motherboard sensors.

[DEBUG] [MPMD] Initializing mboard 0

[INFO] [MPM.PeriphManager] init() called with device args `fpga=XG,mgmt_addr=192.168.40.2,product=n320,clock_source=internal,time_source=internal'.

[INFO] [MPM.Rhodium-0] init() called with args `fpga=XG,mgmt_addr=192.168.40.2,product=n320,clock_source=internal,time_source=internal'

[INFO] [MPM.Rhodium-1] init() called with args `fpga=XG,mgmt_addr=192.168.40.2,product=n320,clock_source=internal,time_source=internal'

[INFO] [MPM.Rhodium-0.init.LMK04828] LMK initialized and locked!

[ERROR] [MPM.Sync-0] TDC measurements show a wide range of values! Check your clock rates for incompatibilities.

[INFO] [MPM.Rhodium-1.init.LMK04828] LMK initialized and locked!

[ERROR] [RPC] TDC measurement out of expected range!

[INFO] [MPM.Rhodium-1.DAC37J82] DAC PLL Locked!

[INFO] [MPM.Rhodium-1.AD9695] ADC PLL Locked!

[INFO] [MPM.Rhodium-1.init] JESD204B Link Initialization & Training Complete

[ERROR] [MPM.RPCServer] init() failed with error: TDC measurement out of expected range!

Error: RuntimeError: Error during RPC call to `init'. Error message: TDC measurement out of expected range!

```

The TDC measurement errors can be reproduced at least somewhat consistently with the following command:

while true; do uhd_usrp_probe --args="force_reinit=1,master_clock_rate=200000000"; done

The "force_reinit=1" argument forces the clocks to get setup each time. If we let this run while the UHD 4.1.0.4 or prior filesystem is installed on an N320, we have not been able to reproduce the TDC error. Using the filesystem from UHD 4.1.0.5-rc1 and later and running the above command results in occasional TDC errors. They occur randomly, but if we leave it running, we'll usually see at least a few per hour. We tended to leave it running over night and check for errors the next morning.

It looks like the problem is related to a change made in the LMK04848 configuration in MPM. In UHD commit d7ee3dcf4a7478a17a094a1be2cba37b98843963, some register writes were changed to decrease PLL lock time. It looks like these registers set the amount of time that the phase detector error must be within a certain window before Lock Detect is asserted. I'm guessing that the reduction in time required to declare lock (number of clock cycles) might be too aggressive. It works most of the time, but not always. 

Making the following edits to /usr/lib/python3.7/site-packages/usrp_mpm/dboard_manager/lmk_rh.py seems to fix the issue. Note that this file must be edited on the N320.

Replace:

            (0x15B, 0xC7), # PLL1 PFD: negative slope for active filter / CP = 750 uA

            (0x15C, 0x0F), # PLL1 DLD Count [13:8]

With:

            (0x15B, 0x27), # PLL1 PFD: negative slope for active filter / CP = 750 uA

            (0x15C, 0x10), # PLL1 DLD Count [13:8]

This just undoes the change made in the commit mentioned above and requires more time before the LMK04848 declares lock. With this change, the measured skew seems to stay within the +/-500ps of tolerated skew in the "measure" function in tdc_sync.py.

**Comment by mbr0wn** [comment]
@jpalladino Thanks for the issue. We have confirmed this in an investigation on our side and will push the revert soon.
