### ISSUE TITLE
Python API -- failed to import

### ISSUE THREAD

**Issue by SubtleMuffin** [EttusResearch/uhd#597]
## Issue Description ##

Failed to import `uhd` Python module.

## Setup Details ##

UHD v4.3 (5333d3d12ffc21229ec4203a9ea1c7f68d82e57f), Ubuntu 22.04, N210

## Expected Behavior ##

Success in importing the module

## Actual Behaviour ##

Here is the log
```
>>> import uhd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ece/miniconda3/envs/research/lib/python3.10/site-packages/uhd-4.3.0-py3.10.egg/uhd/__init__.py", line 10, in <module>
    from . import types
  File "/home/ece/miniconda3/envs/research/lib/python3.10/site-packages/uhd-4.3.0-py3.10.egg/uhd/types.py", line 10, in <module>
    from . import libpyuhd as lib
ImportError: cannot import name 'libpyuhd' from partially initialized module 'uhd' (most likely due to a circular import) (/home/ece/miniconda3/envs/research/lib/python3.10/site-packages/uhd-4.3.0-py3.10.egg/uhd/__init__.py)
```

## Steps to reproduce the problem ##

```
git clone https://github.com/EttusResearch/uhd.git
cd uhd/host
mkdir build
cd build
cmake -DENABLE_PYTHON_API=ON -DENABLE_C_API=ON -DENABLE_TESTS=OFF -DENABLE_MANUAL=OFF ..
make -j8
sudo make install
sudo ldconfig
python3
```

**Comment by michaelld** [comment]
Echoing what @manderseck wrote: the default install prefix for UHD is `/usr/local`. Your `import uhd` shows it is trying to use `/home/ece/miniconda3/envs/research`. You need to fix the `PYTHON_EXECUTABLE` (for cmake to build UHD from the correct Python executable) and/or `PYTHONPATH` (for once UHD is built and installed, to tell this Python to use the correct UHD install).
