### ISSUE TITLE
E310/E312 not showing up under "uhd_find_devices"

### ISSUE THREAD

**Issue by mvl5023** [EttusResearch/uhd#612]
## Issue Description ##
I have multiple Ettus E310 and E312 devices that are connected over ethernet.  I can SSH into them, all seem to be working fine.  However, when I try to run "uhd_find_devices" from my host computer, it returns "No UHD devices found."

## Setup Details ##
Host computer is a Dell Latitude 5520 running Ubuntu 20.04 LTS.  I have installed UHD 4.1.0 on the host computer; I downloaded the SD card image using "uhd_images_downloader" and updated the SD cards of the SDRs.  I can SSH into the SDRs via an ethernet cable connected directly to the host, and I have verified that the UHD version matches the version run on the host computer.

I have edited the eth0.network files of the SDRs and assigned them all fixed IPv4 addresses; I have also manually configured the ethernet connection on the host computer to have a fixed IPv4 address, and have made sure that the host and all of the SDRs are on the same subnet.  I have tried connecting to the SDRs one at a time, as well as multiple at once using an unmanaged ethernet switch, but no matter what, when I try to use "uhd_find_devices," my host cannot find the USRPs.  I have used basically this exact same setup a while back using a different Dell laptop running the  same version of Ubuntu, the same version of UHD, connecting to the same USRPs, all with the same fixed IPv4 addresses on the same subnet, and uhd_find_devices worked just fine. On the new host laptop, it just isn't finding the USRPs. What am I missing?

## Expected Behavior ##
uhd_find_devices should show the list of all the USRPs connected on the same subnet.

## Actual Behaviour ##
uhd_find_devices returns no UHD devices found.

## Steps to reproduce the problem ##
Not sure

## Additional Information ##
None.

**Comment by wordimont** [comment]
Typically this kind of issue is related to network or firewall setup. I'm also running Ubuntu 20.04 LTS and don't see this issue. You might try the mailing list to see what ideas people have, or to see if anyone else has run into this. I think it's unlikely this is a bug. Network configuration tends to be error prone.

Make sure you don't have any firewall changes that could be affecting this. The only other thing I can think off the top of my head is to make sure you use NetworkManager to configure your host. ifconfig and NetworkManager don't play well together. I've seen behavior like this when I tried to use ifconfig to configure my host port for testing.

**Comment by michaelld** [comment]
Agreed with @wordimont . Please revisit the networking settings on both host computer and USRP; hopefully something obvious will come forth & you can fix it that way. If this issue persists, please email the USRP mailing list and/or Ettus Support ( support@ettus.com ). This feature of UHD works fine with my various E31x USRPs on UHD 3.15 to current master, so I'm closing this issue.

**Comment by mvl5023** [comment]
Great, thanks for the help!  The firewall is most likely the problem because that is the only parameter I can think of that has changed.  I just think it's odd that I can easily ping/SSH into the USRPs, but UHD cannot recognize them when the firewall is enabled.  I haven't used ifconfig to set IP addresses or make changes, I've only used NetworkManager to set up static IPv4 for the ethernet to USB adapter on the host computer

**Comment by marcivanmanalac** [comment]
Were you able to confirm that it was the firewall? im troubleshooting the same thing now on an ubuntu vm 20.04 able to ping and all just not able to find uhd
