### ISSUE TITLE
Need support in configuring TX1 in B200/B210

### ISSUE THREAD

**Issue by mayuri2016** [EttusResearch/uhd#62]
Default configuration in B200 code is always TX2 as FE1=1. I tried changing this to TX1 making FE1=0 and FE2=1. But this doesn't help. I don't see any o/p at AD9361. Can you please help?

**Comment by mbr0wn** [comment]
This sounds more like a support request. Can you please post it to the mailing list?

Also, I'm not sure what you're trying to do. When you post to the list, please provide some details on what you want to achieve. Thanks!

**Comment by mayuri2016** [comment]
Hi

Can u let me know the mailing list?

Regards
Mayuri

**Comment by mbr0wn** [comment]
https://www.ettus.com/support
