### ISSUE TITLE
[ERROR] [STREAMER] recv packet demuxer unexpected sid 0x260bae9

### ISSUE THREAD

**Issue by koh-osug** [EttusResearch/uhd#621]
## Issue Description ##

When starting [dlProbe](https://github.com/kotuliak/dlProbe) I get

> [ERROR] [STREAMER] recv packet demuxer unexpected sid 0x260bae9

## Setup Details ##

* Ubuntu 20.04 and Ubuntu 22.04
* UHD_4.2.0.1-0ubuntu1~focal1
* B205mini

## Expected Behavior ##

dlProbe runs. I t was already running, but I see that in August the uhd version 4.2.0 was released on the PPA Ubuntu page. From there I have installed it.

~~~shell
sudo apt-get install libuhd-dev libuhd4.2.0 uhd-host
sudo uhd_images_downloader
~~~

## Actual Behaviour ##

Application does not work:

> Reading configuration file dlProbe.conf...
> WARNING: cpu0 scaling governor is not set to performance mode. Realtime processing could be compromised. Consider setting it to performance mode before running the application.
> Opening 1 channels in RF device=default with args=default
> Available RF device list: UHD 
> Trying to open RF device 'UHD'
> [INFO] [UHD] linux; GNU C++ version 9.4.0; Boost_107100; UHD_4.2.0.1-0ubuntu1~focal1
> [INFO] [LOGGING] Fastpath logging disabled at runtime.
> [INFO] [B200] Loading firmware image: /usr/share/uhd/images/usrp_b200_fw.hex...
> Opening USRP channels=1, args: type=b200,master_clock_rate=23.04e6
> [INFO] [UHD RF] RF UHD Generic instance constructed
> [INFO] [B200] Detected Device: B205mini
> [INFO] [B200] Loading FPGA image: /usr/share/uhd/images/usrp_b205mini_fpga.bin...
> [INFO] [B200] Operating over USB 3.
> [INFO] [B200] Initialize CODEC control...
> [INFO] [B200] Initialize Radio control...
> [INFO] [B200] Performing register loopback test... 
> [INFO] [B200] Register loopback test passed
> [INFO] [B200] Asking for clock rate 23.040000 MHz... 
> [INFO] [B200] Actually got clock rate 23.040000 MHz.
> RF device 'UHD' successfully opened
> Waiting PHY to initialize ... done!
> Attaching UE...
> .
> Found Cell:  Mode=FDD, PCI=313, PRB=75, Ports=2, CP=Normal, CFO=4.2 KHz
> [INFO] [B200] Asking for clock rate 61.440000 MHz... 
> [INFO] [B200] Actually got clock rate 61.440000 MHz.
> [ERROR] [STREAMER] recv packet demuxer unexpected sid 0x24486e9

## Steps to reproduce the problem ##

After setting up dlProbe run it:

~~~shell
sudo dlProbe dlProbe.conf
~~~

## Additional Information ##

[dlProbe.conf.txt](https://github.com/EttusResearch/uhd/files/9355516/dlProbe.conf.txt)

**Comment by mbr0wn** [comment]
This is not enough information to go off of. There could be all sorts of issues at play, including the 3rd party software. Closing this.
