### ISSUE TITLE
error importing uhd into python broke a perfect install somehow!!

### ISSUE THREAD

**Issue by alexxmarsh44** [EttusResearch/uhd#631]
## Issue Description ##
I have been using the python UHD API for a solid couple of years with no problems.  I am running Arch Linux and installed uhd from the main package repository.  I have been coding with python in a python ide called pycharm.  Basically I am running python in a virtual environment that mirrors the site packages directory from the python system directory.  All is well and good until today.  I installed a package called gpsd a package I have used many times before.  It instantly breaks my uhd import.  Here is the following screenshot.  
![pythonscreen](https://user-images.githubusercontent.com/59932969/191160232-84c965e2-f20b-4a74-bcae-b40a5d23101a.png)
Any idea why this sudden error?  I really am in trouble here I was on the verge of finishing a huge direction finding project when this happened.  please help!

## Setup Details ##
usrp b210, libuhd latest version from pacman repo, and I use a copy of uhd from the site packages python3 directory and copy that to my virtual environment.

## Expected Behavior ##
clean import of uhd

## Actual Behaviour ##
throws error

## Steps to reproduce the problem ##
import uhd

**Comment by alexxmarsh44** [comment]
Also it appears that the missing file has a file by the same name but with version 80 instead of 79

**Comment by mbr0wn** [comment]
Sorry, can't reproduce. I'm guessing this must be specific to your setup. Maybe some .so couldn't be found.
