### ISSUE TITLE
OAI eNB with USRP B210: DL PRB = 25 (BW = 5 MHz) is normal, DL PRB = 6 ( BW = 1.4 MHz) often display "L" & "U" on terminal

### ISSUE THREAD

**Issue by davidyu1** [EttusResearch/uhd#64]
Hi Ettus,
When we used OAI eNB with USRP B210: 
Execution on DL PRB = 25 (BW = 5 MHz) is normal, 
but is abnormal on DL PRB = 6 ( BW = 1.4 MHz) is anormal and It often display "L" & "U" on terminal.
Do you know why it cause this issue?

Regards,
David Yu

**Comment by davidyu1** [comment]
Paste the log as follows:

linux; GNU C++ version 4.8.4; Boost_105400; UHD_003.009.004-release

# /dev/cpu_dma_latency set to 0us
log init done
Running with XFORMS!
num component carrier 1 

----------------------------------------------------------------------
 ENB CONFIG FILE CONTENT LOADED (TBC):
----------------------------------------------------------------------
ENB CONFIG for instance 0:

	eNB name:           	eNB_Eurecom_LTEBox:
	eNB ID:             	3584:
	Cell type:          	CELL_MACRO_ENB:
	TAC:                	1:
	MCC:                	208:
	MNC:                	93:
	eutra band for CC 0:         	5:
	downlink freq for CC 0:      	881500000:
	uplink freq offset for CC 0: 	-45000000:

	Cell ID for CC 0:	0:
	N_RB_DL for CC 0:	6:
	nb_antennas_tx for CC 0:	1:
	nb_antennas_rx for CC 0:	1:
	rach_numberOfRA_Preambles for CC 0:	15:
	rach_preamblesGroupAConfig for CC 0:	0:
	rach_powerRampingStep for CC 0:	2:
	rach_preambleInitialReceivedTargetPower for CC 0:	6:
	rach_preambleTransMax for CC 0:	6:
	rach_raResponseWindowSize for CC 0:	7:
	rach_macContentionResolutionTimer for CC 0:	5:
	rach_maxHARQ_Msg3Tx for CC 0:	5:
	bcch_modificationPeriodCoeff for CC 0:	0:
	pcch_defaultPagingCycle for CC 0:	2:
	pcch_nB for CC 0:	2:
	prach_root for CC 0:	0:
	prach_config_index for CC 0:	0:
	prach_high_speed for CC 0:	0:
	prach_zero_correlation for CC 0:	1:
	prach_freq_offset for CC 0:	2:
	pdsch_referenceSignalPower for CC 0:	-45:
	pdsch_p_b for CC 0:	0:
	pusch_n_SB for CC 0:	1:
	pusch_hoppingMode for CC 0:	0:
	pusch_hoppingOffset for CC 0:	0:
	pusch_enable64QAM for CC 0:	0:
	pusch_groupHoppingEnabled for CC 0:	1:
	pusch_groupAssignment for CC 0:	0:
	pusch_sequenceHoppingEnabled for CC 0:	0:
	pusch_nDMRS1 for CC 0:	1:
	pucch_delta_shift for CC 0:	0:
	pucch_nRB_CQI for CC 0:	1:
	pucch_nCS_AN for CC 0:	0:
	srs_enable for CC 0:	0:
	pusch_p0_Nominal for CC 0:	-60:
	pucch_p0_Nominal for CC 0:	-96:
	pusch_alpha for CC 0:	7:
	pucch_deltaF_Format1 for CC 0:	2:
	pucch_deltaF_Format1b for CC 0:	1:
	pucch_deltaF_Format2 for CC 0:	1:
	pucch_deltaF_Format2a for CC 0:	1:
	pucch_deltaF_Format2b for CC 0:	1:
	msg3_delta_Preamble for CC 0:	6:
	ul_CyclicPrefixLength for CC 0:	0:
	ue_TimersAndConstants_t300 for CC 0:	5:
	ue_TimersAndConstants_t301 for CC 0:	5:
	ue_TimersAndConstants_t310 for CC 0:	5:
	ue_TimersAndConstants_n310 for CC 0:	7:
	ue_TimersAndConstants_t311 for CC 0:	3:
	ue_TimersAndConstants_n311 for CC 0:	0:

	Global log level:  	debug
	HW log level:      	error
	PHY log level:     	info
	MAC log level:     	error
	RLC log level:     	error
	PDCP log level:    	error
	RRC log level:     	error
	UDP log level:     	info
	GTP log level:     	info
	OSA log level:     	info

--------------------------------------------------------
Downlink frequency/ uplink offset of CC_id 0 set to 881500000/-45000000
configuring for eNB
CPU Freq is 3.408197 
reported resolution = 1 ns
[PHY][I]Initializing frame parms for N_RB_DL 6, Ncp 0, osf 1
lte_parms.c: Setting N_RB_DL to 6, ofdm_symbol_size 128
[PHY][I][eNB 0] Initializing DL_FRAME_PARMS : N_RB_DL 6, PHICH Resource 1, PHICH Duration 0
pcfich_reg : 0,3,6,9
Ngroup_PHICH 1 (phich_config_common.phich_resource 1,phich_config_common.phich_duration normal, NidCell 0,Ncp 0, frame_type 0), smallest pcfich REG 0, n0 8, n1 18 (first PHICH REG 0)
phich_reg :0 => 1,4,8
[PHY][I]init eNB: Nid_cell 0
[PHY][I]init eNB: frame_type 0,tdd_config 3
[PHY][I]init eNB: number of ue max 10 number of enb max 1 number of harq pid max 8
[PHY][I]init eNB: N_RB_DL 6
[PHY][I]init eNB: Transmission mode 1
CPU Freq is 3.408190 
frame_parms->N_RB_DL=6
frame_parms->N_RB_UL=6
frame_parms->Nid_cell=0
frame_parms->Ncp=0
frame_parms->Ncp_UL=0
frame_parms->nushift=0
frame_parms->frame_type=0
frame_parms->tdd_config=3
frame_parms->tdd_config_S=0
frame_parms->mode1_flag=1
frame_parms->nb_antennas_tx=1
frame_parms->nb_antennas_rx=1
frame_parms->ofdm_symbol_size=128
frame_parms->nb_prefix_samples=9
frame_parms->nb_prefix_samples0=10
frame_parms->first_carrier_offset=92
frame_parms->samples_per_tti=1920
frame_parms->symbols_per_tti=14
HW: Configuring card 0, nb_antennas_tx/rx 1/1
Card 0, channel 0, Setting tx_gain 0.000000, rx_gain 0.000000, tx_freq 881500000.000000, rx_freq 836500000.000000
Card 0, channel 1, Setting tx_gain 0.000000, rx_gain 0.000000, tx_freq 881500000.000000, rx_freq 836500000.000000
Card 0, channel 2, Setting tx_gain 0.000000, rx_gain 0.000000, tx_freq 881500000.000000, rx_freq 836500000.000000
Card 0, channel 3, Setting tx_gain 0.000000, rx_gain 0.000000, tx_freq 881500000.000000, rx_freq 836500000.000000
Checking for USRPs : UHD 003.009.004-release (3.9.4)
Found USRP B200-- Detected Device: B210
-- Operating over USB 3.
-- Detecting internal GPSDO.... Found an internal GPSDO
-- Initialize CODEC control...
-- Initialize Radio control...
-- Performing register loopback test... pass
-- Performing register loopback test... pass
-- Performing CODEC loopback test... pass
-- Performing CODEC loopback test... pass
-- Asking for clock rate 16.000000 MHz... 
-- Actually got clock rate 16.000000 MHz.
-- Performing timer loopback test... pass
-- Performing timer loopback test... pass
-- Setting master clock rate selection to 'automatic'.
-- Asking for clock rate 30.720000 MHz... 
-- Actually got clock rate 30.720000 MHz.
-- Performing timer loopback test... pass
-- Performing timer loopback test... pass
Setting rx freq/gain on channel 0/2 : BW 1.250000 (readback 1.250000)
cal 0: freq 3500000000.000000, offset 44.000000, diff 2663500000.000000
cal 1: freq 2660000000.000000, offset 49.000000, diff 1823500000.000000
cal 2: freq 2300000000.000000, offset 50.000000, diff 1463500000.000000
cal 3: freq 1880000000.000000, offset 53.000000, diff 1043500000.000000
cal 4: freq 816000000.000000, offset 58.000000, diff 20500000.000000
RX Gain 0 80.000000 (58.000000) => 22.000000 (max 76.000000)
Setting tx freq/gain on channel 0/2: BW 1.250000 (readback 1.250000)
Actual master clock: 30.720000MHz...
rx_max_num_samps 2044
tx_max_num_samps 2044
RX Channel 0
Actual RX sample rate: 1.920000MSps...
Actual RX frequency: 0.836500GHz...
Actual RX gain: 22.000000...
Actual RX bandwidth: 1.250000M...
Actual RX antenna: RX2...
TX Channel 0

Actual TX sample rate: 1.920000MSps...
Actual TX frequency: 0.881500GHz...
Actual TX gain: 75.000000...
Actual TX bandwidth: 1.250000M...
Actual TX antenna: TX/RX...
Device timestamp: 0.000239...
[BBU] has loaded USRP B200 device.
openair0_device_init returns 0
Done
[SCTP][I][sctp_eNB_task] Starting SCTP layer
[S1AP][I][s1ap_eNB_task] Starting S1AP layer
[UDP][I]Initializing UDP task interface
[UDP][I]Initializing UDP task interface: DONE
[GTPV1U][I]Initializing GTPU stack 0xe9d440
ITTI tasks created
setup_eNB_buffers: frame_parms = 0x7f976742c8e0
rxdata[0] @ 0x1631be80 (0x1631be80) (N_TA_OFFSET 0)
txdata[0] @ 0x162f79c0
Setting eNB buffer to all-RX
[UDP][I]Initializing UDP for local address 192.170.1.2 with port 2152
[UDP][I]Inserting new descriptor for task 11, sd 45
[UDP][I]Initializing UDP for local address 192.170.1.2 with port 2152: DONE
Wait for the ITTI initialize message
[S1AP][I][s1ap_eNB_handle_register_eNB] Registered new eNB[0] and macro eNB id 3584
[SCTP][I][sctp_handle_new_association_req] sctp_bindx SCTP_BINDX_ADD_ADDR socket bound to : 192.170.0.2
[SCTP][I][sctp_handle_new_association_req] Converted ipv4 address 192.170.0.1 to network type
[SCTP][I][sctp_handle_new_association_req] connectx assoc_id  15 in progress..., used 1 addresses
[SCTP][I][sctp_handle_new_association_req] Inserted new descriptor for sd 47 in list, nb elements 1, assoc_id 15
[SCTP][I][sctp_eNB_flush_sockets] Found data for descriptor 47
[SCTP][I][sctp_eNB_read_from_socket] Received notification for sd 47, type 32769
[SCTP][I][sctp_eNB_read_from_socket] Client association changed: 0
[SCTP][I][sctp_get_peeraddresses] ----------------------
[SCTP][I][sctp_get_peeraddresses] Peer addresses:
[SCTP][I][sctp_get_peeraddresses]     - [192.170.0.1]
[SCTP][I][sctp_get_peeraddresses] ----------------------
[SCTP][I][sctp_get_sockinfo] ----------------------
[SCTP][I][sctp_get_sockinfo] SCTP Status:
[SCTP][I][sctp_get_sockinfo] assoc id .....: 15
[SCTP][I][sctp_get_sockinfo] state ........: 4
[SCTP][I][sctp_get_sockinfo] instrms ......: 2
[SCTP][I][sctp_get_sockinfo] outstrms .....: 2
[SCTP][I][sctp_get_sockinfo] fragmentation : 65487
[SCTP][I][sctp_get_sockinfo] pending data .: 0
[SCTP][I][sctp_get_sockinfo] unack data ...: 0
[SCTP][I][sctp_get_sockinfo] rwnd .........: 106496
[SCTP][I][sctp_get_sockinfo] peer info     :
[SCTP][I][sctp_get_sockinfo]     state ....: 2
[SCTP][I][sctp_get_sockinfo]     cwnd .....: 131070
[SCTP][I][sctp_get_sockinfo]     srtt .....: 0
[SCTP][I][sctp_get_sockinfo]     rto ......: 3000
[SCTP][I][sctp_get_sockinfo]     mtu ......: 65535
[SCTP][I][sctp_get_sockinfo] ----------------------
[SCTP][I][sctp_eNB_read_from_socket] Comm up notified for sd 47, assigned assoc_id 15
[S1AP][I][s1ap_eNB_generate_s1_setup_request] 3584 -> 00e000
[SCTP][I][sctp_send_data] Successfully sent 59 bytes on stream 0 for assoc_id 15
[SCTP][I][sctp_eNB_flush_sockets] Found data for descriptor 47
[SCTP][I][sctp_eNB_read_from_socket] Received notification for sd 47, type 32777
[SCTP][I][sctp_eNB_flush_sockets] Found data for descriptor 47
[SCTP][I][sctp_eNB_read_from_socket] [15][47] Msg of length 27 received from port 36412, on stream 0, PPID 18
[S1AP][I][s1ap_decode_s1ap_s1setupresponseies] Decoding message S1ap_S1SetupResponseIEs (/home/iii/openairinterface5g/cmake_targets/lte_build_oai/build/CMakeFiles/R10.5/s1ap_decoder.c:3544)
[S1AP][I][s1ap_eNB_handle_s1_setup_response] servedGUMMEIs.list.count 1
[S1AP][I][s1ap_eNB_handle_s1_setup_response] servedPLMNs.list.count 1
[ENB_APP][I][eNB_app_task] [eNB 0] Received S1AP_REGISTER_ENB_CNF: associated MME 1
Scope thread has priority 2
Scope thread created, ret=0
Setting eNB_thread FIFO scheduling policy with priority 99 
Setting OS scheduler to SCHED_FIFO for eNB [cc0][thread0] 
Setting OS scheduler to SCHED_FIFO for eNB [cc0][thread1] 
Setting OS scheduler to SCHED_FIFO for eNB [cc0][thread2] 
Setting OS scheduler to SCHED_FIFO for eNB [cc0][thread3] 
Setting OS scheduler to SCHED_FIFO for eNB [cc0][thread4] 
Setting OS scheduler to SCHED_FIFO for eNB [cc0][thread5] 
Setting OS scheduler to SCHED_FIFO for eNB [cc0][thread6] 
Setting OS scheduler to SCHED_FIFO for eNB [cc0][thread7] 
Setting OS scheduler to SCHED_FIFO for eNB [cc0][thread8] 
Setting OS scheduler to SCHED_FIFO for eNB [cc0][thread9] 
Creating main eNB_thread 
[SCHED][eNB] Started eNB main thread on CPU 0 TID 4889
eNB_thread: mlockall in ...
eNB_thread: mlockall out ...
waiting for sync (eNB_thread)
Sending sync to all threads
TYPE <CTRL-C> TO TERMINATE
Entering ITTI signals handler
got sync (eNB_thread)
LULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULLULLULLULLULLULLULLULLULLULLULLULLULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULLULLULLULLULLULLULLULLULLULLULLULLULLULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULLULLULLULLULLULLULLULLULLULLULLULLULLULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULLULLULLULLULLULLULLULLULLULLULLULLULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULLULLULLULLULLULLULLULLULLULLULLULLULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULLULLULLULLULLULLULLULLULLULLULLULLULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULLULLULLULLULLULLULLULLULLULLULLULLULLULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULLULLULLULLULLULLULLULLULLULLULLULLULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULLULLULLULLULLULLULLULLULLULLULLULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULLULLULLULLULLULLULLULLULLULLULLULLULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULLULLULLULLULLULLULLULLULLULLULLULLULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULLULLULLULLULLULLULLULLULLULLULLULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULLULLULLULLULLULLULLULLULLULLULLULLULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULLULLULLULLULLULLULLULLULLULLULLULLULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULLULLULLULLULLULLULLULLULLULLULLULLULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULLULLULLULLULLULLULLULLULLULLULLULLULLULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULLULLULLULLULLULLULLULLULLULLULLULLULLULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULLULLULLULLULLULLULLULLULLULLULLULLULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULLULLULLULLULLULLULLULLULLULLULLULLULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULLULLULLULLULLULLULLULLULLULLULLULLULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULLULLULLULLULLULLULLULLULLULLULLULLULULLULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULLULLULLULLULLULLULLULLULLULLULLULLULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULLULLULLULLULLULLULLULLULLULLULLULLULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULLULLULLULLULLULLULLULLULLULLULLULLULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULULLULLULLULLULLULLULLULLULLULLULLULLULULULULULULULULULULULUL

**Comment by mbr0wn** [comment]
@davidyu1 This seems more like an OAI issue. I would recommend posting on their mailing list.
