### ISSUE TITLE
UHD version is incorrect

### ISSUE THREAD

**Issue by mmaroti** [EttusResearch/uhd#649]
## Issue Description ##
When building the UHD host library with `mkdir build && cd build && cmake ..`, then the UHD version information is correctly set and reported in the `uhd_config_info`. However, if you do another `cmake ..` in the build directory, either before or after `make`, then the UHD version is lost, and no version will be reported in `uhd_config_info`.

## Setup Details ##
- Get the latest (or any other version).
- cd uhd/host
- mkdir build
- cd build
- cmake ..
- cmake ..
- make

## Expected Behavior ##
After the second `cmake ..` step the version string should stay the same.

## Actual Behaviour ##
After the first `cmake ..` I get `-- Building version: 4.3.0.0-0-g1f8fd345`. But after the second one I get `-- Building version:`. Also the reported version will be missing in `uhd_version_info`. This causes GNURadio to disable RFNoC components.

**Comment by mbr0wn** [comment]
Hey @mmaroti, thanks for submitting. FYI we had already fixed this on 38726c1c967f553a10cc8d2a3d721a51cbb04a46 a while ago. I ran into the exact same issue  :/
