### ISSUE TITLE
rpc::timeout: Timeout 2000ms when using UHD Python API

### ISSUE THREAD

**Issue by LawsonGu** [EttusResearch/uhd#653]
## Issue Description ##
When I was using UHD Python API
`import uhd`
`usrp = uhd.usrp.MultiUSRP("addr=192.168.9.2")`
This issue happened

## Setup Details ##
Ubuntu: 20.04
UHD: 4.2
Python: 3.8

## Expected Behavior ##
![image](https://user-images.githubusercontent.com/101655210/210944461-4c6911fd-2642-41f1-8bba-c31b7468cb7f.png)

## Actual Behaviour ##
![image](https://user-images.githubusercontent.com/101655210/210944489-cb0adcdd-cfac-4c10-afff-2cc812802ba1.png)

## Steps to reproduce the problem ##
Before you reproduce, please confirm your $home/.bashrc. It should be like this.
![image](https://user-images.githubusercontent.com/101655210/210944590-63faf774-b189-47c2-ab5f-5856d321fd24.png)

## Additional Information ##
After I change $home/.bashrc file like below, issue disappear and expected behavior goes well.
![image](https://user-images.githubusercontent.com/101655210/210944700-2b69b03e-1292-4728-ad8d-860b91038bea.png)

Maybe the question is: 
If $PYTHONPATH contains 
`/python3/dist-packages`
seems UHD Python API could not use normally in this case?

**Comment by wordimont** [comment]
It looks like get_num_xbars was removed when UHD 4.0 was released. Notice in your actual output the UHD version printed is 3.15, which probably doesn't match your device. Perhaps you have remnants from multiple UHD versions on your system and changing your PYTHONPATH is affecting which one is being used.

**Comment by mbr0wn** [comment]
In your logs, you are mixing UHD versions. I expect if you update your devices, you're good to go.
