### ISSUE TITLE
Possibility of RFNoC on the Zedboard platform ?? 

### ISSUE THREAD

**Issue by hacene182** [EttusResearch/uhd#66]
Hello ; 
Is there any way to use the RFNoC architecture in a Zedboard platform, which contains the same Zynq as the USRP E310; and test the RFNoC blocks ( No radio blocks; just loop-back chains) , using Gnu Radio installed on the ARM Side or in a Host Side. ( educational purpose) 

Thank you.

**Comment by mbr0wn** [comment]
RFNoC is open source and you can port it wherever you like (within the confines of the GPL). Have fun!
