### ISSUE TITLE
TwinRx GPIO Init Sleep Too Short?

### ISSUE THREAD

**Issue by johnwstanford** [EttusResearch/uhd#682]
If the underlying function rounds to microsecond precision, wouldn't 166ns round down to zero?  In which case the sleep call would do nothing?

https://github.com/EttusResearch/uhd/blob/0e50a37b5ec6039ed4e8947421dd333047e24408/host/lib/usrp/dboard/twinrx/twinrx_io.hpp#L123

**Comment by mbr0wn** [comment]
No, because we have a minimum sleep duration of 1us:

https://github.com/EttusResearch/uhd/blob/master/host/lib/usrp/dboard_iface.cpp#L24-L30
