### ISSUE TITLE
ADF5356_MAX_FRAC2 too big for a uint16_t

### ISSUE THREAD

**Issue by johnwstanford** [EttusResearch/uhd#684]
If `ADF5356_MAX_FRAC2` wins this comparison, then I don't think it'll fit into the `uint16_t` that we're casting it into.  Its value is 268435455 and log2(268435455) = 28.

https://github.com/EttusResearch/uhd/blob/0e50a37b5ec6039ed4e8947421dd333047e24408/host/lib/include/uhdlib/usrp/common/adf535x.hpp#L569C60-L569C77

**Comment by mbr0wn** [comment]
You're right. This is copy/pasta from ADF5355.
