### ISSUE TITLE
Feature Request/Question: Overclocking the AD9364 for wider bandwidth

### ISSUE THREAD

**Issue by Martyx00** [EttusResearch/uhd#685]
Is there a plan for USRP product line to do something like Nuand did with bladeRF to overtclock the AD9364 to achcieve wider bandwidth (for exmaple to hear the whole Bluetooth spectrum)? If not, is there a reason (such as potential damage) that youre not considereing it and would discourage others from doing so?

Refs: 
* https://destevez.net/2023/02/running-the-ad9361-at-122-88-msps/
* https://www.nuand.com/2023-02-release-122-88mhz-bandwidth/

**Comment by mbr0wn** [comment]
We have decided to not implement this, mainly because even with bypassing interpolators, the analog response is not that great outside the intended bandwidth, and the recommendation of ADI to not do this.
