### ISSUE TITLE
Should `_fb_after_divider` be a `bool`?

### ISSUE THREAD

**Issue by johnwstanford** [EttusResearch/uhd#686]
It looks like `_fb_after_divider` is initialized and used as a `bool`, but declared here as a `double`.  Should it be declared as a `bool`?

https://github.com/EttusResearch/uhd/blob/0e50a37b5ec6039ed4e8947421dd333047e24408/host/lib/include/uhdlib/usrp/common/adf435x.hpp#L558C12-L558C29

**Comment by mbr0wn** [comment]
It should, and as it happens, this was fixed as part of d80d56114a5eb15b84.
