### ISSUE TITLE
Register 6 or 10 in ADF5355 Freq Update?

### ISSUE THREAD

**Issue by johnwstanford** [EttusResearch/uhd#687]
The datasheet I have for the ADF5355 says register 10 should be the first one updated during a frequency update sequence, but this looks like it's updating 6 first and never updating 10 at all.  I'm looking at page 34 of Rev D. of the ADF5355 datasheet.

https://github.com/EttusResearch/uhd/blob/0e50a37b5ec6039ed4e8947421dd333047e24408/host/lib/include/uhdlib/usrp/common/adf535x.hpp#L489

**Comment by mbr0wn** [comment]
You're right that it doesn't match the data sheet. But unless we get complaints about buggy tuning behaviour on TwinRX, we won't touch this. Changing it would change the timing behaviour, which is critical.
