### ISSUE TITLE
Does anyone have version 3.13.0.3 rc for Windows. Come, it is not possible to collect.

### ISSUE THREAD

**Issue by Andryiv1982** [EttusResearch/uhd#688]

**Comment by manderseck** [comment]
@Andryiv1982 It's not quite clear what you are looking for. The 3.13 release is accessible via the corresponding tag: https://github.com/EttusResearch/uhd/tree/UHD-3.13
Together with the build instructions you should be able to install this in Windows, although later versions are recommended. I'm closing this but you may feel free to re-open this issue if that didn't help you and if you can provide more information.
