### ISSUE TITLE
Building UHD on Raspberry PI 3B+

### ISSUE THREAD

**Issue by Haider037** [EttusResearch/uhd#696]
## Issue Description ##

I am building a UHD driver on a raspberry pi 3 B+ Model. When doing sudo make install it says "Building CXX object python/CmakeFiles/pyuhd.dir/pyuhd.cpp.o Then it says: c++: fatal error: killed signal terminated program cc1plus compilation terminated. make[2]: *** [python/cmakefiles/pyuhd.dir/build.make:82: python/Cmakefiles/pyuhd.dir/pyuhd.cpp.o] error 1 make[1]: *** [cmakefiles/makefiles2:5431: python/cmakefiles/pyuhd.dir/all] error2 make: *** [Makefile:182: all] Error 2

**Comment by Haider037** [comment]
The last thing it says during the make process before the error comes up is
"[ 98%] Building CXX object python/CMakeFiles/pyuhd.dir/pyuhd.cpp.o"
And it stays at that stage for a long time before it exits the code with the error mentioned above.

**Comment by NI-LAm** [comment]
@Haider037 Could please provide some more details, like:
* What Distrubution is installed on the RasPi?
* Which uhd Version are you trying to build?
* What cmake command did you use for configuration?

Please also post full logs of the configure and build process.

**Comment by Haider037** [comment]
1) Raspberry Pi OS (Raspbian)
2) Version 4.0.0
3) cmake -DCMAKE_CXX_FLAGS:STRING="-march=armv7ve -mfloat-abi=hard -mfpu=neon-vfpv4 -mtune=cortex-a53 -Wno-psabi" -DCMAKE_C_FLAGS:STRING="-march=armv7ve -mfloat-abi=hard -mfpu=neon-vfpv4 -mtune=cortex-a53 -Wno-psabi" -DCMAKE_ASM_FLAGS:STRING="-march=armv7ve -mfloat-abi=hard -mfpu=neon-vfpv4 -mtune=cortex-a53 -g" ../

The tags are on my raspberry pi and I am currently on my MacI have to run the cmake line above and it's taking a while, so I will try and post It on here if I get it working. But I am pretty sure all the builds pass until it gets to 98% like stated above.

**Comment by Haider037** [comment]
Here are the tags 
After running this command: cmake -DCMAKE_CXX_FLAGS:STRING="-march=armv7ve -mfloat-abi=hard -mfpu=neon-vfpv4 -mtune=cortex-a53 -Wno-psabi" -DCMAKE_C_FLAGS:STRING="-march=armv7ve -mfloat-abi=hard -mfpu=neon-vfpv4 -mtune=cortex-a53 -Wno-psabi" -DCMAKE_ASM_FLAGS:STRING="-march=armv7ve -mfloat-abi=hard -mfpu=neon-vfpv4 -mtune=cortex-a53 -g" ../

...@raspberrypi:~/uhd/host/build $ cmake -DCMAKE_CXX_FLAGS:STRING="-march=armv7ve -mfloat-abi=hard -mfpu=neon-vfpv4 -mtune=cortex-a53 -Wno-psabi" -DCMAKE_C_FLAGS:STRING="-march=armv7ve -mfloat-abi=hard -mfpu=neon-vfpv4 -mtune=cortex-a53 -Wno-psabi" -DCMAKE_ASM_FLAGS:STRING="-march=armv7ve -mfloat-abi=hard -mfpu=neon-vfpv4 -mtune=cortex-a53 -g" ../
--
-- Configuring the Python interpreter...
-- Manually determining build Python version...
-- Python interpreter: /usr/bin/python3.9 Version: 3.9.2
-- Override with: -DPYTHON_EXECUTABLE=<path-to-python>
-- Manually determining runtime Python version...
-- Python runtime interpreter: /usr/bin/python3.9 Version: 3.9.2
-- Override with: -DRUNTIME_PYTHON_EXECUTABLE=<path-to-python>
-- Finding Python Libraries...
-- Python Libraries: /usr/lib/arm-linux-gnueabihf/libpython3.9.so
-- Python include directories: /usr/include/python3.9
-- Operating on master branch.
-- Using UHD Images Directory: /usr/local/share/uhd/images
-- Build type not specified: defaulting to release.
--
-- Configuring Boost C++ Libraries...
--
-- Checking for Boost version 1.65 or greater
--   Looking for required Boost components...
--   Enabling Boost Error Code Header Only
--     Disabling boost::asio use of std::string_view
--   Boost version: 1.74.0
--   Boost include directories: /usr/include
--   Boost library directories: /usr/lib/arm-linux-gnueabihf
--   Boost libraries: Boost::chrono;Boost::date_time;Boost::filesystem;Boost::program_options;Boost::serialization;Boost::thread;Boost::unit_test_framework;Boost::system
-- Looking for Boost version 1.65 or greater - found
--
-- Python checking for compatible Python version
-- Python checking for compatible Python version - 3.9.2 satisifes minimum required version 3.6
--
-- Python checking for Mako templates module
-- Python checking for Mako templates module - 1.1.3 satisifes minimum required version 0.4.2
--
-- Python checking for requests module
-- Python checking for requests module - 2.25.1 satisifes minimum required version 2.0
--
-- Python checking for numpy module
-- Python checking for numpy module - 1.19.5 satisifes minimum required version 1.11
--
-- Python checking for ruamel.yaml module
-- Python checking for ruamel.yaml module - "import ruamel.yaml" failed (is it installed?)
--
-- Configuring LibUHD support...
--   Dependency Boost_FOUND = TRUE
--   Dependency HAVE_PYTHON_MODULE_MAKO = TRUE
--   Enabling LibUHD support.
--   Override with -DENABLE_LIBUHD=ON/OFF
--
-- Configuring LibUHD - C API support...
--   Dependency ENABLE_LIBUHD = ON
--   Enabling LibUHD - C API support.
--   Override with -DENABLE_C_API=ON/OFF
--
-- Configuring LibUHD - Python API support...
--   Dependency ENABLE_LIBUHD = ON
--   Dependency HAVE_PYTHON_MODULE_NUMPY = TRUE
--   Dependency HAVE_PYTHON_LIBS = TRUE
--   Enabling LibUHD - Python API support.
--   Override with -DENABLE_PYTHON_API=ON/OFF
--
-- Configuring Examples support...
--   Dependency ENABLE_LIBUHD = ON
--   Enabling Examples support.
--   Override with -DENABLE_EXAMPLES=ON/OFF
--
-- Configuring Utils support...
--   Dependency ENABLE_LIBUHD = ON
--   Enabling Utils support.
--   Override with -DENABLE_UTILS=ON/OFF
--
-- Configuring Tests support...
--   Dependency ENABLE_LIBUHD = ON
--   Enabling Tests support.
--   Override with -DENABLE_TESTS=ON/OFF
--
-- Could NOT find DPDK (missing: DPDK_INCLUDE_DIRS DPDK_LIBRARIES) (Required is at least version "18.11...21.11")
--
-- Configuring USB support...
--   Dependency ENABLE_LIBUHD = ON
--   Dependency LIBUSB_FOUND = TRUE
--   Enabling USB support.
--   Override with -DENABLE_USB=ON/OFF
--
-- Configuring B100 support...
--   Dependency ENABLE_LIBUHD = ON
--   Dependency ENABLE_USB = ON
--   Enabling B100 support.
--   Override with -DENABLE_B100=ON/OFF
--
-- Configuring B200 support...
--   Dependency ENABLE_LIBUHD = ON
--   Dependency ENABLE_USB = ON
--   Enabling B200 support.
--   Override with -DENABLE_B200=ON/OFF
--
-- Configuring USRP1 support...
--   Dependency ENABLE_LIBUHD = ON
--   Dependency ENABLE_USB = ON
--   Enabling USRP1 support.
--   Override with -DENABLE_USRP1=ON/OFF
--
-- Configuring USRP2 support...
--   Dependency ENABLE_LIBUHD = ON
--   Enabling USRP2 support.
--   Override with -DENABLE_USRP2=ON/OFF
--
-- Configuring X300 support...
--   Dependency ENABLE_LIBUHD = ON
--   Enabling X300 support.
--   Override with -DENABLE_X300=ON/OFF
--
-- Configuring MPMD support...
--   Dependency ENABLE_LIBUHD = ON
--   Enabling MPMD support.
--   Override with -DENABLE_MPMD=ON/OFF
--
-- Configuring SIM support...
--   Dependency ENABLE_LIBUHD = ON
--   Dependency ENABLE_MPMD = ON
--   Dependency ENABLE_PYTHON_API = ON
--   Enabling SIM support.
--   Override with -DENABLE_SIM=ON/OFF
--
-- Configuring N300 support...
--   Dependency ENABLE_LIBUHD = ON
--   Dependency ENABLE_MPMD = ON
--   Enabling N300 support.
--   Override with -DENABLE_N300=ON/OFF
--
-- Configuring N320 support...
--   Dependency ENABLE_LIBUHD = ON
--   Dependency ENABLE_MPMD = ON
--   Enabling N320 support.
--   Override with -DENABLE_N320=ON/OFF
--
-- Configuring E320 support...
--   Dependency ENABLE_LIBUHD = ON
--   Dependency ENABLE_MPMD = ON
--   Enabling E320 support.
--   Override with -DENABLE_E320=ON/OFF
--
-- Configuring E300 support...
--   Dependency ENABLE_LIBUHD = ON
--   Dependency ENABLE_MPMD = ON
--   Enabling E300 support.
--   Override with -DENABLE_E300=ON/OFF
--
-- Configuring X400 support...
--   Dependency ENABLE_LIBUHD = ON
--   Dependency ENABLE_MPMD = ON
--   Enabling X400 support.
--   Override with -DENABLE_X400=ON/OFF
--
-- Configuring OctoClock support...
--   Dependency ENABLE_LIBUHD = ON
--   Enabling OctoClock support.
--   Override with -DENABLE_OCTOCLOCK=ON/OFF
--
-- Configuring DPDK support...
--   Dependency ENABLE_MPMD = ON
--   Dependency DPDK_FOUND = FALSE
--   Disabling DPDK support.
--   Override with -DENABLE_DPDK=ON/OFF
--
--
-- Configuring priority scheduling...
--   Priority scheduling supported through pthread_setschedparam.
--   Setting thread names is supported through pthread_setname_np.
--   Setting thread affinity is supported through pthread_setaffinity_np.
--
-- Configuring module loading...
--   Module loading supported through dlopen.
--
-- Configuring atomics support...
--   Atomics support is built-in, no linking required.
--
-- Processing NI-RIO FPGA LVBITX Bitstreams...
--   Using x300.lvbitx_base for codegen
--   Using x310.lvbitx_base for codegen
--
-- USB support enabled via libusb.
--
-- Configuring interface address discovery...
--   Interface address discovery supported through getifaddrs.
--
-- Loading build info.
-- Could NOT find Curses (missing: CURSES_LIBRARY CURSES_INCLUDE_PATH)
--
-- Adding B2XX device test target
-- Adding X3x0 device test target
-- Adding E3XX device test target
-- Adding N3XX device test target
-- Adding E32x device test target
-- Adding X4x0 device test target
--
-- Could NOT find Curses (missing: CURSES_LIBRARY CURSES_INCLUDE_PATH)
--
-- Configuring Manual support...
--   Dependency DOXYGEN_FOUND = YES
--   Enabling Manual support.
--   Override with -DENABLE_MANUAL=ON/OFF
--
-- Configuring API/Doxygen support...
--   Dependency DOXYGEN_FOUND = YES
--   Enabling API/Doxygen support.
--   Override with -DENABLE_DOXYGEN=ON/OFF
--
-- Found GZip: /usr/bin/gzip
--
-- Compressed Man Pages enabled
--   Override with -DENABLE_MAN_PAGE_COMPRESSION=ON/OFF
--
-- Configuring Man Pages support...
--   Dependency NOT_WIN32 = TRUE
--   Dependency GZIP_FOUND = TRUE
--   Enabling Man Pages support.
--   Override with -DENABLE_MAN_PAGES=ON/OFF
--
-- Python checking for virtual environment
-- Python checking for virtual environment - "assert sys.prefix != sys.base_prefix" failed
--
-- Python checking for gevent module
-- Python checking for gevent module - "import gevent" failed (is it installed?)
--
-- Python checking for mprpc module
-- Python checking for mprpc module - "import mprpc" failed (is it installed?)
--
-- Python checking for pyudev module
-- Python checking for pyudev module - "import pyudev" failed (is it installed?)
--
-- Python checking for pyroute2 module
-- Python checking for pyroute2 module - "import pyroute2" failed (is it installed?)
-- MPM unit test Python package prerequisites not met; skipping
--
-- Utilizing the python install directory: /usr/local/lib/python3.9/site-packages
--
-- ######################################################
-- # UHD enabled components                              
-- ######################################################
--   * LibUHD
--   * LibUHD - C API
--   * LibUHD - Python API
--   * Examples
--   * Utils
--   * Tests
--   * USB
--   * B100
--   * B200
--   * USRP1
--   * USRP2
--   * X300
--   * MPMD
--   * SIM
--   * N300
--   * N320
--   * E320
--   * E300
--   * X400
--   * OctoClock
--   * Manual
--   * API/Doxygen
--   * Man Pages
--
-- ######################################################
-- # UHD disabled components                            
-- ######################################################
--   * DPDK
--
-- ******************************************************
-- * You are building the UHD development master branch.
-- * For production code, we recommend our stable,
-- * releases or using the release branch (maint).
-- ******************************************************
-- Building version: 4.4.0.0-265-ga2a04e31
-- Using install prefix: /usr/local
-- Configuring done
-- Generating done
-- Build files have been written to: /home/.../uhd/host/build


After running sudo make:

...@raspberrypi:~/uhd/host/build $ sudo make
[  1%] Built target uhd_rpclib
[  4%] Built target uhd-resources
[ 50%] Built target uhd
[ 50%] Built target tx_timed_samples
[ 51%] Built target network_relay
[ 51%] Built target tx_bursts
[ 51%] Built target test_messages
[ 51%] Built target spi
[ 51%] Built target rx_samples_to_udp
[ 51%] Built target benchmark_rate
[ 51%] Built target rfnoc_nullsource_ce_rx
[ 51%] Built target tx_samples_from_file
[ 51%] Built target sync_to_gps
[ 51%] Built target tx_waveforms
[ 51%] Built target txrx_loopback_to_file
[ 51%] Built target test_pps_input
[ 51%] Built target usrp_list_sensors
[ 52%] Built target test_timed_commands
[ 52%] Built target latency_test
[ 53%] Built target gpio
[ 53%] Built target rfnoc_rx_to_file
[ 53%] Built target rfnoc_radio_loopback
[ 53%] Built target test_clock_synch
[ 53%] Built target rx_timed_samples
[ 53%] Built target getopt
[ 53%] Built target tx_samples_c
[ 54%] Built target test_dboard_coercion
[ 54%] Built target rx_samples_to_file
[ 54%] Built target rx_samples_c
[ 55%] Built target rfnoc_replay_samples_from_file
[ 56%] Built target rx_multi_samples
[ 56%] Built target uhd_test
[ 56%] Built target rf_control_gain_profile_test
[ 56%] Built target discoverable_feature_test
[ 57%] Built target pwr_cal_mgr_test
[ 58%] Built target offload_io_srv_test
[ 59%] Built target xport_adapter_ctrl_test
[ 59%] Built target mb_controller_test
[ 62%] Built target ferrum_radio_block_test
[ 63%] Built target split_stream_block_test
[ 64%] Built target module_test
[ 64%] Built target siggen_block_test
[ 64%] Built target null_block_test
[ 64%] Built target logpwr_block_test
[ 65%] Built target keep_one_in_n_test
[ 65%] Built target fosphor_block_test
[ 65%] Built target switchboard_block_test
[ 65%] Built target duc_block_test
[ 66%] Built target ddc_block_test
[ 67%] Built target addsub_block_test
[ 68%] Built target lmx2572_test
[ 69%] Built target sensors_test
[ 69%] Built target vector_iir_block_test
[ 69%] Built target narrow_cast_test
[ 69%] Built target constrained_device_args_test
[ 69%] Built target string_vector_c_test
[ 69%] Built target interpolation_test
[ 69%] Built target scope_exit_test
[ 69%] Built target gain_group_test
[ 69%] Built target x400_rfdc_control_test
[ 70%] Built target tx_streamer_test
[ 70%] Built target paths_test
[ 71%] Built target fp_compare_epsilon_test
[ 71%] Built target rfnoc_propprop_test
[ 71%] Built target error_test
[ 72%] Built target zbx_cpld_test
[ 72%] Built target fft_block_test
[ 72%] Built target addr_test
[ 72%] Built target convert_test
[ 72%] Built target cast_test
[ 72%] Built target cal_database_test
[ 72%] Built target cal_data_dsa_test
[ 72%] Built target link_test
[ 72%] Built target byteswap_test
[ 73%] Built target cal_data_iq_test
[ 73%] Built target log_test
[ 73%] Built target isatty_test
[ 74%] Built target window_block_test
[ 74%] Built target chdr_parse_test
[ 75%] Built target subdev_spec_test
[ 75%] Built target rfnoc_node_test
[ 75%] Built target math_test
[ 75%] Built target compat_test
[ 75%] Built target ranges_test
[ 75%] Built target eeprom_utils_test
[ 75%] Built target cal_data_gain_pwr_test
[ 75%] Built target fp_compare_delta_test
[ 75%] Built target serial_number_test
[ 75%] Built target dict_test
[ 76%] Built target replay_block_test
[ 77%] Built target fe_conn_test
[ 77%] Built target sph_send_test
[ 77%] Built target actions_test
[ 77%] Built target time_spec_test
[ 77%] Built target tasks_test
[ 77%] Built target property_test
[ 78%] Built target system_time_test
[ 78%] Built target vrt_test
[ 79%] Built target fir_filter_block_test
[ 80%] Built target streamer_benchmark
[ 80%] Built target rfnoc_topograph_test
[ 81%] Built target client_zero_test
[ 81%] Built target expert_test
[ 81%] Built target block_id_test
[ 82%] Built target rfnoc_property_test
[ 83%] Built target rfnoc_chdr_test
[ 83%] Built target multichan_register_iface_test
[ 84%] Built target buffer_test
[ 84%] Built target eeprom_c_test
[ 85%] Built target soft_reg_test
[ 86%] Built target error_c_test
[ 89%] Built target x4xx_radio_block_test
[ 89%] Built target ranges_c_test
[ 90%] Built target transport_test
[ 91%] Built target rx_streamer_test
[ 92%] Built target config_parser_test
[ 92%] Built target moving_average_block_test
[ 92%] Built target sph_recv_test
[ 92%] Built target sensors_c_test
[ 92%] Built target subdev_spec_c_test
[ 92%] Built target rfnoc_detailgraph_test
[ 92%] Built target octoclock_burn_eeprom
[ 92%] Built target b2xx_fx3_utils
[ 92%] Built target uhd_config_info
[ 93%] Built target uhd_usrp_probe
[ 94%] Built target uhd_find_devices
[ 94%] Built target uhd_image_loader
[ 94%] Built target uhd_adc_self_cal
[ 95%] Built target uhd_cal_rx_iq_balance
[ 95%] Built target uhd_cal_tx_dc_offset
[ 95%] Built target uhd_cal_tx_iq_balance
[ 95%] Built target usrp_burn_db_eeprom
[ 95%] Built target usrp_burn_mb_eeprom
[ 95%] Built target converter_benchmark
[ 95%] Built target query_gpsdo_sensors
[ 95%] Built target fx2_init_eeprom
[ 97%] Built target man_page_gzips
[ 98%] Built target doxygen_docs
[ 98%] Building CXX object python/CMakeFiles/pyuhd.dir/pyuhd.cpp.o

Then after a long time of the machine staying at 98% it crashes and spits this out 

"Building CXX object python/CmakeFiles/pyuhd.dir/pyuhd.cpp.o Then it says: c++: fatal error: killed signal terminated program cc1plus compilation terminated. make[2]: *** [python/cmakefiles/pyuhd.dir/build.make:82: python/Cmakefiles/pyuhd.dir/pyuhd.cpp.o] error 1 make[1]: *** [cmakefiles/makefiles2:5431: python/cmakefiles/pyuhd.dir/all] error2 make: *** [Makefile:182: all] Error 2

I hope this has everything you need.

**Comment by NI-LAm** [comment]
So, your config looks good. From the error message you get and the RasPi you are using I assume you run out of memory during compilation (pyuhd.cpp is huge, it contains the full Python interface for UHD). If that's the case, you have several options:
* remove the Python interface if you don't need it (run cmake with `DENABLE_PYTHON_API=OFF`)
* increase the swap size on your PI (https://linuxhint.com/increase-memory-raspberry-pi/), this will further slow down your compilation process on the RasPI, because swap is so much slower than RAM.
* cross compile (e.g. using this https://github.com/tttapa/docker-arm-cross-toolchain) might be more effort at the beginning but compile times will reduce drastically.

As a side node. When building UHD yourself for this specific platform you might want to disable components you don't need (e.g. disable all the devices you do not need support for).

**Comment by Haider037** [comment]
Okay after removing the python interface everything installed and make passed with no errors. But now when I am creating my code on gnu radio and running it on my pi this is what comes up 

Generating: '/home/.../uhd/host/build/fmReceiver.py'

Executing: /usr/bin/python3 -u /home/.../uhd/host/build/fmReceiver.py

[INFO] [UHD] linux; GNU C++ version 10.2.0; Boost_107100; UHD_3.15.0.0-4
[WARNING] [B200] EnvironmentError: IOError: Could not find path for image: usrp_b200_fw.hex

Using images directory: <no images directory located>

Set the environment variable 'UHD_IMAGES_DIR' appropriately or follow the below instructions to download the images package.

Please run:

 "/lib/arm-linux-gnueabihf/uhd/utils/uhd_images_downloader.py"
Traceback (most recent call last):
  File "/home/.../uhd/host/build/fmReceiver.py", line 263, in <module>
    main()
  File "/home/.../uhd/host/build/fmReceiver.py", line 239, in main
    tb = top_block_cls()
  File "/home/.../uhd/host/build/fmReceiver.py", line 83, in __init__
    self.uhd_usrp_source_0 = uhd.usrp_source(
  File "/usr/lib/python3/dist-packages/gnuradio/uhd/__init__.py", line 125, in constructor_interceptor
    return old_constructor(*args)
  File "/usr/lib/python3/dist-packages/gnuradio/uhd/uhd_swig.py", line 2791, in make
    return _uhd_swig.usrp_source_make(device_addr, stream_args, issue_stream_cmd_on_start)
RuntimeError: LookupError: KeyError: No devices found for ----->
Empty Device Address

>>> Done (return code 1)

I ran the exact same code on my MacBook and used the same usrp device and it connected/ worked perfectly. But on my pi this is what comes up.

**Comment by Haider037** [comment]
I have installed all the images necessary, or at least I think I have and I see the files under the utils and the build directories

**Comment by Haider037** [comment]
Yes it is connected to my Pi via usb and when I run uhd_find_devices it shows up with the serial number and everything as well

**Comment by Haider037** [comment]
are you sure I will need the interface? because I have seen it work without I think, unless I am mistaken.

**Comment by Haider037** [comment]
I re installed the uhd with the python interface but it still says that it cant read the device on gnu radio, but when I run uhd_find_devices or uhd_usrp_probe the device comes up.

**Comment by Haider037** [comment]
Im using the companion

**Comment by NI-LAm** [comment]
Is the companion running on the Pi or on your Mac?

**Comment by Haider037** [comment]
pi all of this is on my pi

**Comment by NI-LAm** [comment]
The GRC script says it tries to load a 3.15 UHD version. Is that the one you have build on your Pi? How did install the companion? Did you compiled it by youself or via package manager? In both cases can you share some details about the versions you use? You might have to tell GRC where to find your UHD binaries.

**Comment by mbr0wn** [comment]
Summarizing this thread:
- RPi3 is not beefy enough to build Python API natively (cross-compiling may work)
- GNU Radio does not require Python API
- Looks like a UHD version mismatch on the Pi
