### ISSUE TITLE
B2x0 GPSDO does not work

### ISSUE THREAD

**Issue by n-west** [EttusResearch/uhd#70]
This is the offending commit / area of code: https://github.com/EttusResearch/uhd/commit/90a5d3153e04b6d0b95e51bc84cf396a4e009c07#diff-bd92c3fd62d7d78c6251663f4b1327f6R214

My B2x0 + GPSDO returns "GPSTCXO , Firmware Rev 0.929a" which is not detected as a valid GPSDO by the new code.

**Comment by mbr0wn** [comment]
@michael-west Has a fix -- will get merged tomorrow. Thanks for bringing up! Closing this particular issue for now.
