### ISSUE TITLE
Deprecated boost header

### ISSUE THREAD

**Issue by kb6ibb** [EttusResearch/uhd#700]
## Issue Description ##
Building CXX object python/CMakeFiles/pyuhd.dir/__/lib/usrp/multi_usrp_python.cpp.o
In file included from /usr/include/boost/smart_ptr/detail/sp_thread_sleep.hpp:22,
                 from /usr/include/boost/smart_ptr/detail/yield_k.hpp:23,
                 from /usr/include/boost/smart_ptr/detail/spinlock_gcc_atomic.hpp:14,
                 from /usr/include/boost/smart_ptr/detail/spinlock.hpp:42,
                 from /usr/include/boost/smart_ptr/detail/spinlock_pool.hpp:25,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:29,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /usr/include/boost/format/alt_sstream.hpp:22,
                 from /usr/include/boost/format/internals.hpp:24,
                 from /usr/include/boost/format.hpp:38,
                 from /home/kb6ibb/src/UHD/uhd-4.4.0.0/host/include/uhd/types/dict.ipp:12,
                 from /home/kb6ibb/src/UHD/uhd-4.4.0.0/host/include/uhd/types/dict.hpp:154,
                 from /home/kb6ibb/src/UHD/uhd-4.4.0.0/host/include/uhd/types/device_addr.hpp:11,
                 from /home/kb6ibb/src/UHD/uhd-4.4.0.0/host/include/uhd/stream.hpp:11,
                 from /home/kb6ibb/src/UHD/uhd-4.4.0.0/host/include/uhd/device.hpp:12,
                 from /home/kb6ibb/src/UHD/uhd-4.4.0.0/host/include/uhd/usrp/multi_usrp.hpp:28,
                 from /home/kb6ibb/src/UHD/uhd-4.4.0.0/host/lib/usrp/multi_usrp_python.cpp:15:
/usr/include/boost/detail/iterator.hpp:13:1: note: ‘#pragma message: This header is deprecated. Use <iterator> instead.’
   13 | BOOST_HEADER_DEPRECATED("<iterator>")
      | ^~~~~~~~~~~~~~~~~~~~~~~

## Setup Details ##
Red Hat Enterprise Linux 9.2
gcc version 11.3.1 20221121 (Red Hat 11.3.1-4) (GCC)

## Expected Behavior ##
Build without warnings or errors on up to date system.

## Actual Behaviour ##
Multiple warnings generated during build

## Steps to reproduce the problem ##
cmake -DLIB_SUFFIX=64 ../
![Screenshot from 2023-09-01 09-57-22](https://github.com/EttusResearch/uhd/assets/71456603/689870f5-a24b-4201-8046-2bea8e3e6b45)
![Screenshot from 2023-09-01 09-57-22](https://github.com/EttusResearch/uhd/assets/71456603/7c92a81f-295c-4844-9bcc-dbc836d84d5d)

make -j6

**Comment by mbr0wn** [comment]
@kb6ibb Thanks for reporting. From your error message, it seems like this is a Boost-internal issue (since it stems from including `boost/format.hpp`, which we need and which is a standard include). I've also not seen this error before, which tells me there's a bunch of Boost versions that don't have this issue. In that case, there's nothing we can do about it. Closing this issue.
