### ISSUE TITLE
The driver for ADC/DAC is located where?

### ISSUE THREAD

**Issue by MeiMingLhz** [EttusResearch/uhd#702]
## Issue Description ##
Hello! I'm using USRP X310 and I want to modify the ADC/DAC driver in UHD 4.5.0 to suit my needs. Can you tell me where the ADC/DAC driver implementation is located? Is it implemented using the C++ API on the PC or is it embedded in the FPGA code driven by a state machine? Where are the driver files for the ADC/DAC located?

**Comment by mbr0wn** [comment]
Mostly here: https://github.com/EttusResearch/uhd/tree/master/host/lib/usrp/x300
