### ISSUE TITLE
detection of RF signal with USRP X310

### ISSUE THREAD

**Issue by PHDsaoudi** [EttusResearch/uhd#704]
Hello;

I need to detect RF signal with USRP X310. I would like to know how can i connect USRP X310 with our PC in order to disply the RF signal using Python langage; I'm so gratefull if you can send me a clear tutorial how to configue USRP X310 using Python langage.

**Comment by mbr0wn** [comment]
@PHDsaoudi This is a big question. I suggest starting going through our tutorials (e.g. from here: https://kb.ettus.com/Knowledge_Base)
