### ISSUE TITLE
tx_waveforms' power argument does not work correctly with all channels

### ISSUE THREAD

**Issue by joelkeeling** [EttusResearch/uhd#705]
## Issue Description ##
The example program tx_waveforms does not properly handle the power argument with all channels

## Setup Details ##
Run the example program with the '--power' argument AND set the '--channels' argument to any valid channel besides '0'

## Expected Behavior ##
The power would be correctly configured for the specific channel(s)

## Actual Behaviour ##
Configuration settings get written to the incorrect channel(s)

## Steps to reproduce the problem ##
I will instead describe the fix to the problem:
There is an error in the set_tx_power_reference call, **ch** should actually be **channel_nums[ch]**

## Additional Information ##
We have corrected this issue on our local system. If time permits, I hope to provide a small Pull Request to correct the issue.

**Comment by manderseck** [comment]
Thanks for reporting and fixing these issues. Your changes have been merged into our internal master and will be publicly available with the next push to the public uhd repo.
