### ISSUE TITLE
tx_samples_from_file only works with channel 0

### ISSUE THREAD

**Issue by joelkeeling** [EttusResearch/uhd#706]
## Issue Description ##
The example program tx_samples_from_file does not properly handle the channel argument

## Setup Details ##
Run the example program with the '--channel' argument set to anything but '0'

## Expected Behavior ##
The transmission would be correctly configured for the specified channel

## Actual Behaviour ##
Configuration settings always get written to channel 0

## Steps to reproduce the problem ##
I will instead describe the fix to the problem:
Many calls throughout the example rely on function "default arguments" to set the channel. In most cases the default is channel '0'.
Calls that could, but don't specify the channel are: set_tx_rate, set_tx_freq, set_tx_gain, set_tx_bandwidth set_tx_antenna

## Additional Information ##
We have corrected this issue on our local system. If time permits, I hope to provide a small Pull Request to correct the issue.

**Comment by manderseck** [comment]
Thanks for reporting and fixing these issues. Your changes have been merged into our internal master and will be publicly available with the next push to the public uhd repo.
