### ISSUE TITLE
Test URSP functionality

### ISSUE THREAD

**Issue by pemo75** [EttusResearch/uhd#721]
Hello community,

I am currently working on testing URSP b210 functionality, I am seeking guidance on how to ensure that it is working properly?
Thank you in advance for your time and assistance. I appreciate any guidance or suggestions you can provide.

**Comment by manderseck** [comment]
@pemo75 Sounds like this is not actually a software or hardware issue. Please read the [Getting Started Guides for the B210](https://kb.ettus.com/B200/B210/B200mini/B205mini_Getting_Started_Guides) over at the [Ettus Knowledge Base](https://kb.ettus.com/Knowledge_Base) which provides information about technical support, too. I'm closing this issue.
