### ISSUE TITLE
Why libsrsran_rf_uhd.so give an error

### ISSUE THREAD

**Issue by zapatista06** [EttusResearch/uhd#725]
Hello I wanna run srsenb but libsrsran_rf_uhd gives an error. Can you help me ?

**Skipping RF plugin libsrsran_rf_uhd.so: /usr/local/lib/libsrsran_rf_uhd.so: undefined symbol: _Z24error_from_uhd_exceptionPKN3uhd9exceptionE**
Active RF plugins: libsrsran_rf_soapy.so libsrsran_rf_blade.so libsrsran_rf_zmq.so
Inactive RF plugins: libsrsran_rf_uhd.so 
---  Software Radio Systems LTE eNodeB  ---

Reading configuration file enb.conf...

Built in Release mode using commit af4b9589b on branch master.

Opening 1 channels in RF device=bladeRF with args=default
connect(): Connection refused
Supported RF device list: <none>
Failed to initiate S1 connection. Attempting reconnection in 10 seconds
Opening bladeRF...
Set RX sampling rate 1.92 Mhz, filter BW: 1.92 Mhz

==== eNodeB started ===
Type <t> to view trace
Set RX sampling rate 11.52 Mhz, filter BW: 9.22 Mhz
Setting frequency: DL=2680.0 Mhz, UL=2560.0 MHz for cc_idx=0 nof_prb=50
set TX frequency to 2680000000
set RX frequency to 2560000000

**Comment by mbr0wn** [comment]
This  doesn't immediately seem like a UHD bug. It looks like streaming, tuning are working.
