### ISSUE TITLE
RFNoC on the X300/310 Specification Doc

### ISSUE THREAD

**Issue by max596789** [EttusResearch/uhd#73]
I had a question about the RFNoC Specification page:

Under current issues, it states that "In its current state, the X300 implementation class is very much hard-coded around a specific setup, which means there's two radios, and little else"

Which implementation is this? By implementation do you mean a specific daughter board setup? If so, which daughter board is used for RFNoC. I would rather buy a the setup from ettus that is know to work instead of buying daughterboards that end up not being the correct ones.

**Comment by mbr0wn** [comment]
@max596789 please ask this on the mailing list or at support@ettus.com.

The sentence you quote is outdated. However, it doesn't mean what you think it does: The choice of daughterboards was never limited by RFNoC. There are some legacy daughterboards that do not work with X310, but any of the current daughterboards you can purchase *will* work.
