### ISSUE TITLE
N310:SFP0 Unreachable

### ISSUE THREAD

**Issue by GershomSandeep** [EttusResearch/uhd#746]
Hi

I followed this steps to achieve 10 Gigabit Ethernet interface on SFP Port 1 but am receiving unreachable response from the Host and green light is not illuminating Please advice me on this issue.

NOTE: USRP N310 loaded with  XG FPGA image
1. Configure your Host's 10Gb Ethernet adapter as shown below.

   IP Address: 192.168.20.1
   Subnet Mask: 255.255.255.0
   Gateway: 0.0.0.0
   MTU: 9000

NOTE: When operating at 10Gb speeds, it is important to set a MTU of 9000 and not a value of automatic.

2. Connect the USRP to a host computer using either a 10Gb SFP or Fiber cable to SFP Port 1.

The ​ Green LED​ above ​SFP Port 1​ should illuminate.

3. To test the connection,​ ​ping​ the device at address 192.168.20.2​ from the host, as shown below:

   $ ping 192.168.20.2

Press CTRL+C to stop the ping program.

**Comment by wordimont** [comment]
From the comment in https://github.com/EttusResearch/uhd/issues/745 with the pictures you posted (now deleted?), it looked like it had 1 GbE equipment connected to the SFP ports. So I would expect the link LED to be on for SFP0 until you download the XG image, then it would no longer work. If using the XG image, please ensure you have a 10 GbE SFP cable connected to a 10 GbE Ethernet card on the connected computer. You need to make sure the devices link (indicated by the green LED next to the SFP port) before you try to ping.

**Comment by GershomSandeep** [comment]
thank you so much:-)

**Comment by GershomSandeep** [comment]
Today I was trying N310 with srsRAN, i don't no what happened suddenly its restarting continuously. Even i tried by resetting the devices but no use. so please advise me on this issue.

**Comment by wordimont** [comment]
You probably need to re-image your SD card to a known good state. At this point I suggest your reach out to technical support. https://www.ettus.com/support/

**Comment by GershomSandeep** [comment]
sure thank you.
