### ISSUE TITLE
USRP N310 with UHD 4.6.0 imcompatiable?

### ISSUE THREAD

**Issue by 1ifeofcho** [EttusResearch/uhd#747]
Hi I am trying to update the file system of USRP N310 but there seems to be a weird behavior. 

Currently using N310 with 1GbE equipment connected to a host computer.
Before updating the file system, the N310 worked perfectly fine as in the SFP Port 0 illuminated fine and I was able to access the device via ssh. But after updating the file system via mender and rebooted N310 it does not reboot.

I expected it to reboot but it took forever to reboot(cannot ping the device or access it via ssh) so I forced quit and restarted the N310 device but when it does that, the file system is not updated. So I tried to update the N310 device by writing the disk image but this time the same issue(cannot ping the device or access it via ssh) occurred. 

After working with it for a while, I realized that now instead of SFP Port 0, SFP Port 1(Instead of Port 0, Port 1 illuminates) works. I do not quite get why this is happening and was wondering why the device is behaving this way.

**Comment by manderseck** [comment]
@1ifeofcho Which was the previous version that you've used and where it worked correctly?
