### ISSUE TITLE
Adding fft in fpga resulting in CODEC loopback test failed 

### ISSUE THREAD

**Issue by dheller26** [EttusResearch/uhd#750]
hello everyone ,
i'm using the b205mini usrp and I need to implement a fft block on the fpga inside the usrp and pc gets the data in freq domain. I designed my fft using xilinx IP core ver 7.1 and place it in the top module after the b205_io module using it's 12 bits I & Q ports .
unfortunately when testing my design in gnuradio i got ERROR CODEC loopback test failed  as you can see below.

what can be the problem ? when my design is clean without fft i don't get errors like that .
i will appreciate your help.
with best regards .
Dror 
![Screenshot from 2024-05-12 15-48-31](https://github.com/EttusResearch/uhd/assets/79789844/543b267b-00f8-47e5-9adb-91c50e9142ba)

**Comment by mbr0wn** [comment]
If you want to put the FFT before `b205_io` then you need to disable the codec loopback in the UHD driver. Probably much easier to stay on the other side of `radio_legacy` and work on the `rx_t*` signals (AXI-stream).
