### ISSUE TITLE
uhd_cal_rx_iq_balance documentation error

### ISSUE THREAD

**Issue by esromneb** [EttusResearch/uhd#76]
The man page for uhd_cal_rx_iq_balance says that the --tx_wave_ampl is measured in "counts" but isn't it measured in a 0 -> 1  scale?  I thought the word "counts" was reserved for raw integer values that an dac or adc would use. (and is therefor dependent on how many bits the dac/adc is)

https://github.com/EttusResearch/uhd/blob/master/host/utils/uhd_cal_rx_iq_balance.cpp#L119

**Comment by mbr0wn** [comment]
@esromneb Good catch, thanks.
