### ISSUE TITLE
Generate Vitis Project to use USRP on standalone mode 

### ISSUE THREAD

**Issue by Emreyldz06** [EttusResearch/uhd#774]
## Issue Description ##

UHD ps side reconfiguration in standalone mode 
## Setup Details ##

Ubuntu 18.04 
UHD 4.6
## Expected Behavior ##

We want to configure Vitis project (PS side application) 
## Actual Behaviour ##

We ordered USRP E320 device and we aim to use UHD 4.6 or 4.7 (latest versions). Before our order delivered to us, we made quick research on your opensource repository. We generated the .xpr file of XG_ethernet example project from fpga/top/usrp3/e320 directory with using vivado in GUI mode. Here we noticed that its all includes PL design and PS connections. We don't want to use any oot application like gnuradio and even our desktop computer to control usrp. We want to run that device standalone. According to the information we obtained from forums device has embedded linux on ps side. However, we could not generate vitis project like as we did on vivado.We want to use C++ api on PS. Is there a any guide document how to use and reconfigure vitis project with shared api's. Could you please help us with that? 

Thanks for your help,
Sincerely.
Emre

**Comment by mbr0wn** [comment]
@Emreyldz06 this is not a support forum, so I'm closing this. However, you can run C++ applications on the PS, link them against UHD (which is available on the PS) and so on. The only downside really is the limited CPU capabilities and the available bandwidth from PS to PL (a few Msps). Check out our knowledge base. Other than that, you even have compilers on the embedded Linux so can do quite a bit (for professionally done deployments, we recommend our OpenEmbedded build flow and either making custom filesystems or installing .ipk files). So, desktop computer or other device is only necessary for development, not deployment.
