### ISSUE TITLE
Analog Bandwidth with X310 and TwinRx Daughterboard

### ISSUE THREAD

**Issue by vahidrezaee** [EttusResearch/uhd#777]
## Issue Description ##

I'm using an X310 USRP with a single TwinRx daughterboard on Ubuntu 20.04 with UHD 4.6. I'm attempting to modify the analog bandwidth in the rx_ascii_art_dft.cpp example, but I'm not seeing any changes in the output.

I'm uncertain about the following:

Is it possible to change the analog bandwidth of a TwinRx daughterboard?
If so, what is the expected behavior when changing the analog bandwidth, as I'm not observing any visible changes.
I've tried setting different bandwidth values, but the output remains consistent.
## Setup Details ##

UHD 4.6
and exacuting the  rx_ascii_art_dft.cpp  example
## Expected Behavior ##

in the attachment  there are two picture  the number one is with the bandwidth is 80 MHz and second is when the bandwidth is 10 Mhz
![Screenshot from 2024-08-01 10-47-40](https://github.com/user-attachments/assets/9757a649-44b8-41cc-aa95-63010e032324)
![Screenshot from 2024-08-01 10-50-25](https://github.com/user-attachments/assets/5fd7f37d-2146-464a-9e4c-aade3a8c495d)

**Comment by gmeyerho** [comment]
Hello @vahidrezaee, the bandwidth range for the TwinRX is actually a set value, if you run uhd_usrp_probe for your device, you will see the bandwidth range under the daughterboards listed as 80MHz to 80MHz. 

However the property for setting the bandwidth value does not do any coercion based on this range, thus giving you the illusion that you are setting the bandwidth.

Thank you for pointing this out, I will put up a change to fix this.
