### ISSUE TITLE
UHD 4.7 with DPDK >=22.11 still not able to start with latest fix commit (8305d)

### ISSUE THREAD

**Issue by Welly-Huang** [EttusResearch/uhd#795]
## Setup Details ##

Master branch which Includes the commit - 8305d925176fed1fd7f375e3ae8d9de0b72b04d4
Re-compiled

- UHD Version: 4.7
- FPGA: HG (port 0: 1G / port 1: 10G)
- PC connected to USRP via RJ45
- An Intel X710 network card supporting dual SFP+ is also available
- Due to the lack of SFP+ cables, I am using RJ45 with an adapter connected to the Intel X710 SFP+ interface and the USRP SFP+ port 0

## Expected Behavior ##
The multi_usrp is able to instantiate with DPDK

## Actual Behaviour ##
---

[INFO] [UHD] linux; GNU C++ version 11.4.0; Boost_107400; DPDK_23.11; UHD_4.7.0.0-0-unknown
EAL: Detected CPU lcores: 32
EAL: Detected NUMA nodes: 1
EAL: Detected shared linkage of DPDK
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'VA'
EAL: VFIO support initialized
EAL: Probe PCI driver: mlx5_pci (15b3:1019) device: 0000:01:00.0 (socket -1)
EAL: Probe PCI driver: mlx5_pci (15b3:1019) device: 0000:01:00.1 (socket -1)
EAL: Using IOMMU type 1 (Type 1)
EAL: Probe PCI driver: net_i40e (8086:1572) device: 0000:02:00.0 (socket -1)
EAL: Probe PCI driver: net_i40e (8086:1572) device: 0000:02:00.1 (socket -1)
TELEMETRY: No legacy callbacks, legacy socket not created
[ERROR] [UHD] Device discovery error: vector::_M_range_check: __n (which is 3) >= this->size() (which is 1)
[HW]   No USRP Device Found.

---

## Steps to reproduce the problem ##
Download the latest source codes, and compile it.
Run it with
`$ sudo ./benchmark_rate     --args "type=n3xx,mgmt_addr=192.168.1.151,addr=192.168.20.2,master_clock_rate=125e6,use_dpdk=1"    --duration 60    --channels "0"    --rx_rate 31.25e6    --rx_subdev "A:0"    --tx_rate 31.25e6    --tx_subdev "A:0"`

**Comment by joergho** [comment]
We found another issue which is fixed with commit 40a02c0784b8d567991512fb5164ba33c1c3d1b8. Please check with the latest `master`.
