### ISSUE TITLE
CMake issue with older GNU tools

### ISSUE THREAD

**Issue by CodaCarlson** [EttusResearch/uhd#82]
I am using CentOS 6.8 and now get a build error during the make. In the CMakeLists file there is a check for CMAKE_VERSION less than 3.1 and if it's using the GNU compiler than it will add the following flag "std=gnu++11". Unfortunately the version of g++ installed is 4.4.7 and gnu++11 is not supported. I had to modify this to be std=c++0x. This is necessary when g++ is less than 4.7 i believe. I know these are super old versions, just wanted to let you know in case you wanted to fix up the CMakeLists.

As a side note in order to get uhd to build I  have to install an alternate version of python as well since there is a system dependency on 2.6 and 2.7 is now a requirement.

**Comment by mbr0wn** [comment]
Just for the record and to confirm, gcc 4.4 is no longer supported with UHD 3.10 and up. The `gnu++11` extension is required for master branch (3.11 and up).
