### ISSUE TITLE
N300 device not found

### ISSUE THREAD

**Issue by CarlosD1119** [EttusResearch/uhd#820]
I encountered some issues while configuring the N300. The N300 responds to my ping requests, but the host cannot find the device using the command `uhd_find_devices` while correctly detecting my b210 device. I referred to [[this post on StackOverflow](https://stackoverflow.com/questions/33304828/when-trying-to-use-my-usrp-in-gnu-radio-i-get-a-no-devices-found-for?rq=1)], but adding parameters and modifying the firewall settings did not resolve the issue. I believe my network is correctly configured, and my UHD version is up to date.
![QQ_1734107185096](https://github.com/user-attachments/assets/656762c2-b63e-4379-9f5d-bfc4312b2629)
![QQ_1734107162725](https://github.com/user-attachments/assets/dc6e6176-c438-4880-8e5e-3ae39d4eec0f)

**Comment by mbr0wn** [comment]
I'm not sure where those screenshots were taken (is this on your host computer, or did you add a graphical network tool to the USRP?).

This looks more like a support request than a bug report in UHD, so I'm closing this. Some pointers for you:
- Connect the N300 to a DHCP-managed network using the RJ45. You can figure out the IP address by logging into your USRP using the serial console, or maybe you have a network management. Then try again to ping, try to `ssh root@<address>`, and then finally `uhd_usrp_probe --args addr=<address>`.
- Using `addr=<address>` also works for `uhd_find_devices`, so try that.
- Ping will work on anything, which means if you get a ping response, you might actually be getting it from something else. Make sure it's from the device.
