### ISSUE TITLE
UHD_VERSION is missing in usrp.h

### ISSUE THREAD

**Issue by aholtzma** [EttusResearch/uhd#84]
The preprocessor symbol for UHD_VERSION is missing in the C api header. It would be useful to have it.

**Comment by mbr0wn** [comment]
Excellent catch.

**Comment by mbr0wn** [comment]
I have a fix for this queued up. Will get merged soon and will go onto maint.

**Comment by aholtzma** [comment]
Can you put this in 3.9.6? This would be most useful when switching between 3.9 and 3.10.

**Comment by mbr0wn** [comment]
We missed this on the LTS branch, but it's fixed now.
