### ISSUE TITLE
Always receive S or U while operating with packet_len tag

### ISSUE THREAD

**Issue by jblandrum** [EttusResearch/uhd#86]
linux; GNU C++ version 5.2.1 20151010; Boost_105800; UHD_3.11.0.git-28-gc66cb1ba

Using code located here in the interpreter
http://dpaste.com/22TR8CV

```
import mydemo as d
tb = d.generate_top_block(True,False)
tb.start()
tb.post_pdu( <arbitrary string of ones and zeros here> )
```
NOTE: with the demo code the generate_top_block function isn't passing the debug argument along to the class so in order to use the debug functions that needs to be hand jammed first.

quitting and restarting because the only way I can reproduce the errors, they only print the first or second transmission. I'm repeating the same PDU several times. 
I changed the sizes of the initial transmission around and found that anything 32 bits and shorter immediately print a U and then no fuss with following transmission attempts that run of the program.
Anything with 33 or greater bits input initial transmission is transmitted on the first attempt; the second attempt yields an S then 3rd onward goes merrily along with no issues.
Now there's a interpolater in there so the size of the complex buffer on the output side is larger than the bit input and I haven't attempted to get any more granular than tuning the number of bits going into the interpolater. However, if you `generate_top_block(True,True)` then it should enable some debugging vectors that will allow you to` len(tb.v_mltply_out.data())` and see how much stuff is getting shipped off to the USRP

**Comment by mbr0wn** [comment]
We're lacking a lot of info, and this could originate from anywhere (although you should never see "S", but "U" are fine). Please take this to the mailing list, and provide info such as the device used. I'm closing until we're sure this is a UHD issue.
