### ISSUE TITLE
Build: 71 succeeded, 1 failed, 0 up-to-date, 6 skipped

### ISSUE THREAD

**Issue by commthu** [EttusResearch/uhd#96]
I follow this link to build UHD in windows
https://kb.ettus.com/Building_and_Installing_the_USRP_Open_Source_Toolchain_(UHD_and_GNU_Radio)_on_Windows

finally, i got Build: 71 succeeded, 1 failed, 0 up-to-date, 6 skipped. the fail reason is the error as followings:

2>libusb1_control.obj : error LNK2019: unresolved external symbol _libusb_control_transfer@32 referenced in function "public: virtual int __thiscall libusb_control_impl::submit(unsigned char,unsigned char,unsigned short,unsigned short,unsigned char *,unsigned short,unsigned int)" (?submit@libusb_control_impl@@UAEHEEGGPAEGI@Z)
2>libusb1_zero_copy.obj : error LNK2019: unresolved external symbol _libusb_alloc_transfer@4 referenced in function "public: __thiscall libusb_zero_copy_single::libusb_zero_copy_single(class boost::shared_ptr<class uhd::transport::libusb::device_handle>,int,unsigned char,unsigned int,unsigned int)" (??0libusb_zero_copy_single@@QAE@V?$shared_ptr@Vdevice_handle@libusb@transport@uhd@@@boost@@HEII@Z)

2>libusb1_base.obj : error LNK2019: unresolved external symbol _libusb_exit@4 referenced in function "public: virtual __thiscall libusb_session_impl::~libusb_session_impl(void)" (??1libusb_session_impl@@UAE@XZ)

**Comment by mbr0wn** [comment]
This doesn't seem like an UHD error, so please take this to usrp-users. If we figure out it's a UHD issue, we'll reopen. Thanks!
